// Package model holds the GORM models of the kun_trust database — the Trust &
// Safety platform's storage layer (doc 18 §4). ONE platform service: universal
// report intake + a single cross-site review inbox + dispositions with an
// enforcement-callback loop + an append-only audit hash chain.
//
// Storage conventions (章程 ruling 4 — the GORM-trap discipline, mirrored from
// the catalog/community models):
//
//   - Identity primary keys are `bigint GENERATED BY DEFAULT AS IDENTITY`
//     (the catalog/community recipe — every part of the tag is load-bearing;
//     see internal/platform/catalog/model/person.go for the full rationale).
//     BY DEFAULT (not ALWAYS) keeps explicit-id writes possible for
//     cross-environment moves and test provisioning.
//   - INTENT columns whose ZERO value is meaningful (site / subject_kind /
//     subject_id / source / status / action / severity / weight / priority /
//     reason_code …) are `not null` WITHOUT a gorm default tag: a default tag
//     makes GORM omit the zero from INSERTs and the DB default silently wins
//     (the catalog trust_tier lesson). The value is always written explicitly
//     by the service layer.
//   - BOOKKEEPING columns whose creation-time value is fixed (is_deprecated →
//     false, callback_attempts → 0) keep their DDL default — their initial
//     value is not a meaningful caller choice.
//   - Every tenant row leads its access indexes with `site` (invariant 11).
//   - Acronym columns (NameCN) carry an explicit column tag to dodge the
//     b_i_d / name_c_n snake-case trap.
//
// These are CODE-COUPLED enum constants: adding a value ships with new code, so
// smallint constants are the right form. All values are persisted; NEVER
// renumber an existing constant.
package model

// Report status (trust_report.status) — invariant 10. received is the fresh
// intake; linked = aggregated into an open review item; folded = attached to a
// recently-dismissed item inside the negative-knowledge window (章程 ruling 8).
const (
	ReportStatusReceived int16 = 0
	ReportStatusLinked   int16 = 1
	ReportStatusFolded   int16 = 2
)

// Review-item source (trust_review_item.source) — why the item entered the
// unified inbox (doc 18 §4.2). reports is the P0 driver; ai_text/ai_image/
// community_forward are placeholder constants defined now, wired in later
// phases (章程 ruling: define before use, never renumber).
const (
	ReviewSourceReports          int16 = 0
	ReviewSourceAIText           int16 = 1
	ReviewSourceAIImage          int16 = 2
	ReviewSourceCommunityForward int16 = 3
	ReviewSourceMislabel         int16 = 4
	ReviewSourceManual           int16 = 5
)

// Review-item status (trust_review_item.status). pending/claimed are the OPEN
// states (the partial unique — invariant 4 — keys on them); actioned/dismissed
// are terminal.
const (
	ReviewStatusPending   int16 = 0
	ReviewStatusClaimed   int16 = 1
	ReviewStatusActioned  int16 = 2
	ReviewStatusDismissed int16 = 3
)

// Disposition action (trust_disposition.action) — the enforcement decision the
// product executes via callback (doc 18 §4.2). none is a meaningful zero
// (a decision that records a judgement but takes no enforcement action).
const (
	ActionNone        int16 = 0
	ActionHide        int16 = 1
	ActionRemove      int16 = 2
	ActionWarnUser    int16 = 3
	ActionRestrict    int16 = 4
	ActionEscalateIDP int16 = 5
)

// Callback status (trust_disposition.callback_status; NULLABLE — a disposition
// on a subject_kind with no callback_url stays NULL = human-only enforcement).
// pending → delivered on a 2xx, or → dead_letter after the retry budget is
// exhausted (章程 ruling 9, invariant 13).
const (
	CallbackStatusPending    int16 = 0
	CallbackStatusDelivered  int16 = 1
	CallbackStatusDeadLetter int16 = 2
)

// Scan status (trust_scan_result.status) — the AI shadow-scoring pipeline (step
// 03). pending is the fresh intake; the scoring worker drives it to a TERMINAL
// state: scored (the gateway returned a verdict) or degraded (the gateway is
// unconfigured / degraded / failed). degraded is terminal — the worker only ever
// claims pending, so the queue always DRAINS and never backs up unbounded.
const (
	ScanStatusPending  int16 = 0
	ScanStatusScored   int16 = 1
	ScanStatusDegraded int16 = 2
)

// Scan mode (trust_scan_result.mode) — 0=shadow is the ONLY mode this step
// ships and is hardcoded at intake. Shadow means the pipeline records a verdict
// and NOTHING else: no review item, no callback, no enforcement. live/enqueue
// modes (feeding the inbox) are P2 (doc 18 §6; step 03 explicitly out of scope).
const (
	ScanModeShadow int16 = 0
)

// Tier0 term kind (trust_term.kind) — the deterministic word-list enforcement
// intent (step 05; doc 18 §6). suspect = a hold signal (the sync check returns
// "hold" → the caller routes to review, content still flows); banned = a deny
// signal (the sync check returns "deny" → the caller blocks). An INTENT column:
// the zero (suspect) is meaningful, so the model carries NO default tag.
const (
	TermKindSuspect int16 = 0
	TermKindBanned  int16 = 1
)
