package model

import "time"

// TrustDisposition is the record of an enforcement decision on a review item
// (doc 18 §4.2). Every actioned decision produces one, carrying the Art.17
// reason statement. When the subject_kind has a callback_url the dispatch
// worker delivers it (callback_status pending → delivered / dead_letter); with
// no callback endpoint callback_status stays NULL (human-only enforcement).
type TrustDisposition struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// ReviewItemID references trust_review_item (intent, NOT NULL). FK via the
	// association below.
	ReviewItemID int64 `gorm:"not null;type:bigint;column:review_item_id" json:"review_item_id"`
	// Action uses the Action* constants; 0=none is a meaningful zero → NO
	// default tag. ActedBy is the operator's global user id.
	Action  int16 `gorm:"not null;column:action" json:"action"`
	ActedBy int64 `gorm:"not null;column:acted_by" json:"acted_by"`
	// ReasonCode is the machine reason; Statement the Art.17 reason statement
	// (nullable in P0, template generation is P3 — 章程 ruling 11).
	ReasonCode string  `gorm:"not null;column:reason_code" json:"reason_code"`
	Statement  *string `gorm:"column:statement" json:"statement"`
	// CallbackStatus uses the CallbackStatus* constants; NULLABLE — NULL means
	// the subject_kind has no callback endpoint (human-only).
	CallbackStatus *int16 `gorm:"column:callback_status" json:"callback_status"`
	// CallbackAttempts is the delivery attempt counter; creation value 0 is
	// fixed → the DDL default stays (a bookkeeping counter, not caller intent).
	CallbackAttempts int32 `gorm:"not null;default:0;column:callback_attempts" json:"callback_attempts"`
	// NextAttemptAt is when the worker may next try (NULL when not pending);
	// DeliveredAt stamps a successful delivery.
	NextAttemptAt *time.Time `gorm:"column:next_attempt_at" json:"next_attempt_at"`
	DeliveredAt   *time.Time `gorm:"column:delivered_at" json:"delivered_at"`
	CreatedAt     time.Time  `gorm:"not null;column:created_at" json:"created_at"`

	// ReviewItem is the association for ReviewItemID; GORM creates the FK.
	ReviewItem *TrustReviewItem `gorm:"foreignKey:ReviewItemID" json:"review_item,omitempty"`
}

func (TrustDisposition) TableName() string { return "trust_disposition" }

// TrustAuditLog is the append-only hash-chain audit trail (doc 18 §4.2, 章程
// ruling 10). PII is separated: rows store only ids / refs / reason_code, never
// content text. hash = SHA256(prev_hash || canonical-row); the first row's
// prev_hash is 32 zero bytes. Chain verification tooling is P3.
type TrustAuditLog struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// ActorID is the operator (NULL for system-driven rows). Action is the
	// audited event key (review_dismissed / review_actioned / callback_delivered
	// / callback_dead_letter / registry_* …).
	ActorID *int64 `gorm:"column:actor_id" json:"actor_id"`
	Action  string `gorm:"not null;column:action" json:"action"`
	// Subject refs (nullable — a registry-change row may have no subject).
	Site        *string `gorm:"column:site" json:"site"`
	SubjectKind *string `gorm:"column:subject_kind" json:"subject_kind"`
	SubjectID   *string `gorm:"column:subject_id" json:"subject_id"`
	ReasonCode  *string `gorm:"column:reason_code" json:"reason_code"`
	PolicyRef   *string `gorm:"column:policy_ref" json:"policy_ref"`
	// PrevHash / Hash are the chain links (bytea). NOT NULL — the first row's
	// prev_hash is 32 zero bytes, never absent.
	PrevHash  []byte    `gorm:"type:bytea;not null;column:prev_hash" json:"-"`
	Hash      []byte    `gorm:"type:bytea;not null;column:hash" json:"-"`
	CreatedAt time.Time `gorm:"not null;column:created_at" json:"created_at"`
}

func (TrustAuditLog) TableName() string { return "trust_audit_log" }
