package model

import "time"

type TrustDisposition struct {
	ID               int64      `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ReviewItemID     int64      `gorm:"not null;type:bigint;column:review_item_id" json:"review_item_id"`
	Action           int16      `gorm:"not null;column:action" json:"action"`
	ActedBy          int64      `gorm:"not null;column:acted_by" json:"acted_by"`
	ReasonCode       string     `gorm:"not null;column:reason_code" json:"reason_code"`
	Statement        *string    `gorm:"column:statement" json:"statement"`
	CallbackStatus   *int16     `gorm:"column:callback_status" json:"callback_status"`
	CallbackAttempts int32      `gorm:"not null;default:0;column:callback_attempts" json:"callback_attempts"`
	NextAttemptAt    *time.Time `gorm:"column:next_attempt_at" json:"next_attempt_at"`
	DeliveredAt      *time.Time `gorm:"column:delivered_at" json:"delivered_at"`
	CreatedAt        time.Time  `gorm:"not null;column:created_at" json:"created_at"`

	ReviewItem *TrustReviewItem `gorm:"foreignKey:ReviewItemID" json:"review_item,omitempty"`
}

func (TrustDisposition) TableName() string { return "trust_disposition" }

type TrustAuditLog struct {
	ID          int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ActorID     *int64    `gorm:"column:actor_id" json:"actor_id"`
	Action      string    `gorm:"not null;column:action" json:"action"`
	Site        *string   `gorm:"column:site" json:"site"`
	SubjectKind *string   `gorm:"column:subject_kind" json:"subject_kind"`
	SubjectID   *string   `gorm:"column:subject_id" json:"subject_id"`
	ReasonCode  *string   `gorm:"column:reason_code" json:"reason_code"`
	PolicyRef   *string   `gorm:"column:policy_ref" json:"policy_ref"`
	PrevHash    []byte    `gorm:"type:bytea;not null;column:prev_hash" json:"-"`
	Hash        []byte    `gorm:"type:bytea;not null;column:hash" json:"-"`
	CreatedAt   time.Time `gorm:"not null;column:created_at" json:"created_at"`
}

func (TrustAuditLog) TableName() string { return "trust_audit_log" }
