package model

import "time"

type TrustSubjectKind struct {
	ID              int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site            string    `gorm:"not null;column:site;uniqueIndex:uq_trust_subject_kind_site_key,priority:1" json:"site"`
	Key             string    `gorm:"not null;column:key;uniqueIndex:uq_trust_subject_kind_site_key,priority:2" json:"key"`
	CallbackURL     *string   `gorm:"column:callback_url" json:"callback_url"`
	CallbackSecret  *string   `gorm:"column:callback_secret" json:"callback_secret,omitempty"`
	IsDeprecated    bool      `gorm:"not null;default:false;column:is_deprecated" json:"is_deprecated"`
	NotifyOnDismiss bool      `gorm:"not null;default:false;column:notify_on_dismiss" json:"notify_on_dismiss"`
	CreatedAt       time.Time `json:"created_at"`
}

func (TrustSubjectKind) TableName() string { return "trust_subject_kind" }

type TrustReportReason struct {
	ID           int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Key          string  `gorm:"not null;column:key" json:"key"`
	NameCN       string  `gorm:"not null;column:name_cn" json:"name_cn"`
	Site         *string `gorm:"column:site" json:"site"`
	Severity     int16   `gorm:"not null;column:severity" json:"severity"`
	IsDeprecated bool    `gorm:"not null;default:false;column:is_deprecated" json:"is_deprecated"`
}

func (TrustReportReason) TableName() string { return "trust_report_reason" }
