package model

import "time"

// TrustSubjectKind is the per-site registry of reportable object kinds (doc 18
// §4.1). A site "onboards" a subject kind = INSERT one row (R1 lookup
// philosophy). callback_url is the enforcement endpoint the dispatch worker
// posts to; NULL = human-only enforcement (e.g. the user kind → IdP). Registry
// rows are NEVER deleted — is_deprecated retires a kind (章程 ruling 13).
type TrustSubjectKind struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// Site + Key form the tenant-scoped identity (invariant 11). UNIQUE(site,
	// key) via the composite unique index (both fields priority-tagged so the
	// column order is pinned — the composite-index-priority trap).
	Site string `gorm:"not null;column:site;uniqueIndex:uq_trust_subject_kind_site_key,priority:1" json:"site"`
	Key  string `gorm:"not null;column:key;uniqueIndex:uq_trust_subject_kind_site_key,priority:2" json:"key"`
	// CallbackURL is the product enforcement endpoint (NULL = human-only).
	CallbackURL *string `gorm:"column:callback_url" json:"callback_url"`
	// CallbackSecret is the per-kind HMAC-SHA256 signing secret (NULL when no
	// callback). Never serialized to non-admin surfaces by the handler.
	CallbackSecret *string `gorm:"column:callback_secret" json:"callback_secret,omitempty"`
	// IsDeprecated retires the kind. Creation value is always false, so the DDL
	// default stays (a bookkeeping flag, not a caller intent value).
	IsDeprecated bool      `gorm:"not null;default:false;column:is_deprecated" json:"is_deprecated"`
	CreatedAt    time.Time `json:"created_at"`
}

func (TrustSubjectKind) TableName() string { return "trust_subject_kind" }

// TrustReportReason is the reason taxonomy: a global base (site NULL) plus
// per-site extensions (doc 18 §4.1). The NULL-vs-non-NULL uniqueness is a pair
// of partial unique indexes created by the migrate raw-SQL section (Postgres
// treats NULLs as distinct in a plain UNIQUE, so a plain UNIQUE(key, site)
// would let duplicate global rows slip through).
type TrustReportReason struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// Key is the stable machine key (abuse / spam / illegal …).
	Key string `gorm:"not null;column:key" json:"key"`
	// NameCN is the display label — explicit column tag to dodge the acronym
	// snake-case trap (NameCN would become name_c_n).
	NameCN string `gorm:"not null;column:name_cn" json:"name_cn"`
	// Site NULL = global; non-NULL = a per-site extension reason.
	Site *string `gorm:"column:site" json:"site"`
	// Severity feeds the review-item priority. Intent value written explicitly
	// (no default tag) — a meaningful smallint the operator chooses.
	Severity int16 `gorm:"not null;column:severity" json:"severity"`
	// IsDeprecated retires a reason (registry rows are never deleted).
	IsDeprecated bool `gorm:"not null;default:false;column:is_deprecated" json:"is_deprecated"`
}

func (TrustReportReason) TableName() string { return "trust_report_reason" }
