package model

import "time"

// TrustReport is one report on a multi-tenant subject (doc 18 §4.2). The
// subject is referenced ONLY by (site, subject_kind, subject_id) — this service
// never dereferences product storage (invariant 2); the reporting BFF carries
// the content snapshot. P0 requires a logged-in reporter (reporter_id NOT NULL);
// the anonymous Art.16 contact columns arrive in P1.
type TrustReport struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// Tenant identity (invariant 11): every access index leads with site.
	Site        string `gorm:"not null;column:site" json:"site"`
	SubjectKind string `gorm:"not null;column:subject_kind" json:"subject_kind"`
	SubjectID   string `gorm:"not null;column:subject_id" json:"subject_id"`
	// ReporterID is the global user id (P0: logged-in only, NOT NULL). The
	// (reporter_id, created_at) index backs the rate-limit window count.
	ReporterID int64 `gorm:"not null;column:reporter_id" json:"reporter_id"`
	// ReasonID references trust_report_reason (intent, NOT NULL). The FK is
	// created by the association below.
	ReasonID int64 `gorm:"not null;type:bigint;column:reason_id" json:"reason_id"`
	// Note is free text; SubjectSnapshot the submitter-carried content snapshot
	// at report time (content may be edited afterwards). Both nullable.
	Note            *string `gorm:"column:note" json:"note"`
	SubjectSnapshot *string `gorm:"column:subject_snapshot" json:"subject_snapshot"`
	// Weight is the reporter-reputation-weighted vote (§5.3). PG real; written
	// explicitly by the service → NO default tag (a bare float maps to numeric,
	// so the type is pinned).
	Weight float32 `gorm:"type:real;not null;column:weight" json:"weight"`
	// ReviewItemID is the inbox item this report aggregated/folded into (NULL
	// until it links).
	ReviewItemID *int64 `gorm:"column:review_item_id" json:"review_item_id"`
	// Status uses the ReportStatus* constants; 0=received is a meaningful zero
	// → NO default tag.
	Status    int16     `gorm:"not null;column:status" json:"status"`
	CreatedAt time.Time `gorm:"not null;column:created_at" json:"created_at"`

	// Reason is the association for ReasonID; GORM AutoMigrate creates the FK.
	Reason *TrustReportReason `gorm:"foreignKey:ReasonID" json:"reason,omitempty"`
}

func (TrustReport) TableName() string { return "trust_report" }

// TrustReviewItem is the unified cross-site review inbox row (doc 18 §4.2, the
// landing of [14] §8.1). At most ONE open item per subject (invariant 4, a
// partial unique on status IN (pending, claimed)); repeated reports aggregate
// into report_weight_sum rather than opening a second item.
type TrustReviewItem struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// Tenant identity (invariant 11).
	Site        string `gorm:"not null;column:site" json:"site"`
	SubjectKind string `gorm:"not null;column:subject_kind" json:"subject_kind"`
	SubjectID   string `gorm:"not null;column:subject_id" json:"subject_id"`
	// Source uses the ReviewSource* constants; 0=reports is a meaningful zero
	// → NO default tag.
	Source int16 `gorm:"not null;column:source" json:"source"`
	// Signal columns (nullable; filled by the driving source).
	Severity        *int16   `gorm:"column:severity" json:"severity"`
	ClassifierScore *float32 `gorm:"type:real;column:classifier_score" json:"classifier_score"`
	ReportWeightSum *float32 `gorm:"type:real;column:report_weight_sum" json:"report_weight_sum"`
	// Priority ≈ reach × severity ÷ cost, recomputable. Intent value written
	// explicitly (章程 ruling 4 lists priority) → NO default tag.
	Priority float32 `gorm:"type:real;not null;column:priority" json:"priority"`
	// Status uses the ReviewStatus* constants; 0=pending is a meaningful zero
	// → NO default tag.
	Status    int16      `gorm:"not null;column:status" json:"status"`
	ClaimedBy *int64     `gorm:"column:claimed_by" json:"claimed_by"`
	ClaimedAt *time.Time `gorm:"column:claimed_at" json:"claimed_at"`
	DecidedBy *int64     `gorm:"column:decided_by" json:"decided_by"`
	DecidedAt *time.Time `gorm:"column:decided_at" json:"decided_at"`
	CreatedAt time.Time  `gorm:"not null;column:created_at" json:"created_at"`
}

func (TrustReviewItem) TableName() string { return "trust_review_item" }
