package model

import (
	"time"

	"gorm.io/datatypes"
)

// TrustScanResult is one AI content-scan event (doc 18 §4 sketch + §6 Tier2-via-
// gateway revision; step 03). A product publishes UGC, then pushes a scan event
// to POST /api/v1/trust/scan; the row lands status=pending and the shadow-scoring
// worker later scores it via the AI gateway's moderate-text route.
//
// It is the ONE place trust stores the content text (invariant 2 is relaxed here
// by design — moderation needs the bytes to score; the de-identification track
// has already ruled kun_trust out of the dev snapshot for exactly this PII). The
// text is NEVER serialized to any API surface (json:"-").
//
// Column discipline (章程 ruling 4, mirrored from the sibling models):
//   - INTENT columns whose zero is meaningful (site / subject_kind / subject_id /
//     content_text / status / mode) carry NO gorm default — the service writes
//     them explicitly (the GORM zero-value default trap).
//   - flagged / score / categories / scored_at are NULLABLE and filled only on
//     the scored path — a degraded row leaves them NULL (deliberate semantics).
//   - channel is NOT NULL DEFAULT ” — a bookkeeping label, ” until a scored
//     row records the upstream channel.
type TrustScanResult struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// Tenant identity (invariant 11): every access index leads with site. Site is
	// derived from the S2S client binding at intake, never the wire body.
	Site        string `gorm:"not null;column:site" json:"site"`
	SubjectKind string `gorm:"not null;column:subject_kind" json:"subject_kind"`
	SubjectID   string `gorm:"not null;column:subject_id" json:"subject_id"`
	// AuthorID is the optional content author's global id (attribution / repeat-
	// offender signal); NULL for anonymous / system content.
	AuthorID *int64 `gorm:"column:author_id" json:"author_id"`
	// SubjectReach is the audience the content had reached at scan time, carried
	// through to the review item it opens so the inbox can rank a widely-seen
	// violation above an unseen one. NULL = not reported by the product.
	//
	// On a publish-time scan this is legitimately 0 or NULL (nothing has been
	// seen yet); reach becomes meaningful on the RE-scan that every edit triggers,
	// and on the community-forward path, which fires long after publication.
	SubjectReach *int64 `gorm:"column:subject_reach" json:"subject_reach"`
	// ContentText is the text to scan — the only UGC body trust persists. Never
	// serialized (json:"-"). Capped at intake (maxScanTextRunes) with truncation
	// recorded; a caller re-scan on edit is a NEW row (scan events are naturally
	// repeatable, the worker scores idempotently).
	ContentText string `gorm:"not null;column:content_text" json:"-"`
	// Status uses the ScanStatus* constants; 0=pending is a meaningful zero → NO
	// default tag.
	Status int16 `gorm:"not null;column:status" json:"status"`
	// Flagged / Score / Categories are the scored-path verdict fields (NULL until
	// scored; a degraded row leaves them NULL).
	Flagged *bool `gorm:"column:flagged" json:"flagged"`
	// GatewayFlagged preserves the AI gateway's OWN boolean verdict, unchanged by
	// any site policy. Today it is identical to Flagged; it is stored separately
	// starting now because step 07 M0-B lets a site re-derive Flagged from Score
	// against its own threshold, and the day that lands, Flagged stops meaning
	// what it meant in every row written before it.
	//
	// Recording it one deploy EARLY is the whole point: a calibration corpus is
	// only useful if rows from different eras answer the same question, and there
	// is no way to reconstruct the gateway's verdict after the fact from a score
	// and a threshold that has since changed. NULL on rows written before this
	// column existed (and on degraded rows, which have no verdict at all).
	GatewayFlagged *bool `gorm:"column:gateway_flagged" json:"gateway_flagged"`
	Score          *float32       `gorm:"type:real;column:score" json:"score"`
	Categories     datatypes.JSON `gorm:"type:jsonb;column:categories" json:"categories,omitempty"`
	// Channel is the upstream channel/model that scored ('' until scored). A
	// bookkeeping label → DDL DEFAULT '' stays.
	Channel string `gorm:"not null;default:'';column:channel" json:"channel"`
	// Mode uses the ScanMode* constants; 0=shadow is a meaningful zero → NO
	// default tag. Hardcoded shadow this step.
	Mode int16 `gorm:"not null;column:mode" json:"mode"`
	// CreatedAt stamps intake (bookkeeping default now()); ScoredAt stamps the
	// scored path only (NULL on pending / degraded).
	CreatedAt time.Time  `gorm:"not null;default:now();column:created_at" json:"created_at"`
	ScoredAt  *time.Time `gorm:"column:scored_at" json:"scored_at"`
	// Tier0Matched is the deterministic word-list match result the scan worker
	// records BEFORE the gateway call (step 05): NULL = not evaluated (legacy
	// rows, or a matcher error); []=evaluated, no match; ["…","…"]=the matched
	// normalized terms. It NEVER changes status semantics (scored/degraded is
	// still gateway-driven) — it is the calibration-sample landing spot (doc 18
	// P1). Nullable jsonb, explicit column tag.
	Tier0Matched datatypes.JSON `gorm:"type:jsonb;column:tier0_matched" json:"tier0_matched,omitempty"`
	// DegradedReason records WHICH drain a degraded row took (the ScanDegraded*
	// constants). Three unrelated faults used to collapse into status=degraded
	// with nothing to tell them apart: an unconfigured gateway (a deploy fault),
	// a failed call (an upstream fault), and the gateway's own fail-open (an
	// upstream fault it already diagnosed for us). Between 2026-07-22 and
	// 2026-08-07 the third kind drained 262 rows while emitting no log line at
	// all, so a real 50% verdict loss was invisible from this table.
	//
	// NULL means "not recorded" — either a scored row, or one drained before this
	// column existed. Those 262 rows keep NULL: inventing a reason for them would
	// be a guess written down as evidence.
	DegradedReason *int16 `gorm:"column:degraded_reason" json:"degraded_reason"`
	// ScanAttempts counts terminal scoring attempts on this row. A degraded row
	// used to be terminal forever, so every drained row was a permanent hole in
	// the record even after the upstream recovered minutes later. The worker now
	// re-claims degraded rows until this reaches maxScanAttempts, which bounds
	// the retry without needing a scheduler: the worker's own tick is the backoff.
	//
	// 0 is the natural initial value AND the DDL default, so the zero-value
	// default trap does not apply — unlike an intent column, nothing is lost by
	// letting the database supply it.
	ScanAttempts int16 `gorm:"not null;default:0;column:scan_attempts" json:"scan_attempts"`
}

func (TrustScanResult) TableName() string { return "trust_scan_result" }
