package model

import "time"

// TrustTerm is one row of the Tier0 deterministic word list (doc 18 §4.1 /
// §6). It is a per-site registry of normalized substrings that the sync
// /trust/check face and the async scan worker match content text against —
// entirely channel-independent (no AI gateway). Registry rows are NEVER
// deleted; is_deprecated retires a term (章程 ruling 13, mirroring
// TrustSubjectKind / TrustReportReason).
//
// Column discipline (章程 ruling 4):
//   - identity PK three-part tag recipe (the catalog/community recipe).
//   - kind is an INTENT column (0=suspect / 1=banned) whose zero is meaningful →
//     NO gorm default; the service writes it explicitly (the zero-value default
//     trap).
//   - is_deprecated is a registry-flag (creation value always false) → its DDL
//     default stays.
//   - term_norm is explicit-column-tagged; it stores the ALREADY-normalized
//     term (admin submits the raw word, the service runs norm.Normalize before
//     insert), so the matcher never normalizes stored terms on the hot path.
//
// De-dup is a partial unique index on (COALESCE(site,''), term_norm) WHERE
// is_deprecated = false — one active term per (site-or-global, norm) — created
// by the migrate raw-SQL section (a deprecated row may share the norm, so a
// retired term can be re-created).
type TrustTerm struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// Site NULL = a GLOBAL term (applies to every site); non-NULL = a per-site
	// term (applies only to that catalog_site).
	Site *string `gorm:"column:site" json:"site"`
	// TermNorm is the normalized substring to match (never the raw admin input).
	TermNorm string `gorm:"not null;column:term_norm" json:"term_norm"`
	// Kind is the enforcement intent: 0=suspect (hold — enqueue, do not block)
	// / 1=banned (deny — the sync check rejects). A meaningful zero → NO default.
	Kind int16 `gorm:"not null;column:kind" json:"kind"`
	// Note is an optional operator memo (why the term is listed).
	Note *string `gorm:"column:note" json:"note,omitempty"`
	// IsDeprecated retires the term (registry rows are never deleted). Creation
	// value is always false → the DDL default stays.
	IsDeprecated bool      `gorm:"not null;default:false;column:is_deprecated" json:"is_deprecated"`
	CreatedAt    time.Time `gorm:"not null;default:now();column:created_at" json:"created_at"`
}

func (TrustTerm) TableName() string { return "trust_term" }
