package service

import (
	"fmt"
	"strings"

	"api/internal/platform/catalog/model"

	"gorm.io/gorm"
)

// mergeStmt is one statement of a rehang batch. collectWorks marks the ones
// whose RETURNING clause hands back the ids of the works whose read face the
// statement just changed — ExecuteMerge touches those works before it commits,
// otherwise the changes feed never learns that the merge rewrote them.
type mergeStmt struct {
	sql          string
	args         []any
	collectWorks bool
}

// rehangEntity repoints every child/reference of source onto target,
// deleting rows that would violate the target's unique constraints (the
// child already exists on the target — a true duplicate). The hook set per
// type is the pinned doc 10 §6.2-2 list. It returns the work ids whose
// rendered content changed, per the wave-118 touch matrix: a work renders
// credits[], its roster and its brand labels, so credit / character / label
// merges rewrite works that are not themselves part of the merge; person and
// org ids never reach the work face (they hang one level below the name and
// the label), so those merges touch nothing.
//
// THE LIST IS THE CONTRACT (wave 170b): a table that references a merge-able
// entity and is missing here strands its rows on the retired id, where nothing
// reads them and no constraint complains — catalog_work_cover was born after
// the original list and left 12 rows hanging on a merged-away work in
// production. Every table that carries a work / character / label / person /
// credit_name / org reference is therefore accounted for below, either by a
// statement or by a named exclusion:
//
//   - catalog_revision, catalog_claim_event — append-only history. The record
//     of what happened to the source id must keep pointing at the source id;
//     rewriting it would rewrite the past (and the merge writes its own
//     revision rows on both sides).
//   - catalog_external_ref, catalog_entity_usage, catalog_redirect — merged by
//     their own dedicated steps in ExecuteMerge (4/5/6), which carry semantics
//     a blind repoint would destroy (exact-conflict demotion, first/last-seen
//     folding, chain flattening).
//   - catalog_match_candidate, catalog_match_rejection, catalog_merge_proposal
//     — the reconciliation queue and its audit trail. The pair's own candidate
//     is settled by step 8; the rest are proposals ABOUT the source id and are
//     regenerated by the matcher, so they stay addressed to what was actually
//     compared.
//   - catalog_work.product_work_id — a PRODUCT-side id (the claim), not a
//     catalog entity id; retireSource frees the source's claim slot.
func rehangEntity(tx *gorm.DB, entityType int16, src, dst int64) ([]int64, error) {
	switch entityType {
	case model.EntityTypePerson:
		// The whole point of the name layer: person merge = repoint names.
		// person_id lives on the name face only — no work changes.
		stmts := []mergeStmt{
			{`UPDATE catalog_credit_name SET person_id = ? WHERE person_id = ?`, []any{dst, src}, false},
			// Intros, deduped against uq_catalog_person_intro
			// (person_id, lang, source_id) — the character-intro idiom.
			{`UPDATE catalog_person_intro i SET person_id = ? WHERE i.person_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_person_intro x
			                     WHERE x.person_id = ? AND x.lang = i.lang AND x.source_id = i.source_id)`,
				[]any{dst, src, dst}, false},
			{`DELETE FROM catalog_person_intro WHERE person_id = ?`, []any{src}, false},
		}
		return execAll(tx, append(stmts, entityRelationStmts(entityType, src, dst)...))

	case model.EntityTypeCreditName:
		stmts := []mergeStmt{
			// credits, deduped against uq_catalog_credit. Both statements
			// change what the host work lists under credits[] — the repoint
			// swaps the credited name, the dedup delete drops a row.
			{`UPDATE catalog_credit c SET credit_name_id = ? WHERE c.credit_name_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_credit d
			                     WHERE d.work_id = c.work_id AND d.credit_name_id = ?
			                       AND d.role_id = c.role_id
			                       AND COALESCE(d.character_id, 0) = COALESCE(c.character_id, 0))
			  RETURNING c.work_id`, []any{dst, src, dst}, true},
			{`DELETE FROM catalog_credit WHERE credit_name_id = ? RETURNING work_id`, []any{src}, true},
			// aliases, deduped against UNIQUE(owner, name, lang) — name face.
			{`UPDATE catalog_name_alias a SET credit_name_id = ? WHERE a.credit_name_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_name_alias b
			                     WHERE b.credit_name_id = ? AND b.name = a.name AND b.lang = a.lang)`, []any{dst, src, dst}, false},
			{`DELETE FROM catalog_name_alias WHERE credit_name_id = ?`, []any{src}, false},
			// primary-name references
			{`UPDATE catalog_person SET primary_credit_name_id = ? WHERE primary_credit_name_id = ?`, []any{dst, src}, false},
		}
		return execAll(tx, append(stmts, entityRelationStmts(entityType, src, dst)...))

	case model.EntityTypeLabel:
		stmts := []mergeStmt{
			// label_id is not part of the credit unique key — plain repoint.
			{`UPDATE catalog_credit SET label_id = ? WHERE label_id = ? RETURNING work_id`, []any{dst, src}, true},
			{`UPDATE catalog_label_alias a SET label_id = ? WHERE a.label_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_label_alias b
			                     WHERE b.label_id = ? AND b.name = a.name AND b.lang = a.lang)`, []any{dst, src, dst}, false},
			{`DELETE FROM catalog_label_alias WHERE label_id = ?`, []any{src}, false},
			// Intros, deduped against uq_catalog_label_intro
			// (label_id, lang, source_id). A work renders label ids, not the
			// label's body — no work id to collect.
			{`UPDATE catalog_label_intro i SET label_id = ? WHERE i.label_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_label_intro x
			                     WHERE x.label_id = ? AND x.lang = i.lang AND x.source_id = i.source_id)`,
				[]any{dst, src, dst}, false},
			{`DELETE FROM catalog_label_intro WHERE label_id = ?`, []any{src}, false},
			// brand edges, deduped against the (work, label, kind) PK
			{`UPDATE catalog_work_label e SET label_id = ? WHERE e.label_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_work_label x
			                     WHERE x.work_id = e.work_id AND x.label_id = ? AND x.kind = e.kind)
			  RETURNING e.work_id`, []any{dst, src, dst}, true},
			{`DELETE FROM catalog_work_label WHERE label_id = ? RETURNING work_id`, []any{src}, true},
		}
		stmts = append(stmts, labelRelationStmts(src, dst)...)
		return execAll(tx, append(stmts, entityRelationStmts(entityType, src, dst)...))

	case model.EntityTypeCharacter:
		stmts := []mergeStmt{
			// voice credits: character_id participates in uq_catalog_credit
			{`UPDATE catalog_credit c SET character_id = ? WHERE c.character_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_credit d
			                     WHERE d.work_id = c.work_id AND d.credit_name_id = c.credit_name_id
			                       AND d.role_id = c.role_id AND COALESCE(d.character_id, 0) = ?)
			  RETURNING c.work_id`, []any{dst, src, dst}, true},
			{`DELETE FROM catalog_credit WHERE character_id = ? RETURNING work_id`, []any{src}, true},
			{`UPDATE catalog_character_alias a SET character_id = ? WHERE a.character_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_character_alias b
			                     WHERE b.character_id = ? AND b.name = a.name AND b.lang = a.lang)`, []any{dst, src, dst}, false},
			{`DELETE FROM catalog_character_alias WHERE character_id = ?`, []any{src}, false},
			// roster edges (catalog_work_character, step 45 — added AFTER the
			// original hook list; step 49 regression fix). When both sides carry
			// an edge on the same work, the surviving edge folds in the loser's
			// stronger signal before the loser row is dropped: kind upgrades from
			// unknown (0) to the loser's typed value (doc 10 §6.2 — the more
			// specific value wins; two typed values keep the survivor's,
			// first-source-wins per step 45), and spoiler takes the higher of the
			// two so a source that flags a severe spoiler is never silently
			// downgraded. Then non-conflicting loser edges move, deduped against
			// uq_catalog_work_character (work_id, character_id), and the rest drop.
			//
			// The fold needs no RETURNING: it only fires on works that carry an
			// edge from BOTH sides, and every one of those loses the source's
			// edge to the dedup DELETE below, which collects them.
			{`UPDATE catalog_work_character d
			    SET kind = CASE WHEN d.kind = 0 THEN s.kind ELSE d.kind END,
			        spoiler = GREATEST(d.spoiler, s.spoiler),
			        updated_at = now()
			    FROM catalog_work_character s
			    WHERE d.character_id = ? AND s.character_id = ? AND s.work_id = d.work_id`, []any{dst, src}, false},
			{`UPDATE catalog_work_character e SET character_id = ?, updated_at = now() WHERE e.character_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_work_character x
			                     WHERE x.work_id = e.work_id AND x.character_id = ?)
			  RETURNING e.work_id`, []any{dst, src, dst}, true},
			{`DELETE FROM catalog_work_character WHERE character_id = ? RETURNING work_id`, []any{src}, true},
			// Descriptions (step 107) and vndb trait links (step 93) were added
			// to the character face AFTER this hook list was written, and were
			// never re-hung: a merge stranded them on the retired row, where
			// nothing reads them (770 such intro rows exist in the 2026-07-30
			// production snapshot, from the step-97/98 waves). Both are
			// character-face tables, so like instance_of above they collect no
			// work id — the work read face does not render them.
			//
			// Dedup targets are the tables' own unique keys:
			// uq_catalog_character_intro (character_id, lang, source_id) and
			// uq_catalog_character_trait_link (character_id, trait_id). On a
			// collision the survivor's row stands and the source's is dropped
			// (doc 10 §6.2 first-source-wins); no field fold is needed, since
			// both facets carry a single source's assertion per key.
			{`UPDATE catalog_character_intro i SET character_id = ? WHERE i.character_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_character_intro x
			                     WHERE x.character_id = ? AND x.lang = i.lang AND x.source_id = i.source_id)`,
				[]any{dst, src, dst}, false},
			{`DELETE FROM catalog_character_intro WHERE character_id = ?`, []any{src}, false},
			{`UPDATE catalog_character_trait_link t SET character_id = ? WHERE t.character_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_character_trait_link x
			                     WHERE x.character_id = ? AND x.trait_id = t.trait_id)`,
				[]any{dst, src, dst}, false},
			{`DELETE FROM catalog_character_trait_link WHERE character_id = ?`, []any{src}, false},
			// variant pointers follow the base character — character face only.
			{`UPDATE catalog_character SET instance_of = ? WHERE instance_of = ?`, []any{dst, src}, false},
		}
		return execAll(tx, append(stmts, entityRelationStmts(entityType, src, dst)...))

	case model.EntityTypeWork:
		// Everything below repoints a facet from source to target, so the
		// TARGET's own face changes (ExecuteMerge touches it unconditionally).
		// Relations are the exception that needs RETURNING: repointing an edge
		// rewrites the relations[] of the work at the OTHER end, which takes
		// no part in this merge.
		stmts := []mergeStmt{
			// edges between the pair would become self-edges (a<>b CHECK) —
			// drop them. Both endpoints are the merge pair itself, so there is
			// no third work to collect here.
			{`DELETE FROM catalog_work_relation
			   WHERE (a_work_id = ? AND b_work_id = ?) OR (a_work_id = ? AND b_work_id = ?)`, []any{src, dst, dst, src}, false},
			// a-side, deduped against the (a, b, type) PK
			{`UPDATE catalog_work_relation r SET a_work_id = ? WHERE r.a_work_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_work_relation x
			                     WHERE x.a_work_id = ? AND x.b_work_id = r.b_work_id
			                       AND x.relation_type_id = r.relation_type_id)
			  RETURNING r.b_work_id`, []any{dst, src, dst}, true},
			{`DELETE FROM catalog_work_relation WHERE a_work_id = ? RETURNING b_work_id`, []any{src}, true},
			// b-side
			{`UPDATE catalog_work_relation r SET b_work_id = ? WHERE r.b_work_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_work_relation x
			                     WHERE x.b_work_id = ? AND x.a_work_id = r.a_work_id
			                       AND x.relation_type_id = r.relation_type_id)
			  RETURNING r.a_work_id`, []any{dst, src, dst}, true},
			{`DELETE FROM catalog_work_relation WHERE b_work_id = ? RETURNING a_work_id`, []any{src}, true},
			// titles, deduped against UNIQUE(work, lang, title, kind)
			{`UPDATE catalog_work_title t SET work_id = ? WHERE t.work_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_work_title u
			                     WHERE u.work_id = ? AND u.lang = t.lang AND u.title = t.title AND u.kind = t.kind)`, []any{dst, src, dst}, false},
			{`DELETE FROM catalog_work_title WHERE work_id = ?`, []any{src}, false},
			// releases carry no unique on work_id — plain repoint
			{`UPDATE catalog_release SET work_id = ? WHERE work_id = ?`, []any{dst, src}, false},
			// credits, deduped against uq_catalog_credit
			{`UPDATE catalog_credit c SET work_id = ? WHERE c.work_id = ?
			    AND NOT EXISTS (SELECT 1 FROM catalog_credit d
			                     WHERE d.work_id = ? AND d.credit_name_id = c.credit_name_id
			                       AND d.role_id = c.role_id
			                       AND COALESCE(d.character_id, 0) = COALESCE(c.character_id, 0))`, []any{dst, src, dst}, false},
			{`DELETE FROM catalog_credit WHERE work_id = ?`, []any{src}, false},
		}
		return execAll(tx, append(stmts, workFacetStmts(src, dst)...))
	}
	return nil, fmt.Errorf("catalog merge: unsupported entity type %d", entityType)
}

// workFacetStmts is the wave-170b closure of the work batch: every table that
// hangs off a work by work_id alone and joined the schema AFTER the original
// doc 10 §6.2-2 list was written. A work merge used to leave all of them on the
// retired id — catalog_work_cover is the one production caught (12 rows moved
// by hand), and it was never alone.
//
// None of these statements collects a work id. They are keyed by work_id only,
// so the sole faces they change belong to the merge pair itself: ExecuteMerge
// touches the target unconditionally, and the source is deliberately never
// touched (its merge signal is the redirects face).
//
// Dedup keys are each table's own UNIQUE index, read off the model tags. Where
// a key collides the survivor's row stands and the source's is dropped
// (doc 10 §6.2 first-source-wins) — the sole exception is the roster edge,
// which folds the loser's stronger signal in first, exactly as the character
// batch does.
func workFacetStmts(src, dst int64) []mergeStmt {
	stmts := []mergeStmt{
		// Roster edges: fold kind/spoiler into the surviving edge before the
		// loser drops (the character batch's rule, seen from the work side).
		{`UPDATE catalog_work_character d
		    SET kind = CASE WHEN d.kind = 0 THEN s.kind ELSE d.kind END,
		        spoiler = GREATEST(d.spoiler, s.spoiler),
		        updated_at = now()
		    FROM catalog_work_character s
		    WHERE d.work_id = ? AND s.work_id = ? AND s.character_id = d.character_id`, []any{dst, src}, false},
	}
	// (table, the unique-key columns BESIDES work_id)
	for _, f := range []struct {
		table string
		key   []string
	}{
		{"catalog_work_intro", []string{"lang", "source_id"}},
		{"catalog_work_cover", []string{"image_hash"}},
		{"catalog_work_screenshot", []string{"image_hash"}},
		{"catalog_work_rating", []string{"source_id"}},
		{"catalog_work_tag", []string{"name", "source_id"}},
		{"catalog_work_popularity", []string{"source_id", "metric"}},
		{"catalog_work_playtime", []string{"source_id"}},
		{"catalog_work_platform", []string{"platform", "source_id"}},
		{"catalog_work_engine", []string{"engine_id"}},
		{"catalog_series_member", []string{"series_id"}},
		{"catalog_work_label", []string{"label_id", "kind"}},
		{"catalog_work_character", []string{"character_id"}},
	} {
		stmts = append(stmts, workFacetRehang(f.table, f.key, src, dst)...)
	}
	return stmts
}

// workFacetRehang builds the two-statement move for one work facet table:
// rows whose unique key is still free on the target move, and the remainder —
// a row the target already carries under the same key — drops. keyCols are the
// unique-key columns other than work_id.
//
// The table and column names are compile-time constants from workFacetStmts,
// never input, so interpolating them is the readable way to keep twelve
// identical statements identical.
func workFacetRehang(table string, keyCols []string, src, dst int64) []mergeStmt {
	match := make([]string, 0, len(keyCols))
	for _, c := range keyCols {
		match = append(match, fmt.Sprintf("x.%s = f.%s", c, c))
	}
	move := fmt.Sprintf(
		`UPDATE %s f SET work_id = ? WHERE f.work_id = ?
		    AND NOT EXISTS (SELECT 1 FROM %s x WHERE x.work_id = ? AND %s)`,
		table, table, strings.Join(match, " AND "))
	return []mergeStmt{
		{move, []any{dst, src, dst}, false},
		{fmt.Sprintf(`DELETE FROM %s WHERE work_id = ?`, table), []any{src}, false},
	}
}

// labelRelationStmts moves the DERIVED corporate-graph edges (wave 186), the
// table catalog_label_relation, which import-label-relations rebuilds wholesale
// per source. Rehanging a derived table looks redundant — the next import puts
// the edge on the survivor anyway, because the merge moved the source anchor
// with it — but "the next import" can be weeks away, and until it runs the read
// face carries edges pointing at a retired label. So this is not inventing a
// derived fact: it is applying early exactly what the rebuild will conclude.
//
// Both endpoints move because storage is mirrored (an imprint edge is stored
// alongside its imprint_of twin), and repointing only one side would leave the
// pair contradicting itself. The edges BETWEEN src and dst drop first: they
// would become self-edges, which the graph reader would render as a company
// owning itself. Dedup is against the full composite PK, source_id included —
// two sources may legitimately assert the same edge.
func labelRelationStmts(src, dst int64) []mergeStmt {
	return []mergeStmt{
		{`DELETE FROM catalog_label_relation
		   WHERE (label_id = ? AND other_label_id = ?) OR (label_id = ? AND other_label_id = ?)`,
			[]any{src, dst, dst, src}, false},
		{`UPDATE catalog_label_relation r SET label_id = ? WHERE r.label_id = ?
		    AND NOT EXISTS (SELECT 1 FROM catalog_label_relation x
		                     WHERE x.label_id = ? AND x.other_label_id = r.other_label_id
		                       AND x.relation = r.relation AND x.source_id = r.source_id)`,
			[]any{dst, src, dst}, false},
		{`DELETE FROM catalog_label_relation WHERE label_id = ?`, []any{src}, false},
		{`UPDATE catalog_label_relation r SET other_label_id = ? WHERE r.other_label_id = ?
		    AND NOT EXISTS (SELECT 1 FROM catalog_label_relation x
		                     WHERE x.other_label_id = ? AND x.label_id = r.label_id
		                       AND x.relation = r.relation AND x.source_id = r.source_id)`,
			[]any{dst, src, dst}, false},
		{`DELETE FROM catalog_label_relation WHERE other_label_id = ?`, []any{src}, false},
	}
}

// entityRelationStmts moves the polymorphic entity↔entity edges (label
// imprint / renamed-from / subsidiary, person membership, …) of a non-work
// merge. The table addresses its endpoints by (entity_type, id), so one
// statement set serves every entity type; the shape mirrors the
// catalog_work_relation block — the edges BETWEEN the pair would become
// self-edges the chk_catalog_entity_relation_distinct CHECK forbids, so they
// drop first, then each side moves deduped against the
// (entity_type, a_id, b_id, relation_type_id) primary key.
//
// No work id is ever collected: the other endpoint of an entity edge is an
// entity, never a work.
func entityRelationStmts(entityType int16, src, dst int64) []mergeStmt {
	return []mergeStmt{
		{`DELETE FROM catalog_entity_relation
		   WHERE entity_type = ? AND ((a_id = ? AND b_id = ?) OR (a_id = ? AND b_id = ?))`,
			[]any{entityType, src, dst, dst, src}, false},
		{`UPDATE catalog_entity_relation e SET a_id = ? WHERE e.entity_type = ? AND e.a_id = ?
		    AND NOT EXISTS (SELECT 1 FROM catalog_entity_relation x
		                     WHERE x.entity_type = e.entity_type AND x.a_id = ? AND x.b_id = e.b_id
		                       AND x.relation_type_id = e.relation_type_id)`,
			[]any{dst, entityType, src, dst}, false},
		{`DELETE FROM catalog_entity_relation WHERE entity_type = ? AND a_id = ?`, []any{entityType, src}, false},
		{`UPDATE catalog_entity_relation e SET b_id = ? WHERE e.entity_type = ? AND e.b_id = ?
		    AND NOT EXISTS (SELECT 1 FROM catalog_entity_relation x
		                     WHERE x.entity_type = e.entity_type AND x.b_id = ? AND x.a_id = e.a_id
		                       AND x.relation_type_id = e.relation_type_id)`,
			[]any{dst, entityType, src, dst}, false},
		{`DELETE FROM catalog_entity_relation WHERE entity_type = ? AND b_id = ?`, []any{entityType, src}, false},
	}
}

// execAll runs a rehang batch in order and gathers the work ids returned by
// the statements flagged collectWorks. Those statements are queries (they carry
// a RETURNING clause), so they go through Raw().Scan rather than Exec.
func execAll(tx *gorm.DB, stmts []mergeStmt) ([]int64, error) {
	var touched []int64
	for _, s := range stmts {
		if !s.collectWorks {
			if err := tx.Exec(s.sql, s.args...).Error; err != nil {
				return nil, err
			}
			continue
		}
		var ids []int64
		if err := tx.Raw(s.sql, s.args...).Scan(&ids).Error; err != nil {
			return nil, err
		}
		touched = append(touched, ids...)
	}
	return touched, nil
}
