package srcvndb

// Traits + tags staging models (step 72): the two curated VNDB vocabularies
// (traits describe characters, tags describe VNs — both carry real English
// descriptions, the feedstock for the tag-canonicalization design), their
// hierarchy edges, and the assignment edges (chars_traits is aggregated;
// tags_vn is the raw per-user vote table).

// Trait mirrors one db/traits row — one entry of the character-trait
// vocabulary. `GID` is the trait's group (root trait, "" for the ~11 roots).
type Trait struct {
	ID           string `gorm:"primaryKey" json:"id"`                 // "i1"
	GID          string `gorm:"column:gid;not null" json:"gid"`       // group trait id or ""
	GOrder       int16  `gorm:"column:gorder;not null" json:"gorder"` // group sort order
	DefaultSpoil int16  `gorm:"column:defaultspoil;not null" json:"defaultspoil"`
	Sexual       bool   `gorm:"not null" json:"sexual"`
	Searchable   bool   `gorm:"not null" json:"searchable"`
	Applicable   bool   `gorm:"not null" json:"applicable"`
	Name         string `gorm:"not null" json:"name"`
	Alias        string `gorm:"not null" json:"alias"` // newline-separated alternative names
	Description  string `gorm:"not null" json:"description"`
}

func (Trait) TableName() string { return "src_vndb.traits" }

// TraitParent mirrors one db/traits_parents row — the trait DAG (a trait can
// have several parents; `Main` marks the primary one).
type TraitParent struct {
	ID     string `gorm:"primaryKey;column:id" json:"id"`         // child "i2"
	Parent string `gorm:"primaryKey;column:parent" json:"parent"` // parent "i1"
	Main   bool   `gorm:"not null" json:"main"`
}

func (TraitParent) TableName() string { return "src_vndb.traits_parents" }

// CharTrait mirrors one db/chars_traits row — a trait assigned to a character
// (already aggregated by VNDB, unlike tags_vn). `Lie` marks the in-story-lie
// flavor of spoiler.
type CharTrait struct {
	ID    string `gorm:"primaryKey;column:id" json:"id"`   // char "c1"
	TID   string `gorm:"primaryKey;column:tid" json:"tid"` // trait "i6"
	Spoil int16  `gorm:"not null" json:"spoil"`            // 0-2
	Lie   bool   `gorm:"not null" json:"lie"`
}

func (CharTrait) TableName() string { return "src_vndb.chars_traits" }

// Tag mirrors one db/tags row — one entry of the VN-tag vocabulary.
type Tag struct {
	ID           string `gorm:"primaryKey" json:"id"` // "g1"
	Cat          string `gorm:"not null" json:"cat"`  // cont/ero/tech
	DefaultSpoil int16  `gorm:"column:defaultspoil;not null" json:"defaultspoil"`
	Searchable   bool   `gorm:"not null" json:"searchable"`
	Applicable   bool   `gorm:"not null" json:"applicable"`
	Name         string `gorm:"not null" json:"name"`
	Alias        string `gorm:"not null" json:"alias"` // newline-separated alternative names
	Description  string `gorm:"not null" json:"description"`
}

func (Tag) TableName() string { return "src_vndb.tags" }

// TagParent mirrors one db/tags_parents row — the tag DAG (same shape as
// TraitParent).
type TagParent struct {
	ID     string `gorm:"primaryKey;column:id" json:"id"`         // child "g2"
	Parent string `gorm:"primaryKey;column:parent" json:"parent"` // parent "g1"
	Main   bool   `gorm:"not null" json:"main"`
}

func (TagParent) TableName() string { return "src_vndb.tags_parents" }

// TagVN mirrors one db/tags_vn row — ONE USER'S tag vote on a VN (the raw,
// unaggregated table; Gold-side consumption aggregates per (tag, vid)).
// `Vote` is -3..3 (negative = downvote); `Spoiler` and `Lie` are pointers
// because NULL (no opinion stated) differs from an explicit 0/false. No
// natural key is clean (uid is NULL for anonymized votes), so a surrogate
// identity PK carries the table.
type TagVN struct {
	Seq     int64  `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"-"`
	Date    string `gorm:"not null" json:"date"`                 // vote date "2010-12-15"
	Tag     string `gorm:"column:tag;not null;index" json:"tag"` // "g2"
	VID     string `gorm:"column:vid;not null;index" json:"vid"` // "v5"
	UID     string `gorm:"column:uid;not null" json:"uid"`       // "u51" or "" (anonymized)
	Vote    int16  `gorm:"not null" json:"vote"`                 // -3..3
	Spoiler *int16 `gorm:"column:spoiler" json:"spoiler"`        // 0-2, NULL = no opinion
	Ignore  bool   `gorm:"column:ignore;not null" json:"ignore"`
	Lie     *bool  `gorm:"column:lie" json:"lie"` // NULL = no opinion
	Notes   string `gorm:"not null" json:"notes"`
}

func (TagVN) TableName() string { return "src_vndb.tags_vn" }
