package srcvndb

// Staff-family staging models (step 72, S1 feedstock): staff + staff_alias
// (the vocabulary — every credited name is an alias row; `main` on staff picks
// the primary one) and the two credit edge tables vn_staff (non-VA roles) and
// vn_seiyuu (VA edges, resolved to a character). Alias ids (aid) are plain
// integers in the dump — the ONE VNDB id space without a letter prefix.

// Staff mirrors one db/staff row — a staff member (person or group). Names are
// NOT here: they live in staff_alias; `Main` is the aid of the primary alias.
type Staff struct {
	ID          string `gorm:"primaryKey" json:"id"` // "s1"
	Gender      string `gorm:"not null" json:"gender"`
	Lang        string `gorm:"not null" json:"lang"`
	Main        int    `gorm:"not null" json:"main"`        // primary alias aid
	Description string `gorm:"not null" json:"description"` // BBCode-ish
	Prod        string `gorm:"not null" json:"prod"`        // linked producer id "p42" or ""
}

func (Staff) TableName() string { return "src_vndb.staff" }

// StaffAlias mirrors one db/staff_alias row — one credited name of a staff
// member. aid is globally unique (the dump's PK); `Name` is the native/script
// form, `Latin` the romanization ("" when the name is already latin).
type StaffAlias struct {
	// Explicit column tag: GORM would snake-case AID to a_i_d (the acronym
	// column-naming trap) — pinned to the dump's name.
	AID   int    `gorm:"primaryKey;autoIncrement:false;column:aid" json:"aid"`
	ID    string `gorm:"column:id;not null;index" json:"id"` // staff "s1"
	Name  string `gorm:"not null" json:"name"`
	Latin string `gorm:"not null" json:"latin"`
}

func (StaffAlias) TableName() string { return "src_vndb.staff_alias" }

// VNStaff mirrors one db/vn_staff row — a non-VA staff credit on a VN under a
// specific alias. `EID` narrows the credit to a vn_editions edition and is a
// pointer because edition 0 exists in the dump (NULL = the base edition). No
// natural key is clean (eid is often absent), so a surrogate identity PK
// carries the table.
type VNStaff struct {
	Seq  int64  `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"-"`
	ID   string `gorm:"column:id;not null;index" json:"id"`   // vn "v1"
	AID  int    `gorm:"column:aid;not null;index" json:"aid"` // credited alias
	Role string `gorm:"not null" json:"role"`                 // scenario/art/music/songs/director/chardesign/staff
	EID  *int   `gorm:"column:eid" json:"eid"`                // edition id, NULL = base edition
	Note string `gorm:"not null" json:"note"`
}

func (VNStaff) TableName() string { return "src_vndb.vn_staff" }

// VNSeiyuu mirrors one db/vn_seiyuu row — a voice-acting credit: alias aid
// voices character cid in vn id. (id, cid, aid) is the dump's natural key.
type VNSeiyuu struct {
	ID   string `gorm:"primaryKey;column:id" json:"id"`   // vn "v1"
	CID  string `gorm:"primaryKey;column:cid" json:"cid"` // char "c1784"
	AID  int    `gorm:"primaryKey;autoIncrement:false;column:aid" json:"aid"`
	Note string `gorm:"not null" json:"note"`
}

func (VNSeiyuu) TableName() string { return "src_vndb.vn_seiyuu" }
