package srcvndb

type Trait struct {
	ID           string `gorm:"primaryKey" json:"id"`
	GID          string `gorm:"column:gid;not null" json:"gid"`
	GOrder       int16  `gorm:"column:gorder;not null" json:"gorder"`
	DefaultSpoil int16  `gorm:"column:defaultspoil;not null" json:"defaultspoil"`
	Sexual       bool   `gorm:"not null" json:"sexual"`
	Searchable   bool   `gorm:"not null" json:"searchable"`
	Applicable   bool   `gorm:"not null" json:"applicable"`
	Name         string `gorm:"not null" json:"name"`
	Alias        string `gorm:"not null" json:"alias"`
	Description  string `gorm:"not null" json:"description"`
}

func (Trait) TableName() string { return "src_vndb.traits" }

type TraitParent struct {
	ID     string `gorm:"primaryKey;column:id" json:"id"`
	Parent string `gorm:"primaryKey;column:parent" json:"parent"`
	Main   bool   `gorm:"not null" json:"main"`
}

func (TraitParent) TableName() string { return "src_vndb.traits_parents" }

type CharTrait struct {
	ID    string `gorm:"primaryKey;column:id" json:"id"`
	TID   string `gorm:"primaryKey;column:tid" json:"tid"`
	Spoil int16  `gorm:"not null" json:"spoil"`
	Lie   bool   `gorm:"not null" json:"lie"`
}

func (CharTrait) TableName() string { return "src_vndb.chars_traits" }

type Tag struct {
	ID           string `gorm:"primaryKey" json:"id"`
	Cat          string `gorm:"not null" json:"cat"`
	DefaultSpoil int16  `gorm:"column:defaultspoil;not null" json:"defaultspoil"`
	Searchable   bool   `gorm:"not null" json:"searchable"`
	Applicable   bool   `gorm:"not null" json:"applicable"`
	Name         string `gorm:"not null" json:"name"`
	Alias        string `gorm:"not null" json:"alias"`
	Description  string `gorm:"not null" json:"description"`
}

func (Tag) TableName() string { return "src_vndb.tags" }

type TagParent struct {
	ID     string `gorm:"primaryKey;column:id" json:"id"`
	Parent string `gorm:"primaryKey;column:parent" json:"parent"`
	Main   bool   `gorm:"not null" json:"main"`
}

func (TagParent) TableName() string { return "src_vndb.tags_parents" }

type TagVN struct {
	Seq     int64  `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"-"`
	Date    string `gorm:"not null" json:"date"`
	Tag     string `gorm:"column:tag;not null;index" json:"tag"`
	VID     string `gorm:"column:vid;not null;index" json:"vid"`
	UID     string `gorm:"column:uid;not null" json:"uid"`
	Vote    int16  `gorm:"not null" json:"vote"`
	Spoiler *int16 `gorm:"column:spoiler" json:"spoiler"`
	Ignore  bool   `gorm:"column:ignore;not null" json:"ignore"`
	Lie     *bool  `gorm:"column:lie" json:"lie"`
	Notes   string `gorm:"not null" json:"notes"`
}

func (TagVN) TableName() string { return "src_vndb.tags_vn" }
