package srcvndb

type Staff struct {
	ID          string `gorm:"primaryKey" json:"id"`
	Gender      string `gorm:"not null" json:"gender"`
	Lang        string `gorm:"not null" json:"lang"`
	Main        int    `gorm:"not null" json:"main"`
	Description string `gorm:"not null" json:"description"`
	Prod        string `gorm:"not null" json:"prod"`
}

func (Staff) TableName() string { return "src_vndb.staff" }

type StaffAlias struct {
	// Explicit column tag: GORM would snake-case AID to a_i_d (the acronym
	// column-naming trap) — pinned to the dump's name.
	AID   int    `gorm:"primaryKey;autoIncrement:false;column:aid" json:"aid"`
	ID    string `gorm:"column:id;not null;index" json:"id"`
	Name  string `gorm:"not null" json:"name"`
	Latin string `gorm:"not null" json:"latin"`
}

func (StaffAlias) TableName() string { return "src_vndb.staff_alias" }

type VNStaff struct {
	Seq  int64  `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"-"`
	ID   string `gorm:"column:id;not null;index" json:"id"`
	AID  int    `gorm:"column:aid;not null;index" json:"aid"`
	Role string `gorm:"not null" json:"role"`
	EID  *int   `gorm:"column:eid" json:"eid"`
	Note string `gorm:"not null" json:"note"`
}

func (VNStaff) TableName() string { return "src_vndb.vn_staff" }

type VNSeiyuu struct {
	ID   string `gorm:"primaryKey;column:id" json:"id"`
	CID  string `gorm:"primaryKey;column:cid" json:"cid"`
	AID  int    `gorm:"primaryKey;autoIncrement:false;column:aid" json:"aid"`
	Note string `gorm:"not null" json:"note"`
}

func (VNSeiyuu) TableName() string { return "src_vndb.vn_seiyuu" }
