package editing

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type Proposal struct {
	ID              int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	EntityFamily    string         `gorm:"not null;index:idx_edit_proposal_entity,priority:1" json:"entity_family"`
	EntityType      string         `gorm:"not null;index:idx_edit_proposal_entity,priority:2" json:"entity_type"`
	EntityID        int64          `gorm:"not null;index:idx_edit_proposal_entity,priority:3" json:"entity_id"`
	BaseRevisionSeq int            `gorm:"not null" json:"base_revision_seq"`
	Patch           datatypes.JSON `gorm:"type:jsonb;not null" json:"patch"`
	ProposerUID     int64          `gorm:"column:proposer_uid;not null" json:"proposer_uid"`
	Note            string         `gorm:"not null;default:''" json:"note"`
	Site            string         `gorm:"not null;index:idx_edit_proposal_site,priority:1" json:"site"`
	Status          int16          `gorm:"not null;index:idx_edit_proposal_entity,priority:4;index:idx_edit_proposal_site,priority:2" json:"status"`
	DecidedByUID    *int64         `gorm:"column:decided_by_uid" json:"decided_by_uid"`
	DecidedAt       *time.Time     `json:"decided_at"`
	DecisionNote    string         `gorm:"not null;default:''" json:"decision_note"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (Proposal) TableName() string { return "edit_proposal" }

type ProposalAmendment struct {
	ID         int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ProposalID int64          `gorm:"not null;uniqueIndex:uq_edit_amendment_proposal_seq,priority:1" json:"proposal_id"`
	Seq        int            `gorm:"not null;uniqueIndex:uq_edit_amendment_proposal_seq,priority:2" json:"seq"`
	PatchDelta datatypes.JSON `gorm:"type:jsonb;not null" json:"patch_delta"`
	AmenderUID int64          `gorm:"column:amender_uid;not null" json:"amender_uid"`
	Note       string         `gorm:"not null;default:''" json:"note"`
	CreatedAt  time.Time      `json:"created_at"`
}

func (ProposalAmendment) TableName() string { return "edit_proposal_amendment" }

type Revision struct {
	ID            int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	EntityFamily  string         `gorm:"not null;uniqueIndex:uq_edit_revision_entity_seq,priority:1" json:"entity_family"`
	EntityType    string         `gorm:"not null;uniqueIndex:uq_edit_revision_entity_seq,priority:2" json:"entity_type"`
	EntityID      int64          `gorm:"not null;uniqueIndex:uq_edit_revision_entity_seq,priority:3" json:"entity_id"`
	Seq           int            `gorm:"not null;uniqueIndex:uq_edit_revision_entity_seq,priority:4" json:"seq"`
	Action        int16          `gorm:"not null" json:"action"`
	ChangedFields datatypes.JSON `gorm:"type:jsonb;not null" json:"changed_fields"`
	Snapshot      datatypes.JSON `gorm:"type:jsonb;not null" json:"snapshot"`
	ActorUID      int64          `gorm:"column:actor_uid;not null" json:"actor_uid"`
	AmenderUID    *int64         `gorm:"column:amender_uid" json:"amender_uid"`
	ProposalID    *int64         `gorm:"index" json:"proposal_id"`
	Site          string         `gorm:"not null" json:"site"`
	CreatedAt     time.Time      `json:"created_at"`

	LegacyAction *string        `gorm:"->;column:legacy_action;type:text" json:"legacy_action,omitempty"`
	LegacyMeta   datatypes.JSON `gorm:"->;column:legacy_meta;type:jsonb" json:"legacy_meta,omitempty"`
	LegacyID     *int64         `gorm:"->;column:legacy_id" json:"legacy_id,omitempty"`
}

func (Revision) TableName() string { return "edit_revision" }

func AutoMigrate(db *gorm.DB) error {
	return db.AutoMigrate(&Proposal{}, &ProposalAmendment{}, &Revision{}, &SuppressedRow{})
}
