package editing

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// Engine tables (edit_* prefix, catalog DB pool — charter ruling 2).
//
// Storage conventions (the GORM-trap discipline, charter ruling 10):
//
//   - Identity primary keys use the full three-part recipe
//     (`autoIncrement:false` + explicit type carrying PRIMARY KEY +
//     `default:(-)`); see catalog/model/person.go for the probed rationale.
//   - INTENT columns whose zero value is meaningful (status,
//     base_revision_seq, action) are `not null` WITHOUT a gorm default tag —
//     the service layer always writes them explicitly.
//   - Composite indexes mark priority on EVERY member (partial marking
//     silently reorders columns).
//   - UID columns carry explicit column tags (the b_i_d snake-case trap).

// Proposal is one edit_proposal row: a field-key→new-value patch against an
// entity, awaiting review or already decided (doc 21 §2.3).
type Proposal struct {
	ID           int64  `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	EntityFamily string `gorm:"not null;index:idx_edit_proposal_entity,priority:1" json:"entity_family"`
	EntityType   string `gorm:"not null;index:idx_edit_proposal_entity,priority:2" json:"entity_type"`
	EntityID     int64  `gorm:"not null;index:idx_edit_proposal_entity,priority:3" json:"entity_id"`
	// BaseRevisionSeq is the entity's max revision seq at proposal time
	// (0 = the entity had no engine revisions yet). Merge rebases the patch
	// against every revision after it (doc 21 §2.3 基线漂移).
	BaseRevisionSeq int `gorm:"not null" json:"base_revision_seq"`
	// Patch is the ORIGINAL field-key→new-value JSONB document (D1). The
	// effective patch is patch ⊕ amendments, computed — never stored.
	Patch       datatypes.JSON `gorm:"type:jsonb;not null" json:"patch"`
	ProposerUID int64          `gorm:"column:proposer_uid;not null" json:"proposer_uid"`
	Note        string         `gorm:"not null;default:''" json:"note"`
	// Site is the tenant the proposal was filed from; policy overlays and
	// the S2S site binding key on it.
	Site   string `gorm:"not null;index:idx_edit_proposal_site,priority:1" json:"site"`
	Status int16  `gorm:"not null;index:idx_edit_proposal_entity,priority:4;index:idx_edit_proposal_site,priority:2" json:"status"`
	// Decision bookkeeping: who closed the proposal (merge/decline/withdraw)
	// and why. The merged revision carries the proposer+amender double
	// signature; the reviewer's identity lives here.
	DecidedByUID *int64     `gorm:"column:decided_by_uid" json:"decided_by_uid"`
	DecidedAt    *time.Time `json:"decided_at"`
	DecisionNote string     `gorm:"not null;default:''" json:"decision_note"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

func (Proposal) TableName() string { return "edit_proposal" }

// ProposalAmendment is one maintainer edit on an open proposal (doc 21
// §2.3): a patch delta (set/unset field keys) applied in seq order on top of
// the original patch. Amendments never change proposal status — only
// content — and are kept forever for per-field contribution attribution.
type ProposalAmendment struct {
	ID         int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ProposalID int64 `gorm:"not null;uniqueIndex:uq_edit_amendment_proposal_seq,priority:1" json:"proposal_id"`
	// Seq is per-proposal monotonic; the unique index makes concurrent
	// amenders collide instead of silently interleaving.
	Seq int `gorm:"not null;uniqueIndex:uq_edit_amendment_proposal_seq,priority:2" json:"seq"`
	// PatchDelta is a JSONB {"set": {key: value}, "unset": [key]} document:
	// set = change/add a field, unset = reject that field from the patch.
	PatchDelta datatypes.JSON `gorm:"type:jsonb;not null" json:"patch_delta"`
	AmenderUID int64          `gorm:"column:amender_uid;not null" json:"amender_uid"`
	Note       string         `gorm:"not null;default:''" json:"note"`
	CreatedAt  time.Time      `json:"created_at"`
}

func (ProposalAmendment) TableName() string { return "edit_proposal_amendment" }

// Revision is one row of the unified append-only revision log (lifetime
// pillar 2). Immutable once written; revert produces a NEW revision, never
// deletes one.
type Revision struct {
	ID           int64  `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	EntityFamily string `gorm:"not null;uniqueIndex:uq_edit_revision_entity_seq,priority:1" json:"entity_family"`
	EntityType   string `gorm:"not null;uniqueIndex:uq_edit_revision_entity_seq,priority:2" json:"entity_type"`
	EntityID     int64  `gorm:"not null;uniqueIndex:uq_edit_revision_entity_seq,priority:3" json:"entity_id"`
	// Seq is per-entity monotonic. The unique index makes concurrent merges
	// on one entity collide instead of silently forking history.
	Seq    int   `gorm:"not null;uniqueIndex:uq_edit_revision_entity_seq,priority:4" json:"seq"`
	Action int16 `gorm:"not null" json:"action"`
	// ChangedFields lists the field keys THIS merge actually changed,
	// written at merge time — never reconstructed later by diffing
	// snapshots (galgame changed_fields lesson).
	ChangedFields datatypes.JSON `gorm:"type:jsonb;not null" json:"changed_fields"`
	// Snapshot is the FULL registered-field state (key→value) after the
	// merge, supporting any-two-versions diff and revert.
	Snapshot datatypes.JSON `gorm:"type:jsonb;not null" json:"snapshot"`
	// Double signature (doc 21 §2.3): actor = proposer; amender = the last
	// amender when the merged patch carried amendments (NULL otherwise).
	ActorUID   int64  `gorm:"column:actor_uid;not null" json:"actor_uid"`
	AmenderUID *int64 `gorm:"column:amender_uid" json:"amender_uid"`
	ProposalID *int64 `gorm:"index" json:"proposal_id"`
	Site       string `gorm:"not null" json:"site"`
	CreatedAt  time.Time `json:"created_at"`
}

func (Revision) TableName() string { return "edit_revision" }

// AutoMigrate creates/updates the three engine tables. Called by the catalog
// migration entry point (cmd/migrate-catalog → catalog/migrate.Run, the
// single migration entry since W5) against the catalog DB pool; everything
// the schema needs is expressible in tags, so there is no raw-SQL section.
func AutoMigrate(db *gorm.DB) error {
	return db.AutoMigrate(&Proposal{}, &ProposalAmendment{}, &Revision{})
}
