package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// CatalogCharacter is a fictional character. Single layer + aliases
// (characters have no persona problem); the same character across media is
// ONE row — that is the point of the shared entity layer.
type CatalogCharacter struct {
	ID              int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	DisplayName     string  `gorm:"not null" json:"display_name"`
	DisplayNameNorm string  `gorm:"->;-:migration" json:"display_name_norm"`
	Latin           *string `json:"latin"`
	Lang            string  `gorm:"not null;default:''" json:"lang"`
	// Gender uses the Gender* constants; NULL = unknown.
	Gender      *int16 `json:"gender"`
	Description string `gorm:"not null;default:''" json:"description"`
	// InstanceOf is the cross-universe variant escape hatch (doc 17 R6, VNDB
	// instance_of): a variant character points at its base character instead
	// of forcing duplicated rows or an over-merged one. Nullable self FK.
	InstanceOf      *int64         `gorm:"index;type:bigint" json:"instance_of"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`

	Instance *CatalogCharacter `gorm:"foreignKey:InstanceOf" json:"instance,omitempty"`
}

func (CatalogCharacter) TableName() string { return "catalog_character" }

// CatalogCharacterAlias mirrors CatalogNameAlias for characters.
type CatalogCharacterAlias struct {
	ID          int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	CharacterID int64   `gorm:"not null;type:bigint;uniqueIndex:uq_catalog_character_alias_owner_name_lang" json:"character_id"`
	Name        string  `gorm:"not null;uniqueIndex:uq_catalog_character_alias_owner_name_lang" json:"name"`
	NameNorm    string  `gorm:"->;-:migration" json:"name_norm"`
	Latin       *string `json:"latin"`
	Lang        string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_character_alias_owner_name_lang" json:"lang"`
	// Kind uses the AliasKind* constants.
	Kind               int16 `gorm:"not null" json:"kind"`
	IsPrimaryForLocale bool  `gorm:"not null" json:"is_primary_for_locale"`

	Character *CatalogCharacter `gorm:"foreignKey:CharacterID" json:"character,omitempty"`
}

func (CatalogCharacterAlias) TableName() string { return "catalog_character_alias" }
