package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// CatalogCharacter is a fictional character. Single layer + aliases
// (characters have no persona problem); the same character across media is
// ONE row — that is the point of the shared entity layer.
type CatalogCharacter struct {
	ID              int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	DisplayName     string  `gorm:"not null" json:"display_name"`
	DisplayNameNorm string  `gorm:"->;-:migration" json:"display_name_norm"`
	Latin           *string `json:"latin"`
	Lang            string  `gorm:"not null;default:''" json:"lang"`
	// Gender uses the Gender* constants; NULL = unknown.
	Gender      *int16 `json:"gender"`
	Description string `gorm:"not null;default:''" json:"description"`
	// InstanceOf is the cross-universe variant escape hatch (doc 17 R6, VNDB
	// instance_of): a variant character points at its base character instead
	// of forcing duplicated rows or an over-merged one. Nullable self FK.
	InstanceOf *int64 `gorm:"index;type:bigint" json:"instance_of"`
	// ImageHash is the character portrait's content-addressed hash in the image
	// service (same shape as the galgame/work image columns); NULL until the
	// step-47 VNDB portrait wave backfills it. This step only lands the column.
	ImageHash *string `json:"image_hash"`
	// FigureHash is the character's FULL-BODY standing art (立绘 / tachi-e),
	// content-addressed in the image service exactly like ImageHash.
	//
	// It is a separate column rather than a second candidate for ImageHash
	// because the two are different assets with different shapes and different
	// uses: ImageHash is a bust rendered at 256x360 `cover` and belongs in a
	// list or beside a name, while this is a whole figure on a transparent-ish
	// white field whose aspect must be preserved (preset "character_figure",
	// fit `inside`). Cover-cropping a standing figure to a portrait box is how
	// you get a picture of someone's midriff.
	//
	// NULL is the normal state: only Getchu supplies this at scale, and only
	// for the works it lists.
	FigureHash *string `json:"figure_hash"`
	// --- typical-set physical attributes (refs/proj/81 field PR C2) ---
	// The display-core attribute set that most sources carry, promoted to real
	// typed columns (the long tail lives in Extra). Every column is a nullable
	// pointer: NULL = unknown/unset (no meaningful zero, no default tag). Written
	// by internal/jobs/charattrs from the VNDB typed columns (survivorship: vndb
	// preferred) and the Bangumi infobox (bgm fills gaps). BirthdayMonth/Day are
	// month+day only — the year is not a real column (kept in Extra when a source
	// supplies one).
	BirthdayMonth *int16 `json:"birthday_month"`
	BirthdayDay   *int16 `json:"birthday_day"`
	// BloodType uses the BloodType* constants (1=A 2=B 3=AB 4=O); NULL = unknown.
	BloodType *int16 `json:"blood_type"`
	// HeightCm/WeightKg are the character's canonical height/weight; BustCm/
	// WaistCm/HipCm are the three-size measurements; all in cm/kg. Cup is the
	// bra-cup letter (verbatim source token, upper-cased: A/B/…/AAA).
	HeightCm *int16  `json:"height_cm"`
	WeightKg *int16  `json:"weight_kg"`
	BustCm   *int16  `json:"bust_cm"`
	WaistCm  *int16  `json:"waist_cm"`
	HipCm    *int16  `json:"hip_cm"`
	Cup      *string `json:"cup"`
	// Extra is the governed long-tail escape hatch (doc 17 R9 shape, cloned from
	// catalog_work): object-only jsonb, source-namespaced. charattrs writes the
	// Bangumi infobox long-tail under the "bgm" key ({"bgm": {"星座": "…", …}});
	// the namespace is replaced wholesale each run (idempotent). datatypes.JSON's
	// zero value is nil, so the default '{}' fires with no zero-value trap.
	Extra           datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"extra"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`

	Instance *CatalogCharacter `gorm:"foreignKey:InstanceOf" json:"instance,omitempty"`
}

func (CatalogCharacter) TableName() string { return "catalog_character" }

// CatalogCharacterAlias mirrors CatalogNameAlias for characters.
type CatalogCharacterAlias struct {
	ID          int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	CharacterID int64   `gorm:"not null;type:bigint;uniqueIndex:uq_catalog_character_alias_owner_name_lang" json:"character_id"`
	Name        string  `gorm:"not null;uniqueIndex:uq_catalog_character_alias_owner_name_lang" json:"name"`
	NameNorm    string  `gorm:"->;-:migration" json:"name_norm"`
	Latin       *string `json:"latin"`
	Lang        string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_character_alias_owner_name_lang" json:"lang"`
	// Kind uses the AliasKind* constants.
	Kind               int16 `gorm:"not null" json:"kind"`
	IsPrimaryForLocale bool  `gorm:"not null" json:"is_primary_for_locale"`

	Character *CatalogCharacter `gorm:"foreignKey:CharacterID" json:"character,omitempty"`
}

func (CatalogCharacterAlias) TableName() string { return "catalog_character_alias" }

// CatalogCharacterIntro is one multilingual intro/description row for a
// character (field PR C1, refs/proj/65), cloning the catalog_work_intro shape.
// Characters are catalog-NATIVE entities — no claimed/bodyless split, no XOR,
// no bridging: every row here is read directly by the character read face. One
// row per (character, language, source): the unique key lets several sources
// coexist for the same language, and the read face merges them per language
// (source_id ascending wins), exactly like the work intro merge.
//
// source_id is row-level provenance — NOT NULL with NO default: a meaningful
// source is always known at write time, and a default tag would drop a
// legitimately-low source id from the INSERT (the default-tag zero-value trap).
type CatalogCharacterIntro struct {
	ID          int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	CharacterID int64 `gorm:"not null;uniqueIndex:uq_catalog_character_intro" json:"character_id"`
	// Lang is BCP-47 and part of the uniqueness key, hence NOT NULL DEFAULT ''
	// (same rationale as catalog_work_intro / the alias tables).
	Lang string `gorm:"not null;default:'';uniqueIndex:uq_catalog_character_intro" json:"lang"`
	// Intro is the body text — verbatim from the source except CRLF→LF and,
	// for VNDB, the spoiler-span removal + markup unwrap (see
	// internal/jobs/entityintros). NOT NULL, no default: content is always
	// supplied.
	Intro string `gorm:"type:text;not null" json:"intro"`
	// SourceID is the provenance FK. Part of the unique key. A MACHINE-translated
	// row (Provenance=1) carries the SOURCE row's source_id — attribution is
	// "translated from that source" — and is told apart from the source row
	// purely by Provenance (the catalog_work_intro step-75 shape).
	SourceID int16 `gorm:"not null;uniqueIndex:uq_catalog_character_intro" json:"source_id"`
	// Provenance is 0=source / 1=machine (entity intro MT, refs/proj/172). A
	// meaningful zero value, so NOT NULL with NO default tag (the default-tag
	// zero-value trap); a source row records 0 explicitly on INSERT.
	Provenance int16 `gorm:"not null" json:"provenance"`
	// SrcHash is sha256(source text) on a machine row — the re-translate
	// trigger. Empty on source rows; NOT NULL DEFAULT ''.
	SrcHash string `gorm:"not null;default:''" json:"src_hash"`
	// MTModel is the model id that produced a machine row; empty on source rows.
	MTModel   string    `gorm:"not null;default:''" json:"mt_model"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Character *CatalogCharacter `gorm:"foreignKey:CharacterID" json:"character,omitempty"`
	Source    *CatalogSource    `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogCharacterIntro) TableName() string { return "catalog_character_intro" }

// CatalogCharacterTrait is one VNDB trait vocabulary row (step 93, refs/proj/93
// ruling 1): a SINGLE-SOURCE vocabulary, so vndb_tid IS the source map — no
// separate map table until a second source exists (catalog_tag grew one because
// it converges THREE sources; YAGNI here). Names/descriptions land verbatim EN
// this wave; alias/description are the future zh-localization feedstock.
// GroupTID is the verbatim VNDB root-group tid (” = this row IS a root group);
// group display names resolve by self-join at read time. Sexual marks the two
// sexual trait families (685/3,327) — stored, surfaced on the read face, gated
// by consumers (the step-81 BWH/cup precedent: the catalog is R18-capable).
type CatalogCharacterTrait struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// VndbTID is the VNDB trait id ("i1"), UNIQUE — the single-source map.
	VndbTID string `gorm:"column:vndb_tid;not null;uniqueIndex:uq_catalog_character_trait_vndb_tid" json:"vndb_tid"`
	// Name is the verbatim VNDB English trait name.
	Name string `gorm:"not null" json:"name"`
	// NameZh is the Simplified-Chinese rendering of Name (wave 176). '' = none
	// yet, which is the honest state for a trait nobody has rendered — the read
	// faces omit the field rather than echoing the English twice. A DEFAULT ''
	// is correct here (unlike the intro-table provenance columns): every
	// pre-existing row genuinely has no Chinese name, so AutoMigrate's
	// `ADD COLUMN … NOT NULL DEFAULT ''` writes the right value and no
	// preMigrate backfill block is needed.
	NameZh string `gorm:"column:name_zh;not null;default:''" json:"name_zh"`
	// NameZhProvenance records WHERE NameZh came from: 0 = curated (the MIT
	// community dictionary / a human), 1 = machine translation. Meaningful only
	// when NameZh != '' — an empty name has no provenance — which is why a
	// plain default:0 carries no zero-value trap: the '' rows the default lands
	// on are exactly the rows whose provenance nobody reads. Curated beats
	// machine: the ingest path may overwrite a 1 but never a 0.
	NameZhProvenance int16 `gorm:"column:name_zh_provenance;not null;default:0" json:"name_zh_provenance"`
	// GroupTID is the verbatim VNDB root-group tid; '' = this row is a root.
	// NOT NULL with no default: the importer always writes it explicitly ('' is
	// a meaningful value — the default-tag zero-value trap avoided).
	GroupTID string `gorm:"column:group_tid;not null" json:"group_tid"`
	// GOrder is VNDB's display order within the group.
	GOrder int16 `gorm:"column:gorder;not null" json:"gorder"`
	// DefaultSpoil is VNDB's default spoiler level for NEW taggings (0/1/2) —
	// vocabulary metadata; the per-character level lives on the link row.
	DefaultSpoil int16 `gorm:"column:default_spoil;not null" json:"default_spoil"`
	Sexual       bool  `gorm:"not null" json:"sexual"`
	Searchable   bool  `gorm:"not null" json:"searchable"`
	// Applicable=false means VNDB stopped offering the trait for new taggings;
	// existing links are real history and are stored regardless (ruling 5).
	Applicable bool `gorm:"not null" json:"applicable"`
	// Alias is the newline-separated VNDB alias list (search feedstock).
	Alias string `gorm:"type:text;not null" json:"alias"`
	// Description is the VNDB English description, BBCode-ish (zh feedstock).
	Description string    `gorm:"type:text;not null" json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (CatalogCharacterTrait) TableName() string { return "catalog_character_trait" }

// CatalogCharacterTraitParent is one DAG edge of the trait hierarchy (VNDB
// traits_parents, ~3.7k rows; multi-parent is legal). Raw material this wave —
// no read-face consumer yet (a future hierarchy/browser wave). Composite PK,
// both sides OUR trait ids (resolved from vndb tids at import).
type CatalogCharacterTraitParent struct {
	TraitID  int64 `gorm:"primaryKey;autoIncrement:false" json:"trait_id"`
	ParentID int64 `gorm:"primaryKey;autoIncrement:false" json:"parent_id"`

	Trait  *CatalogCharacterTrait `gorm:"foreignKey:TraitID" json:"trait,omitempty"`
	Parent *CatalogCharacterTrait `gorm:"foreignKey:ParentID" json:"parent,omitempty"`
}

func (CatalogCharacterTraitParent) TableName() string { return "catalog_character_trait_parent" }

// CatalogCharacterTraitLink is one character×trait assignment (VNDB
// chars_traits via the exact character anchors, ~2.9M rows). SpoilerLevel is
// the per-character 0/1/2 (the read face defaults to 0, ?spoilers widens); Lie
// is VNDB's "presented as true, actually false" flag, surfaced verbatim.
// UNIQUE (character_id, trait_id) — character_id is the index prefix, so
// per-character reads need no extra single-column index. Writes are batched
// multi-row upserts with change detection (spoiler re-grades upstream →
// refresh-runnable, the step-62 discipline).
type CatalogCharacterTraitLink struct {
	ID          int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	CharacterID int64 `gorm:"not null;uniqueIndex:uq_catalog_character_trait_link,priority:1" json:"character_id"`
	TraitID     int64 `gorm:"not null;uniqueIndex:uq_catalog_character_trait_link,priority:2" json:"trait_id"`
	// SpoilerLevel is the per-character spoiler grade (0 none / 1 minor /
	// 2 major). NOT NULL, no default — 0 is meaningful and always written.
	SpoilerLevel int16 `gorm:"not null" json:"spoiler_level"`
	// Lie: the trait is presented as true but is actually a lie (VNDB flag).
	Lie       bool      `gorm:"not null" json:"lie"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Character *CatalogCharacter      `gorm:"foreignKey:CharacterID" json:"character,omitempty"`
	Trait     *CatalogCharacterTrait `gorm:"foreignKey:TraitID" json:"trait,omitempty"`
}

func (CatalogCharacterTraitLink) TableName() string { return "catalog_character_trait_link" }
