package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// CatalogCharacter is a fictional character. Single layer + aliases
// (characters have no persona problem); the same character across media is
// ONE row — that is the point of the shared entity layer.
type CatalogCharacter struct {
	ID              int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	DisplayName     string  `gorm:"not null" json:"display_name"`
	DisplayNameNorm string  `gorm:"->;-:migration" json:"display_name_norm"`
	Latin           *string `json:"latin"`
	Lang            string  `gorm:"not null;default:''" json:"lang"`
	// Gender uses the Gender* constants; NULL = unknown.
	Gender      *int16 `json:"gender"`
	Description string `gorm:"not null;default:''" json:"description"`
	// InstanceOf is the cross-universe variant escape hatch (doc 17 R6, VNDB
	// instance_of): a variant character points at its base character instead
	// of forcing duplicated rows or an over-merged one. Nullable self FK.
	InstanceOf *int64 `gorm:"index;type:bigint" json:"instance_of"`
	// ImageHash is the character portrait's content-addressed hash in the image
	// service (same shape as the galgame/work image columns); NULL until the
	// step-47 VNDB portrait wave backfills it. This step only lands the column.
	ImageHash       *string        `json:"image_hash"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`

	Instance *CatalogCharacter `gorm:"foreignKey:InstanceOf" json:"instance,omitempty"`
}

func (CatalogCharacter) TableName() string { return "catalog_character" }

// CatalogCharacterAlias mirrors CatalogNameAlias for characters.
type CatalogCharacterAlias struct {
	ID          int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	CharacterID int64   `gorm:"not null;type:bigint;uniqueIndex:uq_catalog_character_alias_owner_name_lang" json:"character_id"`
	Name        string  `gorm:"not null;uniqueIndex:uq_catalog_character_alias_owner_name_lang" json:"name"`
	NameNorm    string  `gorm:"->;-:migration" json:"name_norm"`
	Latin       *string `json:"latin"`
	Lang        string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_character_alias_owner_name_lang" json:"lang"`
	// Kind uses the AliasKind* constants.
	Kind               int16 `gorm:"not null" json:"kind"`
	IsPrimaryForLocale bool  `gorm:"not null" json:"is_primary_for_locale"`

	Character *CatalogCharacter `gorm:"foreignKey:CharacterID" json:"character,omitempty"`
}

func (CatalogCharacterAlias) TableName() string { return "catalog_character_alias" }

// CatalogCharacterIntro is one multilingual intro/description row for a
// character (field PR C1, refs/proj/65), cloning the catalog_work_intro shape.
// Characters are catalog-NATIVE entities — no claimed/bodyless split, no XOR,
// no bridging: every row here is read directly by the character read face. One
// row per (character, language, source): the unique key lets several sources
// coexist for the same language, and the read face merges them per language
// (source_id ascending wins), exactly like the work intro merge.
//
// source_id is row-level provenance — NOT NULL with NO default: a meaningful
// source is always known at write time, and a default tag would drop a
// legitimately-low source id from the INSERT (the default-tag zero-value trap).
type CatalogCharacterIntro struct {
	ID          int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	CharacterID int64 `gorm:"not null;uniqueIndex:uq_catalog_character_intro" json:"character_id"`
	// Lang is BCP-47 and part of the uniqueness key, hence NOT NULL DEFAULT ''
	// (same rationale as catalog_work_intro / the alias tables).
	Lang string `gorm:"not null;default:'';uniqueIndex:uq_catalog_character_intro" json:"lang"`
	// Intro is the body text — verbatim from the source except CRLF→LF and,
	// for VNDB, the spoiler-span removal + markup unwrap (see
	// internal/jobs/entityintros). NOT NULL, no default: content is always
	// supplied.
	Intro string `gorm:"type:text;not null" json:"intro"`
	// SourceID is the provenance FK. Part of the unique key.
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_character_intro" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Character *CatalogCharacter `gorm:"foreignKey:CharacterID" json:"character,omitempty"`
	Source    *CatalogSource    `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogCharacterIntro) TableName() string { return "catalog_character_intro" }
