package model

import "time"

type CatalogClaimEvent struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;index" json:"work_id"`

	// FromState / ToState are ClaimState* values.
	//
	// FromState is NULLABLE and NULL means "no prior state" — the transition
	// that created the claim (there was no claim to have a state), and the one
	// case a sentinel like -1 would have modelled dishonestly: -1 is a value
	// outside the vocabulary, and ClaimStateKey maps every such value onto the
	// conservative `hidden`, so a reader that forgot the sentinel would render
	// "was hidden" for a birth event. NULL cannot be misread that way.
	//
	// ToState is NOT NULL and carries a MEANINGFUL ZERO (0 = live), so it is
	// declared without a `default:` tag: a DB default would let an INSERT that
	// omits a legitimate live transition silently take the default instead
	// (the default-tag zero-value trap that shipped trust_tier=0 as 1).
	FromState *int16 `gorm:"column:from_state" json:"from_state"`
	ToState   int16  `gorm:"column:to_state;not null" json:"to_state"`

	ActorUID  int64     `gorm:"column:actor_uid;not null;index" json:"actor_uid"`
	Reason    *string   `gorm:"type:text" json:"reason"`
	Site      string    `gorm:"not null" json:"site"`
	CreatedAt time.Time `json:"created_at"`
}

func (CatalogClaimEvent) TableName() string { return "catalog_claim_event" }
