package model

import "time"

// CatalogClaimEvent is the append-only log of claim-state transitions
// (refs/plans/10 03 §3). It is the registry's ONE lifecycle primitive, and it
// deliberately is NOT a message/inbox table:
//
// The seven wiki message types the retiring family carried were, without
// exception, either a claim-state transition (submitted / claimed / approved /
// declined / banned / unbanned) or an engine revision (edited_pending). The
// registry therefore records only the AUDIT FACT — who moved this claim from
// which state to which, when, and why — and every product feature built on top
// of it (inboxes, unread counters, moemoepoint awards, admin queues) is a
// DOWNSTREAM product concern fed by the S2S cursor feed over this table. A
// registry that shipped an inbox would be importing a product into the
// identity layer, which is the wiki habit this design retires.
//
// Consequences of that framing, all deliberate:
//
//   - no read/unread state, no recipient column. The recipient is derivable
//     downstream (forum holds the creator snapshot; moyu re-derives it), and a
//     per-consumer read cursor belongs to the consumer.
//   - the id space is NEW (a new table), so downstream idempotency keys built
//     on the old galgame_message ids can never collide with these — the one
//     thing 03 §8-2 forbids breaking.
//   - the row is immutable. A correction is another row, never an UPDATE.
//
// N1 creates the TABLE ONLY: no writer exists yet. The lifecycle endpoints
// that emit these rows are N2's delivery, and wiring them earlier would mean a
// write path with no reviewed semantics behind it.
type CatalogClaimEvent struct {
	// Monotonic id — the cursor of the S2S feed, hence the identity PK recipe
	// (a bigint IDENTITY column GORM must never try to supply a value for).
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// WorkID is the claimed registry row whose claim moved. No FK: this log
	// outlives the work row exactly as catalog_revision does — the history of a
	// deleted entity is the last thing that may vanish with it.
	// A plain single-column index is the whole access plan: the GLOBAL feed
	// cursors on the primary key, and a per-work history is a handful of rows
	// the planner sorts for free after this index narrows to them.
	WorkID int64 `gorm:"not null;index" json:"work_id"`

	// FromState / ToState are ClaimState* values.
	//
	// FromState is NULLABLE and NULL means "no prior state" — the transition
	// that created the claim (there was no claim to have a state), and the one
	// case a sentinel like -1 would have modelled dishonestly: -1 is a value
	// outside the vocabulary, and ClaimStateKey maps every such value onto the
	// conservative `hidden`, so a reader that forgot the sentinel would render
	// "was hidden" for a birth event. NULL cannot be misread that way.
	//
	// ToState is NOT NULL and carries a MEANINGFUL ZERO (0 = live), so it is
	// declared without a `default:` tag: a DB default would let an INSERT that
	// omits a legitimate live transition silently take the default instead
	// (the default-tag zero-value trap that shipped trust_tier=0 as 1).
	FromState *int16 `gorm:"column:from_state" json:"from_state"`
	ToState   int16  `gorm:"column:to_state;not null" json:"to_state"`

	// ActorUID is the user who caused the transition; 0 = system/unattributed
	// (a nightly projector, a cascade). A meaningful zero again — not null, no
	// default.
	ActorUID int64 `gorm:"column:actor_uid;not null" json:"actor_uid"`
	// Reason is the moderator's note (decline reason, ban reason). NULL = none
	// given, which is distinct from an empty note the actor deliberately left.
	Reason *string `gorm:"type:text" json:"reason"`
	// Site is the product site the claim belongs to — the same tenant key as
	// catalog_work.site, so a consumer can filter the global feed down to its
	// own claims without joining.
	Site string `gorm:"not null" json:"site"`
	// CreatedAt is the audit timestamp. It is NOT the feed order: the feed
	// cursors on the monotonic id, because two rows in one transaction can
	// share a timestamp but never an id.
	CreatedAt time.Time `json:"created_at"`
}

func (CatalogClaimEvent) TableName() string { return "catalog_claim_event" }
