package model

import "time"

type CatalogCoverVote struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// WorkID + ActorUID are the ballot's identity: one vote per user per WORK.
	// Both columns carry the unique key with NO explicit priority — the composite
	// index priority trap is that tagging only one member silently reorders the
	// columns, so either every member is numbered or none is.
	WorkID    int64     `gorm:"not null;uniqueIndex:uq_catalog_cover_vote" json:"work_id"`
	CoverID   int64     `gorm:"not null;index" json:"cover_id"`
	ActorUID  int64     `gorm:"column:actor_uid;not null;uniqueIndex:uq_catalog_cover_vote" json:"actor_uid"`
	Site      string    `gorm:"not null" json:"site"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (CatalogCoverVote) TableName() string { return "catalog_cover_vote" }
