package model

import "time"

// CatalogCoverVote is one user's vote for the best cover of one work (wave 175).
//
// It is ADVISORY DATA and nothing else. A vote never writes sort_order and never
// writes portrait_pinned: the editorial pins stay the editors', and a downstream
// UI decides for itself whether the counts reorder a gallery, decorate it, or go
// unrendered. That framing is what lets the registry hold the table at all — the
// vote is a fact about an identity's image rows, not a product's like button, and
// the moment it started moving the editorial columns it would be the latter.
//
// Grain: ONE vote per (work, user), not per cover. A user is answering "which of
// this work's covers is the best one", so re-voting a different cover MOVES the
// existing row (the unique key below is the upsert target) rather than
// accumulating a second ballot. The cover reference therefore is not part of the
// key — it is the row's value.
//
// NSFW is not a write-side concern here: the per-image content-rating columns
// (catalog_work_cover.sexual / .violence) already trim the read side, and the
// same trimming applies to whatever the votes decorate.
type CatalogCoverVote struct {
	// Identity PK, the same recipe as the cover rows this table points at.
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// WorkID + ActorUID are the ballot's identity: one vote per user per WORK.
	// Both columns carry the unique key with NO explicit priority — the composite
	// index priority trap is that tagging only one member silently reorders the
	// columns, so either every member is numbered or none is.
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_cover_vote" json:"work_id"`
	// CoverID is the voted catalog_work_cover row — a PLAIN bigint column with a
	// plain index, deliberately NOT a GORM association: declaring one makes GORM
	// copy the referenced identity PK's full type (`bigint GENERATED BY DEFAULT AS
	// IDENTITY PRIMARY KEY`) onto this FK column. The real referential rule is a
	// raw-SQL FK with ON DELETE CASCADE in the migrate package, so deleting a
	// cover takes its votes with it and no Go code has to remember to.
	//
	// Indexed because the aggregation reads this way round: "how many votes does
	// each of these covers have".
	//
	// Known consequence of pointing at the ROW rather than the image hash: the
	// editing face replaces a work's curated cover set wholesale (editspec
	// applyCovers deletes source=curated rows and recreates them, new ids), so
	// editing a work's covers cascades its votes away. Accepted here — a vote is
	// cheap advisory data — and the fix, if it ever matters, is to make that
	// facet upsert by image_hash instead of bolting a bypass onto this table.
	CoverID int64 `gorm:"not null;index" json:"cover_id"`
	// ActorUID is the voting user's global uid, the same identity
	// CatalogClaimEvent.ActorUID carries. Unlike that log, 0 is not a legal value
	// here: a claim transition may be system-attributed (a projector, a cascade),
	// a taste never is — the write face rejects uid <= 0.
	ActorUID int64 `gorm:"column:actor_uid;not null;uniqueIndex:uq_catalog_cover_vote" json:"actor_uid"`
	// Site is the product site the vote came in from — provenance, exactly as on
	// catalog_claim_event, and deliberately NOT part of the unique key: the votes
	// aggregate across every site, so one person voting from two of them is one
	// ballot that moves, not two that add up.
	Site      string    `gorm:"not null" json:"site"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (CatalogCoverVote) TableName() string { return "catalog_cover_vote" }
