package model

import "time"

// Spoiler levels for credit edges (VNDB chars.vns shape).
const (
	SpoilerNone   int16 = 0
	SpoilerMild   int16 = 1
	SpoilerSevere int16 = 2
)

// CatalogCredit is one credit edge: a credited name performing a role on a
// work (doc 10 §4.5 + doc 17 R6) — the backbone of cross-media "who did
// what" queries.
//
// STRUCTURAL INVARIANT 1 (doc 10): this table has no column pointing at
// catalog_person and never will — credits reference credit_name.id only.
// "What did this person do" is always person → credit names (filtered by
// link_visibility for the viewer) → credits.
//
// Uniqueness is the doc 10 expression index (raw-SQL section):
// UNIQUE (work_id, credit_name_id, role_id, COALESCE(character_id, 0)) —
// the same name may hold the same role once per character (voice credits)
// and once uncharactered.
type CatalogCredit struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null" json:"work_id"`
	// CreditNameID is the credited identity (invariant 1 — see above).
	CreditNameID int64 `gorm:"not null;index" json:"credit_name_id"`
	// LabelID is the organizational signer, for label-natured roles
	// (developer/publisher credits); coexists with CreditNameID per role
	// semantics.
	LabelID *int64 `json:"label_id"`
	// RoleID references the unified role vocabulary (catalog_role, R1).
	RoleID int64 `gorm:"not null" json:"role_id"`
	// CharacterID links voice credits to the character performed.
	CharacterID *int64 `gorm:"index" json:"character_id"`
	// ReleaseID optionally narrows the credit to a specific release (R6);
	// NULL = credit applies to the work.
	ReleaseID *int64 `json:"release_id"`
	// Spoiler uses the Spoiler* constants (per-edge spoiler level).
	//
	// UNPOPULATED, and the read path does not gate on it: every row in prod is
	// 0, so ReadService.WorkCredits neither selects nor filters the column, and
	// the public face publishes credits whole at the default spoilers=0 posture
	// (unlike tags and character traits, which ARE capped). That is safe only
	// for as long as the column stays zero. Whichever ingest wave first writes
	// a non-zero spoiler here MUST add the cap to WorkCredits in the same
	// change — otherwise a secret casting credit ships to callers who asked for
	// the safe view, silently.
	Spoiler int16  `gorm:"not null" json:"spoiler"`
	Note    string `gorm:"not null;default:''" json:"note"`
	// SourceID is row-level provenance; NULL = user-curated.
	SourceID  *int16    `json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work       *CatalogWork       `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	CreditName *CatalogCreditName `gorm:"foreignKey:CreditNameID" json:"credit_name,omitempty"`
	Label      *CatalogLabel      `gorm:"foreignKey:LabelID" json:"label,omitempty"`
	Role       *CatalogRole       `gorm:"foreignKey:RoleID" json:"role,omitempty"`
	Character  *CatalogCharacter  `gorm:"foreignKey:CharacterID" json:"character,omitempty"`
	Release    *CatalogRelease    `gorm:"foreignKey:ReleaseID" json:"release,omitempty"`
	Source     *CatalogSource     `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogCredit) TableName() string { return "catalog_credit" }
