package model

import "time"

const (
	SpoilerNone   int16 = 0
	SpoilerMild   int16 = 1
	SpoilerSevere int16 = 2
)

type CatalogCredit struct {
	ID           int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID       int64     `gorm:"not null" json:"work_id"`
	CreditNameID int64     `gorm:"not null;index" json:"credit_name_id"`
	LabelID      *int64    `json:"label_id"`
	RoleID       int64     `gorm:"not null" json:"role_id"`
	CharacterID  *int64    `gorm:"index" json:"character_id"`
	ReleaseID    *int64    `json:"release_id"`
	Spoiler      int16     `gorm:"not null" json:"spoiler"`
	Note         string    `gorm:"not null;default:''" json:"note"`
	SourceID     *int16    `json:"source_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`

	Work       *CatalogWork       `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	CreditName *CatalogCreditName `gorm:"foreignKey:CreditNameID" json:"credit_name,omitempty"`
	Label      *CatalogLabel      `gorm:"foreignKey:LabelID" json:"label,omitempty"`
	Role       *CatalogRole       `gorm:"foreignKey:RoleID" json:"role,omitempty"`
	Character  *CatalogCharacter  `gorm:"foreignKey:CharacterID" json:"character,omitempty"`
	Release    *CatalogRelease    `gorm:"foreignKey:ReleaseID" json:"release,omitempty"`
	Source     *CatalogSource     `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogCredit) TableName() string { return "catalog_credit" }
