package model

import (
	"time"

	"gorm.io/datatypes"
)

// CatalogEngine is one visual-novel / game ENGINE (KiriKiri, Ren'Py, RealLive,
// Artemis, ...) — the data-layer-retirement wave's new facet (refs/plans/10
// charter ruling 4). VNDB publishes no engine data, so unlike ratings/tags/covers
// this facet has NO upstream source to regenerate it from: the wiki family's
// hand-curated galgame_engine rows are the ONLY copy, which is why the engine
// layer is migrated rather than discarded with the rest of the wiki tables.
//
// Name is the canonical engine name and is UNIQUE — the importer's conflict
// key. Description / Aliases carry NO default tag on purpose: the write path
// always supplies them explicitly ('' and '[]'), so a default tag would only
// open the door to the zero-value trap without buying anything.
//
// This wave lands the DATA only — there is deliberately no read face yet
// (charter W0: the read surface belongs to a later wave).
type CatalogEngine struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// Name is the canonical engine name, UNIQUE across the facet (the wiki
	// galgame_engine.name unique carried over verbatim).
	Name string `gorm:"type:text;not null;uniqueIndex" json:"name"`
	// Description is the engine blurb, verbatim from the source. NOT NULL with
	// NO default tag — the write path always supplies it (empty string when the
	// source carries none).
	Description string `gorm:"type:text;not null" json:"description"`
	// Aliases is the alternate-spelling array (the wiki galgame_engine.alias
	// jsonb carried over). NOT NULL with NO default tag — the write path always
	// supplies it ('[]' when the source carries none).
	Aliases   datatypes.JSON `gorm:"type:jsonb;not null" json:"aliases"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (CatalogEngine) TableName() string { return "catalog_engine" }

// CatalogWorkEngine is one work↔engine edge ("this work was built with this
// engine") — the engine facet's projection surface (refs/plans/10 charter
// ruling 4). One row per (work, engine): the UNIQUE key is the importer's
// conflict target, and engine_id carries its own index for the reverse lookup
// (engine → the works using it), mirroring catalog_series_member's shape.
//
// SourceID is row-level provenance, NOT NULL with NO default (the default-tag
// zero-value trap): the wiki projection writes source_id=12 (galgame_wiki)
// explicitly, and a future EGS/manual lane appends rows with its own source.
type CatalogWorkEngine struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// WorkID and EngineID form the unique key. Both carry an explicit priority
	// (all-or-nothing — a partially-prioritized shared index name silently
	// reorders the columns).
	WorkID   int64 `gorm:"not null;uniqueIndex:uq_catalog_work_engine,priority:1" json:"work_id"`
	EngineID int64 `gorm:"not null;index;uniqueIndex:uq_catalog_work_engine,priority:2" json:"engine_id"`
	// SourceID is the provenance FK (see the type doc).
	SourceID  int16     `gorm:"not null" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Engine *CatalogEngine `gorm:"foreignKey:EngineID" json:"engine,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkEngine) TableName() string { return "catalog_work_engine" }
