package model

import (
	"time"

	"gorm.io/datatypes"
)

// Polymorphic infrastructure tables ("add an entity, not a table"). Rows
// address entities by (EntityType* constant, id) — deliberately no FKs.

// CatalogRedirect records that old_id was merged into current_id (doc 10
// §5.2). Redirects are never deleted; every read path resolves through this
// table (invariant 3). CurrentID is FLATTENED ON WRITE: if the merge target
// is itself already redirected, the row points straight at the final
// canonical id — an A→B→C chain must never exist. The flattening (and the
// resolve service) is step 05; this step pins the key shape.
type CatalogRedirect struct {
	EntityType int16      `gorm:"primaryKey;autoIncrement:false" json:"entity_type"`
	OldID      int64      `gorm:"primaryKey;autoIncrement:false" json:"old_id"`
	CurrentID  int64      `gorm:"not null" json:"current_id"`
	MergedAt   *time.Time `json:"merged_at"`
	MergedBy   *int64     `json:"merged_by"`
	Reason     string     `gorm:"not null;default:''" json:"reason"`
}

func (CatalogRedirect) TableName() string { return "catalog_redirect" }

// CatalogEntityUsage tracks which site references an entity (the
// image_site_usage pattern). Hot-update narrow table: last_confirmed_at is
// rewritten constantly, so the table runs fillfactor=85 (raw-SQL section)
// and the timestamps carry NO index — both keep updates HOT (doc 17 R9).
// Second duty = delete protection (doc 10 invariant 8): an entity with any
// usage row can be merged (leaving a redirect) or soft-deleted, never
// hard-deleted. Enforcement lands with the services in step 05.
type CatalogEntityUsage struct {
	EntityType      int16     `gorm:"primaryKey;autoIncrement:false" json:"entity_type"`
	EntityID        int64     `gorm:"primaryKey;autoIncrement:false" json:"entity_id"`
	Site            string    `gorm:"primaryKey" json:"site"`
	FirstUsedAt     time.Time `gorm:"not null" json:"first_used_at"`
	LastConfirmedAt time.Time `gorm:"not null" json:"last_confirmed_at"`
}

func (CatalogEntityUsage) TableName() string { return "catalog_entity_usage" }

// CatalogRevision is the polymorphic edit history (the taxonomy_revision
// pattern generalized, doc 10 §9).
type CatalogRevision struct {
	ID         int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	EntityType int16 `gorm:"not null;uniqueIndex:uq_catalog_revision_entity_rev" json:"entity_type"`
	EntityID   int64 `gorm:"not null;uniqueIndex:uq_catalog_revision_entity_rev" json:"entity_id"`
	// Revision is per-entity monotonic; the service layer assigns it
	// (step 05). The unique index makes concurrent writers collide instead
	// of silently forking history.
	Revision int `gorm:"not null;uniqueIndex:uq_catalog_revision_entity_rev" json:"revision"`
	// Action uses the RevisionAction* constants.
	Action int16 `gorm:"not null" json:"action"`
	// Snapshot is the FULL entity state — including nested credit names /
	// aliases / external refs — not a diff. ChangedFields records what THIS
	// edit touched, written at edit time (galgame_revision lesson: never
	// reconstruct it later by diffing snapshots).
	Snapshot      datatypes.JSON `gorm:"type:jsonb;not null" json:"snapshot"`
	ChangedFields datatypes.JSON `gorm:"type:jsonb" json:"changed_fields,omitempty"`
	ActorID       *int64         `json:"actor_id"`
	IsMinor       bool           `gorm:"not null" json:"is_minor"`
	Note          string         `gorm:"not null;default:''" json:"note"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (CatalogRevision) TableName() string { return "catalog_revision" }
