package model

import (
	"time"

	"gorm.io/datatypes"
)

type CatalogRedirect struct {
	EntityType int16      `gorm:"primaryKey;autoIncrement:false" json:"entity_type"`
	OldID      int64      `gorm:"primaryKey;autoIncrement:false" json:"old_id"`
	CurrentID  int64      `gorm:"not null" json:"current_id"`
	MergedAt   *time.Time `json:"merged_at"`
	MergedBy   *int64     `json:"merged_by"`
	Reason     string     `gorm:"not null;default:''" json:"reason"`
}

func (CatalogRedirect) TableName() string { return "catalog_redirect" }

type CatalogEntityUsage struct {
	EntityType      int16     `gorm:"primaryKey;autoIncrement:false" json:"entity_type"`
	EntityID        int64     `gorm:"primaryKey;autoIncrement:false" json:"entity_id"`
	Site            string    `gorm:"primaryKey" json:"site"`
	FirstUsedAt     time.Time `gorm:"not null" json:"first_used_at"`
	LastConfirmedAt time.Time `gorm:"not null" json:"last_confirmed_at"`
}

func (CatalogEntityUsage) TableName() string { return "catalog_entity_usage" }

type CatalogRevision struct {
	ID            int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	EntityType    int16          `gorm:"not null;uniqueIndex:uq_catalog_revision_entity_rev" json:"entity_type"`
	EntityID      int64          `gorm:"not null;uniqueIndex:uq_catalog_revision_entity_rev" json:"entity_id"`
	Revision      int            `gorm:"not null;uniqueIndex:uq_catalog_revision_entity_rev" json:"revision"`
	Action        int16          `gorm:"not null" json:"action"`
	Snapshot      datatypes.JSON `gorm:"type:jsonb;not null" json:"snapshot"`
	ChangedFields datatypes.JSON `gorm:"type:jsonb" json:"changed_fields,omitempty"`
	ActorID       *int64         `json:"actor_id"`
	IsMinor       bool           `gorm:"not null" json:"is_minor"`
	Note          string         `gorm:"not null;default:''" json:"note"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (CatalogRevision) TableName() string { return "catalog_revision" }
