package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// ⚠️ catalog_org WAS HERE, and is not coming back (removed wave 195,
// 2026-08-08; table and catalog_label.org_id dropped by migrate-catalog).
//
// It modelled "the legal entity / company behind labels" and was meant to
// answer "which company is this brand under". It never held a row in its
// entire life and no label ever carried an org_id, because a nullable FK
// structurally cannot answer that question: it expresses ONE relation at ONE
// level, while the real vocabulary is eight relations at arbitrary depth — an
// imprint chain, a studio SPAWNED from another, a superseded trading name.
// spawned/formerly had nowhere to live in it. Worse, it made two kinds of
// company entity with two id spaces and two read faces, so every company
// needed an answer to "org or label?" — and for VISUAL ARTS, which publishes
// under its own name AND owns Key, the answer is "both".
//
// The question is now answered by CatalogLabelRelation (below), fed for every
// company VNDB relates to anything by the corporate-graph spine
// (internal/jobs/orglabels/spine.go). If you are about to reintroduce a
// company entity because labels feel like the wrong grain: add a relation
// kind, or a LabelKind, not a second table. Entity type 2 stays unallocated
// (model/constants.go).

// CatalogLabel is the signing subject credits and works hang off: game brand
// / bunko / publisher / anime studio / doujin circle / group. The galgame
// domain's company-vs-brand distinction lives here too — both are labels, and
// which is which is a CatalogLabelRelation edge, not a second table.
type CatalogLabel struct {
	ID              int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	DisplayName     string  `gorm:"not null" json:"display_name"`
	DisplayNameNorm string  `gorm:"->;-:migration" json:"display_name_norm"`
	Latin           *string `json:"latin"`
	Lang            string  `gorm:"not null;default:''" json:"lang"`
	// Kind uses the LabelKind* constants (no default tag — 0=game_brand is a
	// meaningful zero).
	Kind int16  `gorm:"not null" json:"kind"`
	Note string `gorm:"not null;default:''" json:"note"`
	// LogoHash is the label's brand logo / avatar in the image service, catalog
	// scope (wave 170). One single slot, mirroring catalog_character.image_hash:
	// a label has one identifying mark, so there is no logo table and no
	// multi-image gallery. Empty string = no logo, which is also the candidate
	// filter the backfill selects on, and therefore the whole of the
	// bangumi > cien precedence: bangumi runs first and cien only ever fills
	// what is still empty. Provenance goes to field_provenance["logo_hash"].
	// Any new image column in catalog scope MUST also join the registry in
	// internal/platform/catalog/imagerefs or its bytes are GC'd a year later.
	LogoHash        string         `gorm:"type:text;not null;default:''" json:"logo_hash"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`
}

func (CatalogLabel) TableName() string { return "catalog_label" }

// CatalogLabelAlias mirrors CatalogNameAlias for labels.
type CatalogLabelAlias struct {
	ID       int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	LabelID  int64   `gorm:"not null;type:bigint;uniqueIndex:uq_catalog_label_alias_owner_name_lang" json:"label_id"`
	Name     string  `gorm:"not null;uniqueIndex:uq_catalog_label_alias_owner_name_lang" json:"name"`
	NameNorm string  `gorm:"->;-:migration" json:"name_norm"`
	Latin    *string `json:"latin"`
	Lang     string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_label_alias_owner_name_lang" json:"lang"`
	// Kind uses the AliasKind* constants.
	Kind               int16 `gorm:"not null" json:"kind"`
	IsPrimaryForLocale bool  `gorm:"not null" json:"is_primary_for_locale"`
	// SourceID / Provenance / MTModel: see CatalogNameAlias for why source_id is
	// nullable here and why provenance carries no default tag.
	SourceID   *int16 `gorm:"type:smallint" json:"source_id"`
	Provenance int16  `gorm:"not null" json:"provenance"`
	MTModel    string `gorm:"not null;default:''" json:"mt_model"`

	Label  *CatalogLabel  `gorm:"foreignKey:LabelID" json:"label,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogLabelAlias) TableName() string { return "catalog_label_alias" }

// CatalogLabelIntro is a label's multilingual description body, one row per
// (label, language, source) — the exact shape of CatalogPersonIntro /
// CatalogCharacterIntro (refs/proj/83 E2b). The unique key lets several
// sources coexist for the same language; the read face merges them per
// language (source_id ascending wins), like the work/person/character intro
// merge. Unlike the entity rows, no XOR / claimed bridge: a label is a native
// catalog entity, so its intro attaches to the label id directly.
//
// source_id is row-level provenance — NOT NULL with NO default: a meaningful
// source is always known at write time, and a default tag would drop a
// legitimately-low source id from the INSERT (the default-tag zero-value trap).
type CatalogLabelIntro struct {
	ID      int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	LabelID int64 `gorm:"not null;uniqueIndex:uq_catalog_label_intro" json:"label_id"`
	// Lang is BCP-47 and part of the uniqueness key, hence NOT NULL DEFAULT ''
	// (same rationale as catalog_person_intro / the alias tables).
	Lang string `gorm:"not null;default:'';uniqueIndex:uq_catalog_label_intro" json:"lang"`
	// Intro is the body text (verbatim from the source except CRLF→LF and, for
	// VNDB, the spoiler-span removal + markup unwrap). NOT NULL, no default.
	Intro string `gorm:"type:text;not null" json:"intro"`
	// SourceID is the provenance FK. Part of the unique key. A MACHINE-translated
	// row (Provenance=1) carries the SOURCE row's source_id and is told apart
	// purely by Provenance (the catalog_work_intro step-75 shape).
	SourceID int16 `gorm:"not null;uniqueIndex:uq_catalog_label_intro" json:"source_id"`
	// Provenance is 0=source / 1=machine (entity intro MT, refs/proj/172). A
	// meaningful zero value: NOT NULL with NO default tag.
	Provenance int16 `gorm:"not null" json:"provenance"`
	// SrcHash is sha256(source text) on a machine row — the re-translate
	// trigger. Empty on source rows; NOT NULL DEFAULT ''.
	SrcHash string `gorm:"not null;default:''" json:"src_hash"`
	// MTModel is the model id that produced a machine row; empty on source rows.
	MTModel   string    `gorm:"not null;default:''" json:"mt_model"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Label  *CatalogLabel  `gorm:"foreignKey:LabelID" json:"label,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogLabelIntro) TableName() string { return "catalog_label_intro" }

// CatalogLabelRelation is a label↔label corporate-structure edge (wave 186):
// the parent/subsidiary, imprint, spin-off and succession facts VNDB's
// producers_relations publishes and no catalog table held until now.
//
// SEMANTICS — a row reads "other_label_id is <relation> of label_id". So
// (label_id=Key, other_label_id=VisualArt's, relation=Parent) means
// "VisualArt's is the parent of Key".
//
// The graph is stored MIRRORED: every fact is written twice, once per
// direction, with the inverse relation code (parent↔subsidiary,
// imprint↔imprint_of, spawned↔origin, succeeded_by↔formerly). That is the
// upstream's own shape, and it means a reader NEVER inverts: the label detail
// face selects `WHERE label_id = ?` and renders what it finds, full stop.
//
// It is deliberately NOT CatalogEntityRelation. That table is a curated,
// single-row, registry-typed edge whose reverse phrase the read path composes;
// this one is a source-owned mirrored graph rebuilt wholesale per source, with
// a code vocabulary that ships with code (constants, not registry rows — the
// LabelKind rationale verbatim). Folding the two would force one of them to
// give up its rebuild story.
//
// Composite PK (label_id, other_label_id, relation, source_id) — the PK IS the
// uniqueness (CatalogWorkLabel's shape), and source_id is inside it so two
// sources may assert the same edge without fighting. SourceID is NOT NULL and
// carries no `default:` tag: every row here comes from an import that knows its
// source (the default-tag zero-value trap).
type CatalogLabelRelation struct {
	LabelID      int64 `gorm:"primaryKey;autoIncrement:false" json:"label_id"`
	OtherLabelID int64 `gorm:"primaryKey;autoIncrement:false;index" json:"other_label_id"` // reverse lookups
	// Relation is a LabelRelation* constant — see constants.go for the
	// vocabulary and its inverse pairing.
	Relation int16 `gorm:"primaryKey;autoIncrement:false" json:"relation"`
	SourceID int16 `gorm:"primaryKey;autoIncrement:false" json:"source_id"`
	// MatchedBy is 'rule:<rule-id>' provenance, the external_ref convention.
	MatchedBy string    `gorm:"not null" json:"matched_by"`
	CreatedAt time.Time `json:"created_at"`

	Label      *CatalogLabel  `gorm:"foreignKey:LabelID" json:"label,omitempty"`
	OtherLabel *CatalogLabel  `gorm:"foreignKey:OtherLabelID" json:"other_label,omitempty"`
	Source     *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogLabelRelation) TableName() string { return "catalog_label_relation" }
