package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type CatalogLabel struct {
	ID              int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	DisplayName     string         `gorm:"not null" json:"display_name"`
	DisplayNameNorm string         `gorm:"->;-:migration" json:"display_name_norm"`
	Latin           *string        `json:"latin"`
	Lang            string         `gorm:"not null;default:''" json:"lang"`
	Kind            int16          `gorm:"not null" json:"kind"`
	Note            string         `gorm:"not null;default:''" json:"note"`
	LogoHash        string         `gorm:"type:text;not null;default:''" json:"logo_hash"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`
}

func (CatalogLabel) TableName() string { return "catalog_label" }

type CatalogLabelAlias struct {
	ID                 int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	LabelID            int64   `gorm:"not null;type:bigint;uniqueIndex:uq_catalog_label_alias_owner_name_lang" json:"label_id"`
	Name               string  `gorm:"not null;uniqueIndex:uq_catalog_label_alias_owner_name_lang" json:"name"`
	NameNorm           string  `gorm:"->;-:migration" json:"name_norm"`
	Latin              *string `json:"latin"`
	Lang               string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_label_alias_owner_name_lang" json:"lang"`
	Kind               int16   `gorm:"not null" json:"kind"`
	IsPrimaryForLocale bool    `gorm:"not null" json:"is_primary_for_locale"`
	SourceID           *int16  `gorm:"type:smallint" json:"source_id"`
	Provenance         int16   `gorm:"not null" json:"provenance"`
	MTModel            string  `gorm:"not null;default:''" json:"mt_model"`

	Label  *CatalogLabel  `gorm:"foreignKey:LabelID" json:"label,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogLabelAlias) TableName() string { return "catalog_label_alias" }

type CatalogLabelIntro struct {
	ID         int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	LabelID    int64     `gorm:"not null;uniqueIndex:uq_catalog_label_intro" json:"label_id"`
	Lang       string    `gorm:"not null;default:'';uniqueIndex:uq_catalog_label_intro" json:"lang"`
	Intro      string    `gorm:"type:text;not null" json:"intro"`
	SourceID   int16     `gorm:"not null;uniqueIndex:uq_catalog_label_intro" json:"source_id"`
	Provenance int16     `gorm:"not null" json:"provenance"`
	SrcHash    string    `gorm:"not null;default:''" json:"src_hash"`
	MTModel    string    `gorm:"not null;default:''" json:"mt_model"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`

	Label  *CatalogLabel  `gorm:"foreignKey:LabelID" json:"label,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogLabelIntro) TableName() string { return "catalog_label_intro" }

type CatalogLabelRelation struct {
	LabelID      int64     `gorm:"primaryKey;autoIncrement:false" json:"label_id"`
	OtherLabelID int64     `gorm:"primaryKey;autoIncrement:false;index" json:"other_label_id"`
	Relation     int16     `gorm:"primaryKey;autoIncrement:false" json:"relation"`
	SourceID     int16     `gorm:"primaryKey;autoIncrement:false" json:"source_id"`
	MatchedBy    string    `gorm:"not null" json:"matched_by"`
	CreatedAt    time.Time `json:"created_at"`

	Label      *CatalogLabel  `gorm:"foreignKey:LabelID" json:"label,omitempty"`
	OtherLabel *CatalogLabel  `gorm:"foreignKey:OtherLabelID" json:"other_label,omitempty"`
	Source     *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogLabelRelation) TableName() string { return "catalog_label_relation" }
