package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// CatalogOrg is the legal entity / company behind labels. Like person it can
// be sparse — signing subjects are labels; org rows exist to group them.
// Orgs have no alias table on purpose (doc 10 ruling): a renamed org is a
// renamed_from relation or a separate label, not a spelling variant.
type CatalogOrg struct {
	ID          int64  `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	DisplayName string `gorm:"not null" json:"display_name"`
	// DisplayNameNorm is the NFKC-folded generated column (raw-SQL section).
	DisplayNameNorm string  `gorm:"->;-:migration" json:"display_name_norm"`
	Latin           *string `json:"latin"`
	Lang            string  `gorm:"not null;default:''" json:"lang"`
	Description     string  `gorm:"not null;default:''" json:"description"`
	// Fuzzy dissolution date (three nullable columns, doc 17 R9).
	DissolvedY      *int16         `json:"dissolved_y"`
	DissolvedM      *int16         `json:"dissolved_m"`
	DissolvedD      *int16         `json:"dissolved_d"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`
}

func (CatalogOrg) TableName() string { return "catalog_org" }

// CatalogLabel is the signing subject credits and works hang off: game brand
// / bunko / publisher / anime studio / doujin circle / group. The galgame
// domain's 会社 vs ブランド split is exactly Org vs Label.
type CatalogLabel struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// OrgID is nullable — "which company owns this brand" is often unknown.
	OrgID           *int64  `gorm:"index;type:bigint" json:"org_id"`
	DisplayName     string  `gorm:"not null" json:"display_name"`
	DisplayNameNorm string  `gorm:"->;-:migration" json:"display_name_norm"`
	Latin           *string `json:"latin"`
	Lang            string  `gorm:"not null;default:''" json:"lang"`
	// Kind uses the LabelKind* constants (no default tag — 0=game_brand is a
	// meaningful zero).
	Kind            int16          `gorm:"not null" json:"kind"`
	Note            string         `gorm:"not null;default:''" json:"note"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`

	Org *CatalogOrg `gorm:"foreignKey:OrgID" json:"org,omitempty"`
}

func (CatalogLabel) TableName() string { return "catalog_label" }

// CatalogLabelAlias mirrors CatalogNameAlias for labels.
type CatalogLabelAlias struct {
	ID       int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	LabelID  int64   `gorm:"not null;type:bigint;uniqueIndex:uq_catalog_label_alias_owner_name_lang" json:"label_id"`
	Name     string  `gorm:"not null;uniqueIndex:uq_catalog_label_alias_owner_name_lang" json:"name"`
	NameNorm string  `gorm:"->;-:migration" json:"name_norm"`
	Latin    *string `json:"latin"`
	Lang     string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_label_alias_owner_name_lang" json:"lang"`
	// Kind uses the AliasKind* constants.
	Kind               int16 `gorm:"not null" json:"kind"`
	IsPrimaryForLocale bool  `gorm:"not null" json:"is_primary_for_locale"`

	Label *CatalogLabel `gorm:"foreignKey:LabelID" json:"label,omitempty"`
}

func (CatalogLabelAlias) TableName() string { return "catalog_label_alias" }
