package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// CatalogOrg is the legal entity / company behind labels. Like person it can
// be sparse — signing subjects are labels; org rows exist to group them.
// Orgs have no alias table on purpose (doc 10 ruling): a renamed org is a
// renamed_from relation or a separate label, not a spelling variant.
type CatalogOrg struct {
	ID          int64  `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	DisplayName string `gorm:"not null" json:"display_name"`
	// DisplayNameNorm is the NFKC-folded generated column (raw-SQL section).
	DisplayNameNorm string  `gorm:"->;-:migration" json:"display_name_norm"`
	Latin           *string `json:"latin"`
	Lang            string  `gorm:"not null;default:''" json:"lang"`
	Description     string  `gorm:"not null;default:''" json:"description"`
	// Fuzzy dissolution date (three nullable columns, doc 17 R9).
	DissolvedY      *int16         `json:"dissolved_y"`
	DissolvedM      *int16         `json:"dissolved_m"`
	DissolvedD      *int16         `json:"dissolved_d"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`
}

func (CatalogOrg) TableName() string { return "catalog_org" }

// CatalogLabel is the signing subject credits and works hang off: game brand
// / bunko / publisher / anime studio / doujin circle / group. The galgame
// domain's 会社 vs ブランド split is exactly Org vs Label.
type CatalogLabel struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// OrgID is nullable — "which company owns this brand" is often unknown.
	OrgID           *int64  `gorm:"index;type:bigint" json:"org_id"`
	DisplayName     string  `gorm:"not null" json:"display_name"`
	DisplayNameNorm string  `gorm:"->;-:migration" json:"display_name_norm"`
	Latin           *string `json:"latin"`
	Lang            string  `gorm:"not null;default:''" json:"lang"`
	// Kind uses the LabelKind* constants (no default tag — 0=game_brand is a
	// meaningful zero).
	Kind int16  `gorm:"not null" json:"kind"`
	Note string `gorm:"not null;default:''" json:"note"`
	// LogoHash is the label's brand logo / avatar in the image service, catalog
	// scope (wave 170). One single slot, mirroring catalog_character.image_hash:
	// a label has one identifying mark, so there is no logo table and no
	// multi-image gallery. Empty string = no logo, which is also the candidate
	// filter the backfill selects on, and therefore the whole of the
	// bangumi > cien precedence: bangumi runs first and cien only ever fills
	// what is still empty. Provenance goes to field_provenance["logo_hash"].
	// Any new image column in catalog scope MUST also join the keep-alive union
	// in internal/jobs/catalog_image_refping.go or its bytes are GC'd a year later.
	LogoHash        string         `gorm:"type:text;not null;default:''" json:"logo_hash"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`

	Org *CatalogOrg `gorm:"foreignKey:OrgID" json:"org,omitempty"`
}

func (CatalogLabel) TableName() string { return "catalog_label" }

// CatalogLabelAlias mirrors CatalogNameAlias for labels.
type CatalogLabelAlias struct {
	ID       int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	LabelID  int64   `gorm:"not null;type:bigint;uniqueIndex:uq_catalog_label_alias_owner_name_lang" json:"label_id"`
	Name     string  `gorm:"not null;uniqueIndex:uq_catalog_label_alias_owner_name_lang" json:"name"`
	NameNorm string  `gorm:"->;-:migration" json:"name_norm"`
	Latin    *string `json:"latin"`
	Lang     string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_label_alias_owner_name_lang" json:"lang"`
	// Kind uses the AliasKind* constants.
	Kind               int16 `gorm:"not null" json:"kind"`
	IsPrimaryForLocale bool  `gorm:"not null" json:"is_primary_for_locale"`

	Label *CatalogLabel `gorm:"foreignKey:LabelID" json:"label,omitempty"`
}

func (CatalogLabelAlias) TableName() string { return "catalog_label_alias" }

// CatalogLabelIntro is a label's multilingual description body, one row per
// (label, language, source) — the exact shape of CatalogPersonIntro /
// CatalogCharacterIntro (refs/proj/83 E2b). The unique key lets several
// sources coexist for the same language; the read face merges them per
// language (source_id ascending wins), like the work/person/character intro
// merge. Unlike the entity rows, no XOR / claimed bridge: a label is a native
// catalog entity, so its intro attaches to the label id directly.
//
// source_id is row-level provenance — NOT NULL with NO default: a meaningful
// source is always known at write time, and a default tag would drop a
// legitimately-low source id from the INSERT (the default-tag zero-value trap).
type CatalogLabelIntro struct {
	ID      int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	LabelID int64 `gorm:"not null;uniqueIndex:uq_catalog_label_intro" json:"label_id"`
	// Lang is BCP-47 and part of the uniqueness key, hence NOT NULL DEFAULT ''
	// (same rationale as catalog_person_intro / the alias tables).
	Lang string `gorm:"not null;default:'';uniqueIndex:uq_catalog_label_intro" json:"lang"`
	// Intro is the body text (verbatim from the source except CRLF→LF and, for
	// VNDB, the spoiler-span removal + markup unwrap). NOT NULL, no default.
	Intro string `gorm:"type:text;not null" json:"intro"`
	// SourceID is the provenance FK. Part of the unique key.
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_label_intro" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Label  *CatalogLabel  `gorm:"foreignKey:LabelID" json:"label,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogLabelIntro) TableName() string { return "catalog_label_intro" }
