package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// Entity-table conventions (see also constants.go):
//
//   - Primary keys are `bigint GENERATED BY DEFAULT AS IDENTITY` (doc 17 R9:
//     no serial). BY DEFAULT — not ALWAYS — keeps explicit-ID writes possible
//     for merge/unmerge rebuilds and cross-environment moves. Every part of
//     the PK tag is load-bearing (probed live against GORM 1.31 / driver 1.6):
//     `autoIncrement:false` + explicit type, or GORM emits bigserial and
//     ignores the tag; the trailing `PRIMARY KEY` inside the type string
//     makes schema.copyableDataType reject it, or GORM copies the FULL type —
//     identity clause included — onto every association FK column (it also
//     stops CreateTable from emitting a duplicate table-level PK);
//     `default:(-)` marks "DB-generated, no DDL default" so struct Creates
//     omit a zero ID and scan the generated one back via RETURNING.
//   - `<col>_norm` NFKC-folded generated columns are created by the raw-SQL
//     section of cmd/migrate-catalog (AutoMigrate can't express STORED
//     generated columns); the model maps them read-only and excludes them
//     from migration.
//   - field_provenance carries the R8 per-field provenance ARRAY semantics:
//     {"<field>": [{"source": "<source key>", "at": "<ts>"}, ...]} with the
//     latest writer first and history preserved. This step only creates the
//     column; the survivorship engine (import steps) maintains it.
//   - Fields whose zero value is meaningful (kind / link_visibility / ...)
//     are `not null` WITHOUT a gorm default tag: with a default tag GORM
//     omits zero values from INSERTs and the DB default silently wins
//     (the trust_tier lesson of step 02).

// CatalogPerson is the real-world individual behind credit names. It can be
// sparse — identity lives in credit names; person rows exist to group them.
// Person merge is cheap by design: repoint credit_name.person_id, everything
// else (credits, aliases, search) hangs off the names and never moves.
type CatalogPerson struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// PrimaryCreditNameID is the display name of record. Nullable (a person
	// row may exist before its names are sorted out). The FK to
	// catalog_credit_name is added by the raw-SQL section — the two tables
	// reference each other, so the column is created first and the
	// constraint follows once both tables exist.
	PrimaryCreditNameID *int64 `json:"primary_credit_name_id"`
	// DisplayName is the denormalized display fast-path (doc 17 R5); the
	// credit names remain the truth.
	DisplayName string `gorm:"not null" json:"display_name"`
	// Gender uses the Gender* constants; NULL = unknown.
	Gender *int16 `json:"gender"`
	// Fuzzy birth date: three nullable columns, precision self-expressed
	// (doc 17 R9 / MusicBrainz model).
	BirthY          *int16         `json:"birth_y"`
	BirthM          *int16         `json:"birth_m"`
	BirthD          *int16         `json:"birth_d"`
	Description     string         `gorm:"not null;default:''" json:"description"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`
}

func (CatalogPerson) TableName() string { return "catalog_person" }

// CatalogCreditName is a credited identity — a name that appears in credits.
// THE hard invariant of the entity layer (doc 10 invariant 1): credits point
// at credit_name.id, never person.id.
type CatalogCreditName struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// PersonID is NULLABLE: orphan credit names are legal (invariant 2) —
	// record first, attribute later. This dissolves the "must disambiguate
	// before entry" deadlock; orphans feed the match-candidate queue.
	//
	// Note the explicit type on association FKs is documentation only: GORM
	// overwrites it with the referenced PK's type unconditionally — what
	// actually keeps the identity clause off FK columns is the PRIMARY KEY
	// marker in the PK tag (see the conventions comment above).
	PersonID *int64 `gorm:"index;type:bigint" json:"person_id"`
	// Name is the original-script name; NameNorm is its NFKC-folded form
	// (generated column, raw-SQL section).
	Name     string `gorm:"not null" json:"name"`
	NameNorm string `gorm:"->;-:migration" json:"name_norm"`
	// Latin transliteration lives on the same row (doc 17 R5), not as a
	// separate alias row.
	Latin *string `json:"latin"`
	// Lang is BCP-47 (ja / zh-Hans / x-jat ...); '' = unknown.
	Lang string `gorm:"not null;default:''" json:"lang"`
	// Kind uses the CreditNameKind* constants. No default tag: 0 (main) is a
	// meaningful zero and must be written explicitly.
	Kind int16 `gorm:"not null" json:"kind"`
	// LinkVisibility uses the LinkVisibility* constants — see constants.go
	// for the hidden semantics and the R18-defaults-hidden policy note.
	LinkVisibility  int16          `gorm:"not null" json:"link_visibility"`
	Note            string         `gorm:"not null;default:''" json:"note"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	// No soft delete: a credit name's lifecycle is merge/redirect, and
	// revision snapshots keep history.

	Person *CatalogPerson `gorm:"foreignKey:PersonID" json:"person,omitempty"`
}

func (CatalogCreditName) TableName() string { return "catalog_credit_name" }

// CatalogNameAlias is a writing variant of one credit name — same identity,
// different spelling (a different identity is a new credit_name row; total
// uncertainty is an orphan credit_name).
type CatalogNameAlias struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// Lang participates in the uniqueness key, hence NOT NULL DEFAULT ''
	// (a nullable lang would let duplicate (owner, name) rows slip through
	// the unique index).
	CreditNameID int64   `gorm:"not null;type:bigint;uniqueIndex:uq_catalog_name_alias_owner_name_lang" json:"credit_name_id"`
	Name         string  `gorm:"not null;uniqueIndex:uq_catalog_name_alias_owner_name_lang" json:"name"`
	NameNorm     string  `gorm:"->;-:migration" json:"name_norm"`
	Latin        *string `json:"latin"`
	Lang         string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_name_alias_owner_name_lang" json:"lang"`
	// Kind uses the AliasKind* constants; search_hint rows are never displayed.
	Kind               int16 `gorm:"not null" json:"kind"`
	IsPrimaryForLocale bool  `gorm:"not null" json:"is_primary_for_locale"`

	CreditName *CatalogCreditName `gorm:"foreignKey:CreditNameID" json:"credit_name,omitempty"`
}

func (CatalogNameAlias) TableName() string { return "catalog_name_alias" }
