package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type CatalogPerson struct {
	ID                  int64  `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	PrimaryCreditNameID *int64 `json:"primary_credit_name_id"`
	DisplayName         string `gorm:"not null" json:"display_name"`
	Gender              *int16 `json:"gender"`
	BirthY              *int16 `json:"birth_y"`
	BirthM              *int16 `json:"birth_m"`
	BirthD              *int16 `json:"birth_d"`
	// PhotoHash is the person's photograph in the image service (wave 172) —
	// ONE slot, mirroring catalog_label.logo_hash exactly: same content-hash
	// currency as a work cover's image_hash, NOT NULL DEFAULT '' so "" (never
	// NULL) is the "no photo" value, and the consumer builds the CDN URL from
	// it. Filled by internal/jobs/personphotos from the bangumi mirror;
	// provenance lands under field_provenance["photo_hash"].
	//
	// A new image column in catalog scope must ALSO join the registry in
	// internal/platform/catalog/imagerefs, or the bytes are silently
	// collected once the TTL elapses.
	PhotoHash       string         `gorm:"type:text;not null;default:''" json:"photo_hash"`
	Description     string         `gorm:"not null;default:''" json:"description"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`
}

func (CatalogPerson) TableName() string { return "catalog_person" }

type CatalogPersonIntro struct {
	ID         int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	PersonID   int64     `gorm:"not null;uniqueIndex:uq_catalog_person_intro" json:"person_id"`
	Lang       string    `gorm:"not null;default:'';uniqueIndex:uq_catalog_person_intro" json:"lang"`
	Intro      string    `gorm:"type:text;not null" json:"intro"`
	SourceID   int16     `gorm:"not null;uniqueIndex:uq_catalog_person_intro" json:"source_id"`
	Provenance int16     `gorm:"not null" json:"provenance"`
	SrcHash    string    `gorm:"not null;default:''" json:"src_hash"`
	MTModel    string    `gorm:"not null;default:''" json:"mt_model"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`

	Person *CatalogPerson `gorm:"foreignKey:PersonID" json:"person,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogPersonIntro) TableName() string { return "catalog_person_intro" }

type CatalogCreditName struct {
	ID              int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	PersonID        *int64         `gorm:"index;type:bigint" json:"person_id"`
	Name            string         `gorm:"not null" json:"name"`
	NameNorm        string         `gorm:"->;-:migration" json:"name_norm"`
	Latin           *string        `json:"latin"`
	Lang            string         `gorm:"not null;default:''" json:"lang"`
	Kind            int16          `gorm:"not null" json:"kind"`
	LinkVisibility  int16          `gorm:"not null" json:"link_visibility"`
	Note            string         `gorm:"not null;default:''" json:"note"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`

	Person *CatalogPerson `gorm:"foreignKey:PersonID" json:"person,omitempty"`
}

func (CatalogCreditName) TableName() string { return "catalog_credit_name" }

type CatalogNameAlias struct {
	ID                 int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	CreditNameID       int64   `gorm:"not null;type:bigint;uniqueIndex:uq_catalog_name_alias_owner_name_lang" json:"credit_name_id"`
	Name               string  `gorm:"not null;uniqueIndex:uq_catalog_name_alias_owner_name_lang" json:"name"`
	NameNorm           string  `gorm:"->;-:migration" json:"name_norm"`
	Latin              *string `json:"latin"`
	Lang               string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_name_alias_owner_name_lang" json:"lang"`
	Kind               int16   `gorm:"not null" json:"kind"`
	IsPrimaryForLocale bool    `gorm:"not null" json:"is_primary_for_locale"`
	SourceID           *int16  `gorm:"type:smallint" json:"source_id"`
	Provenance         int16   `gorm:"not null" json:"provenance"`
	MTModel            string  `gorm:"not null;default:''" json:"mt_model"`

	CreditName *CatalogCreditName `gorm:"foreignKey:CreditNameID" json:"credit_name,omitempty"`
	Source     *CatalogSource     `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogNameAlias) TableName() string { return "catalog_name_alias" }
