// playtime.go — the first-party playtime lane: what one user reports about one
// work, from one client.
//
// The AGGREGATE side already existed before this table: catalog_work_playtime
// holds one median estimate per (work, source), fed by the vndb and
// erogamescape mirrors. This table is the raw material for a THIRD source row
// on that same table — source `nextmoe` — so nothing downstream learns a new
// shape: a consumer reading `playtimes[]` just starts seeing one more entry
// beside the two it already renders.
//
// What is deliberately NOT here: ownership, a wishlist, a rating, a review.
// Playtime wants to grow into a game library and must not be allowed to until
// the library's own questions (visibility, social surface, rating attribution)
// have answers. One facet, one table.
package model

import "time"

// Playtime report statuses. The wire spells them; the column stores them.
//
// Only Finished feeds the public aggregate — "how long does this take to
// finish" and "how long have I played so far" are different quantities, and
// averaging them together would publish a number that answers neither. The
// other three are still stored, because they are the user's own data and the
// manager that reported them wants them back on the next device.
const (
	PlaytimeStatusPlaying  int16 = 0
	PlaytimeStatusFinished int16 = 1
	PlaytimeStatusDropped  int16 = 2
	PlaytimeStatusOnHold   int16 = 3
)

// PlaytimeMinutesMax is the per-report ceiling, in minutes (1000 hours). It is
// not a statement about how long a visual novel can be — it is the line past
// which "the launcher was left running over a long weekend" is a better
// explanation than "somebody played that much".
const PlaytimeMinutesMax = 60_000

// PlaytimeMinutesMin is the floor for COUNTING a report in the public
// aggregate. Below it the report is still stored and still returned to its
// owner; it just does not get a vote on what the work's playtime is. Opening
// a game and closing it is not evidence about its length.
const PlaytimeMinutesMin = 10

// PlaytimeMinReporters is how many distinct users must have finished a work
// before its aggregate row is published (user 拍板 2026-08-09: 3). Below the
// threshold the row is deleted rather than left stale, so the public face
// never carries a median that one or two people defined.
const PlaytimeMinReporters = 3

// CatalogUserPlaytime is one user's playtime on one work, as reported by one
// OAuth client.
//
// Grain — (actor_uid, work_id, client_id):
//
// The client is part of the key on purpose. Two Galgame managers tracking the
// same user are two independent measurements of the same thing, and neither
// one is authoritative: one may have been installed later, one may only count
// foreground time. Keeping them apart means the server never has to guess
// which report supersedes which, and it makes a misbehaving client removable
// — its rows are identifiable, and the aggregate can exclude a whole client id
// without touching anybody's honest data.
//
// The user's playtime on a work is therefore the MAX across their clients, not
// the sum. Two managers watching one save file are not two playthroughs, and
// summing them would double every number the day a user tries a second
// manager. MAX is monotone, idempotent, and survives a migration between apps
// — the three properties that matter for a value clients re-report forever.
//
// Reports carry the ABSOLUTE total, never a delta: a manager already knows the
// running total locally, and a delta protocol would double-count on every
// retry and lose everything on a reinstall.
type CatalogUserPlaytime struct {
	// Identity PK, the recipe every catalog table uses.
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// ActorUID is the reporting user's global uid, taken from the verified
	// token's `id` claim and never from a request body. 0 is not legal: a
	// playtime is somebody's, the way a vote is (catalog_cover_vote's rule).
	//
	// Every member of both composite indexes below is numbered. Tagging only
	// some members silently reorders the columns, which is how a keyset index
	// ends up unusable for the query it was created for.
	ActorUID int64 `gorm:"column:actor_uid;not null;uniqueIndex:uq_catalog_user_playtime,priority:1;index:idx_catalog_user_playtime_sync,priority:1" json:"actor_uid"`
	// WorkID is the catalog work. A plain indexed bigint rather than a GORM
	// association: declaring one copies the referenced identity PK's full
	// `GENERATED BY DEFAULT AS IDENTITY` type onto this column. The real
	// referential rule is the raw-SQL FK in the migrate package.
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_user_playtime,priority:2;index" json:"work_id"`
	// ClientID is the OAuth client_id the token was issued to — the reporting
	// application's identity, resolved server-side from the token. It is the
	// third key member (see the type doc) and the handle a bad actor is
	// excluded by.
	ClientID string `gorm:"not null;uniqueIndex:uq_catalog_user_playtime,priority:3" json:"client_id"`
	// Minutes is the absolute cumulative playtime this client has observed.
	// NOT NULL with no default: a row without minutes is the absence of a
	// report, and the write path never creates one.
	Minutes int `gorm:"not null" json:"minutes"`
	// Status is one of the PlaytimeStatus* constants. No `default` tag —
	// Playing is 0 and a legal value, and a default would let GORM's
	// zero-value omission hand it to the database to invent.
	Status int16 `gorm:"not null" json:"status"`
	// LastPlayedAt is when the client last saw the game running. Nullable
	// because a manager that only knows a total is a legitimate client; it is
	// the user's data, not an audit column, and updated_at already records
	// when we heard about it.
	LastPlayedAt *time.Time `json:"last_played_at"`
	// Site is the product site of the reporting client when it happens to be
	// bound to one, and "" when it is not. Provenance only, exactly as on
	// catalog_cover_vote — and unlike the catalog write faces, a site binding
	// is NOT required here: a third-party Galgame manager is not a catalog
	// tenant, and demanding one would shut out every caller this face exists
	// for.
	Site string `gorm:"not null;default:''" json:"site"`
	// CreatedAt/UpdatedAt. UpdatedAt carries the sync index (see ActorUID) —
	// `GET /playtime/mine?updated_since=` pages on it.
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `gorm:"index:idx_catalog_user_playtime_sync,priority:2" json:"updated_at"`
}

func (CatalogUserPlaytime) TableName() string { return "catalog_user_playtime" }
