package model

import (
	"time"

	"gorm.io/datatypes"
)

type CatalogExternalRef struct {
	EntityType int16      `gorm:"primaryKey;autoIncrement:false" json:"entity_type"`
	EntityID   int64      `gorm:"primaryKey;autoIncrement:false" json:"entity_id"`
	SourceID   int16      `gorm:"primaryKey;autoIncrement:false;index:idx_catalog_external_ref_source_ext" json:"source_id"`
	ExternalID string     `gorm:"primaryKey;index:idx_catalog_external_ref_source_ext" json:"external_id"`
	LinkKind   int16      `gorm:"not null" json:"link_kind"`
	MatchedBy  string     `gorm:"not null" json:"matched_by"`
	VerifiedBy *int64     `json:"verified_by"`
	VerifiedAt *time.Time `json:"verified_at"`
	CreatedAt  time.Time  `json:"created_at"`
	DeadAt     *time.Time `json:"dead_at"`

	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogExternalRef) TableName() string { return "catalog_external_ref" }

type CatalogMatchRejection struct {
	EntityType int16     `gorm:"primaryKey;autoIncrement:false" json:"entity_type"`
	EntityID   int64     `gorm:"primaryKey;autoIncrement:false" json:"entity_id"`
	SourceID   int16     `gorm:"primaryKey;autoIncrement:false" json:"source_id"`
	ExternalID string    `gorm:"primaryKey" json:"external_id"`
	Reason     string    `gorm:"not null" json:"reason"`
	RejectedBy *int64    `json:"rejected_by"`
	RejectedAt time.Time `gorm:"not null;autoCreateTime;default:now()" json:"rejected_at"`
}

func (CatalogMatchRejection) TableName() string { return "catalog_match_rejection" }

type CatalogMatchCandidate struct {
	EntityType int16      `gorm:"primaryKey;autoIncrement:false;index:idx_catalog_match_candidate_queue,priority:2" json:"entity_type"`
	AID        int64      `gorm:"primaryKey;autoIncrement:false" json:"a_id"`
	BID        int64      `gorm:"primaryKey;autoIncrement:false" json:"b_id"`
	Reason     int16      `gorm:"not null" json:"reason"`
	Score      *float32   `json:"score"`
	Status     int16      `gorm:"not null;index:idx_catalog_match_candidate_queue,priority:1" json:"status"`
	CreatedAt  time.Time  `json:"created_at"`
	DecidedBy  *int64     `json:"decided_by"`
	DecidedAt  *time.Time `json:"decided_at"`
}

func (CatalogMatchCandidate) TableName() string { return "catalog_match_candidate" }

type CatalogMergeProposal struct {
	ID              int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	EntityType      int16          `gorm:"not null;index:idx_catalog_merge_proposal_queue,priority:2" json:"entity_type"`
	SourceEntityID  int64          `gorm:"not null" json:"source_entity_id"`
	TargetEntityID  int64          `gorm:"not null" json:"target_entity_id"`
	Status          int16          `gorm:"not null;index:idx_catalog_merge_proposal_queue,priority:1" json:"status"`
	FieldResolution datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_resolution"`
	ProposedBy      int64          `gorm:"not null" json:"proposed_by"`
	ProposedAt      time.Time      `gorm:"not null;autoCreateTime" json:"proposed_at"`
	ExecuteAfter    *time.Time     `json:"execute_after"`
	ExecutedAt      *time.Time     `json:"executed_at"`
	Note            string         `gorm:"not null;default:''" json:"note"`
}

func (CatalogMergeProposal) TableName() string { return "catalog_merge_proposal" }

type CatalogSurvivorshipRule struct {
	EntityType int16  `gorm:"primaryKey;autoIncrement:false" json:"entity_type"`
	Field      string `gorm:"primaryKey" json:"field"`
	SourceID   int16  `gorm:"primaryKey;autoIncrement:false" json:"source_id"`
	Priority   int16  `gorm:"not null" json:"priority"`

	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogSurvivorshipRule) TableName() string { return "catalog_survivorship_rule" }
