package model

import "time"

type CatalogWorkRelation struct {
	AWorkID        int64     `gorm:"primaryKey;autoIncrement:false" json:"a_work_id"`
	BWorkID        int64     `gorm:"primaryKey;autoIncrement:false;index" json:"b_work_id"`
	RelationTypeID int64     `gorm:"primaryKey;autoIncrement:false" json:"relation_type_id"`
	Note           string    `gorm:"not null;default:''" json:"note"`
	SourceID       *int16    `json:"source_id"`
	CreatedAt      time.Time `json:"created_at"`

	AWork        *CatalogWork         `gorm:"foreignKey:AWorkID" json:"a_work,omitempty"`
	BWork        *CatalogWork         `gorm:"foreignKey:BWorkID" json:"b_work,omitempty"`
	RelationType *CatalogRelationType `gorm:"foreignKey:RelationTypeID" json:"relation_type,omitempty"`
	Source       *CatalogSource       `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkRelation) TableName() string { return "catalog_work_relation" }

type CatalogEntityRelation struct {
	EntityType     int16     `gorm:"primaryKey;autoIncrement:false;index:idx_catalog_entity_relation_reverse" json:"entity_type"`
	AID            int64     `gorm:"primaryKey;autoIncrement:false" json:"a_id"`
	BID            int64     `gorm:"primaryKey;autoIncrement:false;index:idx_catalog_entity_relation_reverse" json:"b_id"`
	RelationTypeID int64     `gorm:"primaryKey;autoIncrement:false" json:"relation_type_id"`
	Note           string    `gorm:"not null;default:''" json:"note"`
	CreatedAt      time.Time `json:"created_at"`

	RelationType *CatalogRelationType `gorm:"foreignKey:RelationTypeID" json:"relation_type,omitempty"`
}

func (CatalogEntityRelation) TableName() string { return "catalog_entity_relation" }

type CatalogWorkLabel struct {
	WorkID    int64     `gorm:"primaryKey;autoIncrement:false" json:"work_id"`
	LabelID   int64     `gorm:"primaryKey;autoIncrement:false;index" json:"label_id"`
	Kind      int16     `gorm:"primaryKey;autoIncrement:false" json:"kind"`
	SourceID  *int16    `json:"source_id"`
	CreatedAt time.Time `json:"created_at"`

	Work  *CatalogWork  `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Label *CatalogLabel `gorm:"foreignKey:LabelID" json:"label,omitempty"`
}

func (CatalogWorkLabel) TableName() string { return "catalog_work_label" }

type CatalogReleaseLabel struct {
	ReleaseID int64     `gorm:"primaryKey;autoIncrement:false" json:"release_id"`
	LabelID   int64     `gorm:"primaryKey;autoIncrement:false;index" json:"label_id"`
	Kind      int16     `gorm:"primaryKey;autoIncrement:false" json:"kind"`
	SourceID  *int16    `json:"source_id"`
	CreatedAt time.Time `json:"created_at"`

	Release *CatalogRelease `gorm:"foreignKey:ReleaseID" json:"release,omitempty"`
	Label   *CatalogLabel   `gorm:"foreignKey:LabelID" json:"label,omitempty"`
}

func (CatalogReleaseLabel) TableName() string { return "catalog_release_label" }

type CatalogWorkCharacter struct {
	ID          int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID      int64     `gorm:"not null;uniqueIndex:uq_catalog_work_character" json:"work_id"`
	CharacterID int64     `gorm:"not null;index;uniqueIndex:uq_catalog_work_character" json:"character_id"`
	Kind        int16     `gorm:"not null" json:"kind"`
	Spoiler     int16     `gorm:"not null" json:"spoiler"`
	MatchedBy   string    `gorm:"not null" json:"matched_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`

	Work      *CatalogWork      `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Character *CatalogCharacter `gorm:"foreignKey:CharacterID" json:"character,omitempty"`
}

func (CatalogWorkCharacter) TableName() string { return "catalog_work_character" }
