package model

import (
	"time"

	"gorm.io/datatypes"
)

type CatalogWorkRelation struct {
	AWorkID        int64     `gorm:"primaryKey;autoIncrement:false" json:"a_work_id"`
	BWorkID        int64     `gorm:"primaryKey;autoIncrement:false;index" json:"b_work_id"`
	RelationTypeID int64     `gorm:"primaryKey;autoIncrement:false" json:"relation_type_id"`
	Note           string    `gorm:"not null;default:''" json:"note"`
	SourceID       *int16    `json:"source_id"`
	CreatedAt      time.Time `json:"created_at"`

	AWork        *CatalogWork         `gorm:"foreignKey:AWorkID" json:"a_work,omitempty"`
	BWork        *CatalogWork         `gorm:"foreignKey:BWorkID" json:"b_work,omitempty"`
	RelationType *CatalogRelationType `gorm:"foreignKey:RelationTypeID" json:"relation_type,omitempty"`
	Source       *CatalogSource       `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkRelation) TableName() string { return "catalog_work_relation" }

type CatalogEntityRelation struct {
	EntityType     int16     `gorm:"primaryKey;autoIncrement:false;index:idx_catalog_entity_relation_reverse" json:"entity_type"`
	AID            int64     `gorm:"primaryKey;autoIncrement:false" json:"a_id"`
	BID            int64     `gorm:"primaryKey;autoIncrement:false;index:idx_catalog_entity_relation_reverse" json:"b_id"`
	RelationTypeID int64     `gorm:"primaryKey;autoIncrement:false" json:"relation_type_id"`
	Note           string    `gorm:"not null;default:''" json:"note"`
	CreatedAt      time.Time `json:"created_at"`

	RelationType *CatalogRelationType `gorm:"foreignKey:RelationTypeID" json:"relation_type,omitempty"`
}

func (CatalogEntityRelation) TableName() string { return "catalog_entity_relation" }

type CatalogWorkLabel struct {
	WorkID    int64     `gorm:"primaryKey;autoIncrement:false" json:"work_id"`
	LabelID   int64     `gorm:"primaryKey;autoIncrement:false;index" json:"label_id"`
	Kind      int16     `gorm:"primaryKey;autoIncrement:false" json:"kind"`
	SourceID  *int16    `json:"source_id"`
	CreatedAt time.Time `json:"created_at"`

	Work  *CatalogWork  `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Label *CatalogLabel `gorm:"foreignKey:LabelID" json:"label,omitempty"`
}

func (CatalogWorkLabel) TableName() string { return "catalog_work_label" }

type CatalogReleaseLabel struct {
	ReleaseID int64     `gorm:"primaryKey;autoIncrement:false" json:"release_id"`
	LabelID   int64     `gorm:"primaryKey;autoIncrement:false;index" json:"label_id"`
	Kind      int16     `gorm:"primaryKey;autoIncrement:false" json:"kind"`
	SourceID  *int16    `json:"source_id"`
	CreatedAt time.Time `json:"created_at"`

	Release *CatalogRelease `gorm:"foreignKey:ReleaseID" json:"release,omitempty"`
	Label   *CatalogLabel   `gorm:"foreignKey:LabelID" json:"label,omitempty"`
}

func (CatalogReleaseLabel) TableName() string { return "catalog_release_label" }

type CatalogWorkCharacter struct {
	ID          int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID      int64 `gorm:"not null;uniqueIndex:uq_catalog_work_character" json:"work_id"`
	CharacterID int64 `gorm:"not null;index;uniqueIndex:uq_catalog_work_character" json:"character_id"`
	Kind        int16 `gorm:"not null" json:"kind"`
	Spoiler     int16 `gorm:"not null" json:"spoiler"`
	// MatchedBy records which importer INSERTed this row, not who wrote the kind
	// and spoiler it carries now. uq_catalog_work_character holds one row per
	// (work, character) and the importers only ON CONFLICT DO NOTHING, so merge
	// survivorship writes the values of whichever source got there second:
	// production holds 7,617 rows tagged import:character-roster-eg with a
	// non-zero kind (the EG importer only ever writes 0) and 29 tagged bangumi
	// with a non-zero spoiler (that importer only ever writes 0). Attribution of
	// a column is answered by FieldProvenance, never by this string.
	MatchedBy       string         `gorm:"not null" json:"matched_by"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`

	Work      *CatalogWork      `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Character *CatalogCharacter `gorm:"foreignKey:CharacterID" json:"character,omitempty"`
}

func (CatalogWorkCharacter) TableName() string { return "catalog_work_character" }
