package model

import "time"

// CatalogSeriesIntro is a series' multilingual description body, one row per
// (series, language, source) — the exact shape of CatalogLabelIntro /
// CatalogTagIntro (refs/proj/83 E2b). It lands with the data-layer-retirement
// wave (refs/plans/10 charter ruling 3): the wiki galgame_series.description rows
// are hand-written user content with no upstream to regenerate them from, so
// the ones whose series could be resolved onto a canonical catalog_series are
// rescued here before the wiki table family is dropped.
//
// The entity rows themselves (CatalogSeries / CatalogSeriesMember, step 94)
// live in work.go, next to the work graph they group; only the intro facet
// lives here.
//
// source_id is row-level provenance — NOT NULL with NO default: a meaningful
// source is always known at write time, and a default tag would drop a
// legitimately-low source id from the INSERT (the default-tag zero-value trap).
type CatalogSeriesIntro struct {
	ID       int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	SeriesID int64 `gorm:"not null;uniqueIndex:uq_catalog_series_intro" json:"series_id"`
	// Lang is BCP-47 and part of the uniqueness key, hence NOT NULL DEFAULT ''
	// (same rationale as catalog_label_intro / the alias tables).
	Lang string `gorm:"not null;default:'';uniqueIndex:uq_catalog_series_intro" json:"lang"`
	// Intro is the body text, verbatim from the source. NOT NULL, no default.
	Intro string `gorm:"type:text;not null" json:"intro"`
	// SourceID is the provenance FK. Part of the unique key.
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_series_intro" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Series *CatalogSeries `gorm:"foreignKey:SeriesID" json:"series,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogSeriesIntro) TableName() string { return "catalog_series_intro" }

// CatalogSeriesNameOverride is a reviewed display name for a series in a
// machine-owned lane (wave 185; today only `derived`, source 18). The derived
// builder is its lane's ONLY writer and recomputes display_name every pass, so
// a better-than-mechanical name cannot live on catalog_series itself — the next
// pass would stomp it. It lives here instead, keyed by the series' source
// identity, and the builder consults it: when a row exists AND its MemberHash
// still matches the component's current member set, the override wins over the
// prefix/fallback rule.
//
// The hash is the expiry mechanism. A derived component that gains or loses a
// member is a different grouping, so a name reviewed against the old membership
// is stale evidence — the builder ignores (and on apply, deletes) the row and
// falls back to the mechanical name until a new override is reviewed in. This
// keeps the reaper's contract intact: every byte the lane publishes is either
// derived from current data or validated against it, never remembered past it.
type CatalogSeriesNameOverride struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// SourceID + ExternalID address the series the same way the lane's builder
	// does — NOT the catalog_series row id, which the reaper deletes and
	// recreates as the graph moves. UNIQUE: one override per series identity.
	SourceID   int16  `gorm:"not null;uniqueIndex:uq_catalog_series_name_override,priority:1" json:"source_id"`
	ExternalID string `gorm:"not null;uniqueIndex:uq_catalog_series_name_override,priority:2" json:"external_id"`
	// MemberHash is sha256 (hex) over the sorted member work ids joined by
	// commas — the membership snapshot the name was reviewed against.
	MemberHash string `gorm:"not null" json:"member_hash"`
	// DisplayName is the reviewed name. NOT NULL, no default: an empty override
	// is not a thing.
	DisplayName string `gorm:"not null" json:"display_name"`
	// ReviewedBy records provenance of the review (a model name, a wave tag) —
	// free text, informational only.
	ReviewedBy string    `gorm:"not null;default:''" json:"reviewed_by"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (CatalogSeriesNameOverride) TableName() string { return "catalog_series_name_override" }
