package model

import "time"

// CatalogSeriesIntro is a series' multilingual description body, one row per
// (series, language, source) — the exact shape of CatalogLabelIntro /
// CatalogTagIntro (refs/proj/83 E2b). It lands with the data-layer-retirement
// wave (refs/plans/10 charter ruling 3): the wiki galgame_series.description rows
// are hand-written user content with no upstream to regenerate them from, so
// the ones whose series could be resolved onto a canonical catalog_series are
// rescued here before the wiki table family is dropped.
//
// The entity rows themselves (CatalogSeries / CatalogSeriesMember, step 94)
// live in work.go, next to the work graph they group; only the intro facet
// lives here.
//
// source_id is row-level provenance — NOT NULL with NO default: a meaningful
// source is always known at write time, and a default tag would drop a
// legitimately-low source id from the INSERT (the default-tag zero-value trap).
type CatalogSeriesIntro struct {
	ID       int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	SeriesID int64 `gorm:"not null;uniqueIndex:uq_catalog_series_intro" json:"series_id"`
	// Lang is BCP-47 and part of the uniqueness key, hence NOT NULL DEFAULT ''
	// (same rationale as catalog_label_intro / the alias tables).
	Lang string `gorm:"not null;default:'';uniqueIndex:uq_catalog_series_intro" json:"lang"`
	// Intro is the body text, verbatim from the source. NOT NULL, no default.
	Intro string `gorm:"type:text;not null" json:"intro"`
	// SourceID is the provenance FK. Part of the unique key.
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_series_intro" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Series *CatalogSeries `gorm:"foreignKey:SeriesID" json:"series,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogSeriesIntro) TableName() string { return "catalog_series_intro" }
