package model

import "time"

type CatalogSeriesIntro struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	SeriesID  int64     `gorm:"not null;uniqueIndex:uq_catalog_series_intro" json:"series_id"`
	Lang      string    `gorm:"not null;default:'';uniqueIndex:uq_catalog_series_intro" json:"lang"`
	Intro     string    `gorm:"type:text;not null" json:"intro"`
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_series_intro" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Series *CatalogSeries `gorm:"foreignKey:SeriesID" json:"series,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogSeriesIntro) TableName() string { return "catalog_series_intro" }

type CatalogSeriesNameOverride struct {
	ID          int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	SourceID    int16     `gorm:"not null;uniqueIndex:uq_catalog_series_name_override,priority:1" json:"source_id"`
	ExternalID  string    `gorm:"not null;uniqueIndex:uq_catalog_series_name_override,priority:2" json:"external_id"`
	MemberHash  string    `gorm:"not null" json:"member_hash"`
	DisplayName string    `gorm:"not null" json:"display_name"`
	ReviewedBy  string    `gorm:"not null;default:''" json:"reviewed_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (CatalogSeriesNameOverride) TableName() string { return "catalog_series_name_override" }
