package model

import "time"

// Tag TIER — the display layer of the canonical tag vocabulary (doc 70 §1,
// step 74). It drives the "取精华去糟粕" render policy: core shows by default,
// longtail folds, hidden is never shown. 0 (core) is a MEANINGFUL zero, so the
// column is NOT NULL with NO default tag — a default tag would drop a
// legitimately-core row's tier from the INSERT and the DB default would silently
// promote it (the default-tag zero-value trap).
const (
	TagTierCore     int16 = 0 // cross-source ≥2 (this wave) or high single-source usage (70b)
	TagTierLongtail int16 = 1 // low-usage single-source; folded by default (70b)
	TagTierHidden   int16 = 2 // junk/meta kept for mapping but never shown (70b)
)

// Tag KIND — content description vs platform meta (doc 70 §1, step 74). Meta
// (PC/R18/同人/像素…) stays OUT of the content-tag cloud but can drive an
// attribute-filter facet. 0 (content) is a MEANINGFUL zero → NOT NULL, no
// default tag (same trap as tier).
const (
	TagKindContent int16 = 0
	TagKindMeta    int16 = 1
)

// CatalogTag is one canonical tag in the cross-source vocabulary (doc 70 §1,
// step 74 — the DETERMINISTIC slice). It sits ABOVE the original per-source tag
// layers (galgame_tag for vndb, catalog_work_tag for bangumi/dlsite), which
// stay untouched: this is the convergence layer the read face projects
// tier/kind through, never a replacement. Rows are minted only for cross-source
// exact-name groups this wave (single-source canonical + LLM-proposed
// convergence = 70b); id is a SERVICE-owned identity (not a seed-owned registry
// value — this vocabulary is DERIVED from the source data, not hand-curated, so
// ids need not be identical across environments).
type CatalogTag struct {
	// id is the identity PK (the three-part recipe: autoIncrement:false +
	// explicit GENERATED-BY-DEFAULT type + default:(-)).
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// Name is the canonical display form — the shared original string the group
	// converged on (the write tool's deterministic pick). UNIQUE: one canonical
	// row per name, and the tool's ON CONFLICT (name) key.
	Name string `gorm:"type:text;not null;uniqueIndex" json:"name"`
	// Tier uses the TagTier* constants (0=core is meaningful → NOT NULL, no default).
	Tier int16 `gorm:"not null" json:"tier"`
	// Kind uses the TagKind* constants (0=content is meaningful → NOT NULL, no default).
	Kind      int16     `gorm:"not null" json:"kind"`
	Note      string    `gorm:"type:text;not null;default:''" json:"note"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (CatalogTag) TableName() string { return "catalog_tag" }

// CatalogTagSourceMap maps one source-native tag name onto the canonical
// vocabulary (many-to-one) — the CatalogSourceRoleMap composite-PK precedent
// (source_id + source-defined text). SourceName is the per-source key exactly
// as the read face sees it:
//
//   - vndb (source_id=2): galgame_tag.name (the localized display name kungal
//     renders — an unmapped VNDB tag keeps its English name, a user tag its
//     typed text);
//   - bangumi (3) / dlsite (4): catalog_work_tag.name (verbatim folksonomy /
//     official genre).
//
// So the read face's batch lookup is keyed EXACTLY (source_id, source_name),
// and a bridged claimed vndb tag (source_id=2, name=galgame_tag.name) hits the
// same key as a bodyless vndb tag would. tag_id is a plain int64 FK (the
// identity-PK type-copy trap only fires when the FK column omits an explicit
// type — here it stays bigint).
type CatalogTagSourceMap struct {
	SourceID   int16  `gorm:"primaryKey;autoIncrement:false" json:"source_id"`
	SourceName string `gorm:"primaryKey" json:"source_name"`
	TagID      int64  `gorm:"not null;index" json:"tag_id"`
	Note       string `gorm:"not null;default:''" json:"note"`

	Tag *CatalogTag `gorm:"foreignKey:TagID" json:"tag,omitempty"`
}

func (CatalogTagSourceMap) TableName() string { return "catalog_tag_source_map" }

// CatalogTagIntro is a canonical tag's multilingual description body, one row
// per (tag, language, source) — the exact shape of CatalogLabelIntro
// (refs/proj/83 E2b). It lands with the data-layer-retirement wave
// (refs/plans/10 charter 拍板 3): the wiki galgame_tag.description rows are
// hand-written user content with no upstream to regenerate them from, so the
// ones whose tag converged onto the canonical vocabulary are rescued here
// before the wiki table family is dropped.
//
// The unique key lets several sources coexist for the same language; the read
// face merges them per language (source_id ascending wins), like the
// work/person/character/label intro merge. This table describes the CANONICAL
// tag only — it never mints catalog_tag rows, which stay owned by the doc 70
// vocabulary pipeline.
//
// source_id is row-level provenance — NOT NULL with NO default: a meaningful
// source is always known at write time, and a default tag would drop a
// legitimately-low source id from the INSERT (the default-tag zero-value trap).
type CatalogTagIntro struct {
	ID    int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	TagID int64 `gorm:"not null;uniqueIndex:uq_catalog_tag_intro" json:"tag_id"`
	// Lang is BCP-47 and part of the uniqueness key, hence NOT NULL DEFAULT ''
	// (same rationale as catalog_label_intro / the alias tables).
	Lang string `gorm:"not null;default:'';uniqueIndex:uq_catalog_tag_intro" json:"lang"`
	// Intro is the body text, verbatim from the source. NOT NULL, no default.
	Intro string `gorm:"type:text;not null" json:"intro"`
	// SourceID is the provenance FK. Part of the unique key.
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_tag_intro" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Tag    *CatalogTag    `gorm:"foreignKey:TagID" json:"tag,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogTagIntro) TableName() string { return "catalog_tag_intro" }
