package model

import "time"

const (
	TagTierCore     int16 = 0
	TagTierLongtail int16 = 1
	TagTierHidden   int16 = 2
)

const (
	TagKindContent int16 = 0
	TagKindMeta    int16 = 1
)

type CatalogTag struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Name      string    `gorm:"type:text;not null;uniqueIndex" json:"name"`
	Tier      int16     `gorm:"not null" json:"tier"`
	Kind      int16     `gorm:"not null" json:"kind"`
	Sexual    bool      `gorm:"not null" json:"sexual"`
	Note      string    `gorm:"type:text;not null;default:''" json:"note"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (CatalogTag) TableName() string { return "catalog_tag" }

type CatalogTagSourceMap struct {
	SourceID   int16  `gorm:"primaryKey;autoIncrement:false" json:"source_id"`
	SourceName string `gorm:"primaryKey" json:"source_name"`
	TagID      int64  `gorm:"not null;index" json:"tag_id"`
	Note       string `gorm:"not null;default:''" json:"note"`

	Tag *CatalogTag `gorm:"foreignKey:TagID" json:"tag,omitempty"`
}

func (CatalogTagSourceMap) TableName() string { return "catalog_tag_source_map" }

// CatalogTagRejection is negative knowledge for the tag vocabulary: a source
// name a review wave decided must NOT enter catalog_tag (person names, company
// nicknames, subjective slang…). Without it every propose re-surfaces the same
// rejected names — the catalog_match_rejection lesson, tag-shaped (wave 208).
type CatalogTagRejection struct {
	SourceID   int16     `gorm:"primaryKey;autoIncrement:false" json:"source_id"`
	SourceName string    `gorm:"primaryKey" json:"source_name"`
	Reason     string    `gorm:"not null" json:"reason"`
	RejectedBy string    `gorm:"not null;default:''" json:"rejected_by"`
	RejectedAt time.Time `gorm:"not null;autoCreateTime;default:now()" json:"rejected_at"`
}

func (CatalogTagRejection) TableName() string { return "catalog_tag_rejection" }

type CatalogTagIntro struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	TagID     int64     `gorm:"not null;uniqueIndex:uq_catalog_tag_intro" json:"tag_id"`
	Lang      string    `gorm:"not null;default:'';uniqueIndex:uq_catalog_tag_intro" json:"lang"`
	Intro     string    `gorm:"type:text;not null" json:"intro"`
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_tag_intro" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Tag    *CatalogTag    `gorm:"foreignKey:TagID" json:"tag,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogTagIntro) TableName() string { return "catalog_tag_intro" }
