package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// CatalogWork is the work registry row (doc 17 R2): ONE global ID space for
// every medium (no per-type ID blocks — the TMDB collision tax). It is the
// identity + graph anchor; the work BODY always lives in a product database.
//
// Claiming: site + product_work_id are BOTH NULL for an unclaimed row (DLsite
// voice works, Bangumi anime/manga subjects — data that predates its
// product); claiming is one UPDATE filling both. Claim semantics (service
// side, step 05 + ingestion): a product creating a work FIRST looks up an
// existing row by (medium, external anchors) and claims it — a claim must
// never mint a second identity. Unclaimed-row hygiene (OpenLibrary lesson):
// rows without an external_ref anchor and below the metadata bar can only be
// status=stub and stay out of public aggregation.
type CatalogWork struct {
	ID       int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	MediumID int16 `gorm:"not null;uniqueIndex:uq_catalog_work_claim;index:idx_catalog_work_medium_status,priority:1" json:"medium_id"`
	// The claim unique treats NULLs as distinct (PG semantics): unclaimed
	// rows coexist freely, while a claimed (medium, site, product_work_id)
	// triple is globally unique — exactly the wanted rule.
	Site          *string `gorm:"uniqueIndex:uq_catalog_work_claim" json:"site"`
	ProductWorkID *int64  `gorm:"uniqueIndex:uq_catalog_work_claim" json:"product_work_id"`
	// OLang is the original language (BCP-47); it decides which title row is
	// primary (VNDB model). Write paths default it to 'ja' explicitly — no
	// DB default on purpose.
	OLang string `gorm:"column:olang;not null" json:"olang"`
	// DisplayName is the denormalized display fast-path; titles are truth.
	DisplayName string `gorm:"not null" json:"display_name"`
	// ContentRating uses the ContentRating* constants.
	ContentRating int16 `gorm:"not null" json:"content_rating"`
	// Status uses the WorkStatus* constants.
	Status int16 `gorm:"not null;index:idx_catalog_work_medium_status,priority:2" json:"status"`
	// Extra is the governed escape hatch (doc 17 R9): object-only + 64KB cap
	// (CHECKs in the raw-SQL section). Rule: a key that gets queried
	// regularly must be promoted to a real column — extra is a buffer, not a
	// home.
	Extra           datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"extra"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`

	Medium *CatalogMedium `gorm:"foreignKey:MediumID" json:"medium,omitempty"`
}

func (CatalogWork) TableName() string { return "catalog_work" }

// CatalogWorkTitle is one title row per language/kind (doc 17 R2/R5):
// romaji/latin lives on the row, NOT as a separate row (VNDB v3 shape).
type CatalogWorkTitle struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_title" json:"work_id"`
	// Lang is BCP-47 and part of the uniqueness key, hence NOT NULL
	// DEFAULT '' (same rationale as the alias tables).
	Lang      string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_work_title" json:"lang"`
	Title     string  `gorm:"not null;uniqueIndex:uq_catalog_work_title" json:"title"`
	TitleNorm string  `gorm:"->;-:migration" json:"title_norm"`
	Latin     *string `json:"latin"`
	// Kind uses the WorkTitleKind* constants.
	Kind int16 `gorm:"not null;uniqueIndex:uq_catalog_work_title" json:"kind"`

	Work *CatalogWork `gorm:"foreignKey:WorkID" json:"work,omitempty"`
}

func (CatalogWorkTitle) TableName() string { return "catalog_work_title" }

// CatalogRelease is the SKU/edition anchor point (doc 17 R3), REGISTRY-grade:
// identity + date + platform + the anchor external refs hang off when an
// external ID is SKU-natured (DLsite workno, VNDB release, store pages).
// It is NOT a merchandise/file model — prices stay in staging, file trees
// are content-grade and never enter catalog. Built day-1 because adding the
// layer later is the most expensive direction (Discogs lesson); per-medium
// use is optional.
type CatalogRelease struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;index" json:"work_id"`
	// Kind uses the ReleaseKind* constants.
	Kind     int16   `gorm:"not null" json:"kind"`
	Title    *string `json:"title"`
	Lang     *string `json:"lang"`
	Platform *string `json:"platform"`
	// Fuzzy release date (three nullable columns, doc 17 R9).
	ReleasedY *int16 `json:"released_y"`
	ReleasedM *int16 `json:"released_m"`
	ReleasedD *int16 `json:"released_d"`
	// EventID is the doujin-convention slot reserved day-1 (every doujin
	// precedent hangs the event off the release). Deliberately NO FK: the
	// event table is built when real convention data arrives (doc 17 §9).
	EventID *int64 `json:"event_id"`
	// Extra: governed escape hatch, same CHECKs as catalog_work.
	Extra     datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"extra"`
	CreatedAt time.Time      `json:"created_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`

	Work *CatalogWork `gorm:"foreignKey:WorkID" json:"work,omitempty"`
}

func (CatalogRelease) TableName() string { return "catalog_release" }
