package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// CatalogWork is the work registry row (doc 17 R2): ONE global ID space for
// every medium (no per-type ID blocks — the TMDB collision tax). It is the
// identity + graph anchor; the work BODY always lives in a product database.
//
// Claiming: site + product_work_id are BOTH NULL for an unclaimed row (DLsite
// voice works, Bangumi anime/manga subjects — data that predates its
// product); claiming is one UPDATE filling both. Claim semantics (service
// side, step 05 + ingestion): a product creating a work FIRST looks up an
// existing row by (medium, external anchors) and claims it — a claim must
// never mint a second identity. Unclaimed-row hygiene (OpenLibrary lesson):
// rows without an external_ref anchor and below the metadata bar can only be
// status=stub and stay out of public aggregation.
type CatalogWork struct {
	ID       int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	MediumID int16 `gorm:"not null;uniqueIndex:uq_catalog_work_claim;index:idx_catalog_work_medium_status,priority:1" json:"medium_id"`
	// The claim unique treats NULLs as distinct (PG semantics): unclaimed
	// rows coexist freely, while a claimed (medium, site, product_work_id)
	// triple is globally unique — exactly the wanted rule.
	Site          *string `gorm:"uniqueIndex:uq_catalog_work_claim" json:"site"`
	ProductWorkID *int64  `gorm:"uniqueIndex:uq_catalog_work_claim" json:"product_work_id"`
	// ClaimState is the claim's VISIBILITY on the owning product face
	// (ClaimState* constants — a catalog-owned vocabulary, never a product's
	// status machine). NULLABLE by design, three-valued:
	//
	//   - NULL on every UNCLAIMED row (no claim, no state) — the ONLY correct
	//     value there, and what ClaimWork writes;
	//   - NULL on a claimed row whose state has not been projected yet (right
	//     after the migration, before the first reconcile pass); the read face
	//     renders that as `live`, which is exactly the pre-R7 behavior, and the
	//     reconciler converges it on its next run;
	//   - 0/1/2 once a projector has run.
	//
	// Maintained by the claim reconciler (internal/platform/galgame/catalogsync
	// for the wiki; a future claimer projects its own lifecycle the same way).
	// A claimer with no draft/hidden concept simply leaves every claim live.
	// No `default:` tag: live is a meaningful zero (see the constants).
	ClaimState *int16 `gorm:"column:claim_state" json:"claim_state"`
	// OLang is the original language (BCP-47); it decides which title row is
	// primary (VNDB model). Write paths default it to 'ja' explicitly — no
	// DB default on purpose.
	OLang string `gorm:"column:olang;not null" json:"olang"`
	// DisplayName is the denormalized display fast-path; titles are truth.
	DisplayName string `gorm:"not null" json:"display_name"`
	// ContentRating uses the ContentRating* constants.
	ContentRating int16 `gorm:"not null" json:"content_rating"`
	// Status uses the WorkStatus* constants.
	Status int16 `gorm:"not null;index:idx_catalog_work_medium_status,priority:2" json:"status"`
	// Extra is the governed escape hatch (doc 17 R9): object-only + 64KB cap
	// (CHECKs in the raw-SQL section). Rule: a key that gets queried
	// regularly must be promoted to a real column — extra is a buffer, not a
	// home.
	Extra           datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"extra"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`

	Medium *CatalogMedium `gorm:"foreignKey:MediumID" json:"medium,omitempty"`
}

func (CatalogWork) TableName() string { return "catalog_work" }

// CatalogWorkTitle is one title row per language/kind (doc 17 R2/R5):
// romaji/latin lives on the row, NOT as a separate row (VNDB v3 shape).
type CatalogWorkTitle struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_title" json:"work_id"`
	// Lang is BCP-47 and part of the uniqueness key, hence NOT NULL
	// DEFAULT '' (same rationale as the alias tables).
	Lang      string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_work_title" json:"lang"`
	Title     string  `gorm:"not null;uniqueIndex:uq_catalog_work_title" json:"title"`
	TitleNorm string  `gorm:"->;-:migration" json:"title_norm"`
	Latin     *string `json:"latin"`
	// Kind uses the WorkTitleKind* constants.
	Kind int16 `gorm:"not null;uniqueIndex:uq_catalog_work_title" json:"kind"`

	Work *CatalogWork `gorm:"foreignKey:WorkID" json:"work,omitempty"`
}

func (CatalogWorkTitle) TableName() string { return "catalog_work_title" }

// CatalogWorkIntro is one multilingual intro/description row for a BODYLESS
// work (site=” — no product database to hold its body), the media-aggregation
// pilot's first native media table (refs/proj/51 §3, step 52). It mirrors the
// catalog_work_title shape so the read face can merge it with the CLAIMED
// bridge (a claimed galgame_wiki work reads its intro directly from
// galgame.intro_* — a column→row pivot — and NEVER writes a row here:
// bridge-not-copy, §2). One row per (work, language, source): the unique key
// lets several sources coexist for the same language, and the read face merges
// them per language (source_id ascending wins).
//
// source_id is row-level provenance (§8.C) — NOT NULL with NO default: a
// meaningful source is always known at write time, and the default tag would
// drop a legitimately-low source id from the INSERT (the default-tag zero-value
// trap). shadow-never-delete (§8.B): a bodyless work later claimed keeps its
// rows (claim is reversible); the read face's strict XOR just stops reading
// them.
type CatalogWorkIntro struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_intro" json:"work_id"`
	// Lang is BCP-47 and part of the uniqueness key, hence NOT NULL DEFAULT ''
	// (same rationale as catalog_work_title / the alias tables).
	Lang string `gorm:"not null;default:'';uniqueIndex:uq_catalog_work_intro" json:"lang"`
	// Intro is the body text (verbatim from the source in this pilot — no
	// cleaning; §5). NOT NULL, no default: content is always supplied.
	Intro string `gorm:"type:text;not null" json:"intro"`
	// SourceID is the provenance FK (see the type doc). Part of the unique key.
	// A MACHINE-translated row (Provenance=1, step 75) carries the SOURCE row's
	// source_id — attribution is "translated from that source" — and is told
	// apart from the source row purely by Provenance, NOT by a distinct
	// source_id (so it never widens the unique key).
	SourceID int16 `gorm:"not null;uniqueIndex:uq_catalog_work_intro" json:"source_id"`
	// Provenance is 0=source (upstream original text) / 1=machine (LLM machine
	// translation — the step-75 ja→zh-Hans pilot). A meaningful zero value, so
	// the column is NOT NULL with NO default tag (the default-tag zero-value
	// trap): a source row records 0 EXPLICITLY on INSERT, never has the DB
	// default it. Machine rows NEVER masquerade as source data — the read face
	// prefers the source row for a language whenever both coexist.
	Provenance int16 `gorm:"not null" json:"provenance"`
	// SrcHash is sha256(source ja text) for a machine row — the re-translate
	// trigger: when the source text changes, its hash changes and the machine
	// row is re-translated (upsert). Empty on source rows. NOT NULL DEFAULT ''
	// (the lang/alias pattern: '' is the genuine not-applicable value here, safe
	// to default — unlike Provenance's meaningful 0).
	SrcHash string `gorm:"not null;default:''" json:"src_hash"`
	// MTModel is the model id that produced a machine row (accountability +
	// re-translate audit); empty on source rows. NOT NULL DEFAULT ''.
	MTModel   string    `gorm:"not null;default:''" json:"mt_model"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkIntro) TableName() string { return "catalog_work_intro" }

// CatalogWorkCover is one cover image row for a BODYLESS work (site=” — no
// product database to hold its media), the media-aggregation wave's first
// byte-bearing native table (refs/proj/51 §3, step 53). It mirrors the
// galgame_cover shape (same columns, INDEPENDENT table — never the same row) so
// the read face can merge it with the CLAIMED bridge: a claimed galgame_wiki
// work reads its covers directly from galgame_cover (bridge-not-copy, §2) and
// NEVER writes a row here. One row per (work, image_hash): the unique key lets a
// work carry several covers, and the read face orders them by sort_order.
//
// Byte discipline (§4): a bodyless cover's bytes live in the CATALOG image
// scope (the same `catalog` image client the portrait wave opened) — distinct
// from galgame covers, which live in the galgame_wiki scope and are only ever
// bridge-READ here. shadow-never-delete (§8.B, the byte-version live wire): a
// bodyless work later claimed keeps its cover rows (claim is reversible); the
// read face's strict XOR stops reading them, but their bytes stay in catalog
// scope, so catalog-image-refping MUST keep pinging them (a missed shadowed row
// = GC eats a live image, the 66k-frozen failure class).
//
// source_id is row-level provenance (§8.C) — NOT NULL with NO default (the
// default-tag zero-value trap: a legitimately-low source id would drop from the
// INSERT). sexual/violence/sort_order default 0 (0 is their intended value AND
// zero, so the default tag is safe — no trap); kind allows the empty string
// (unknown / user upload), continuing galgame_cover semantics.
type CatalogWorkCover struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_cover" json:"work_id"`
	// ImageHash is the sha-256 the bytes are keyed by in the image service
	// (catalog scope). Part of the unique key.
	ImageHash string `gorm:"not null;uniqueIndex:uq_catalog_work_cover" json:"image_hash"`
	// SortOrder is the gallery/pin position (0 = pinned landscape banner,
	// mirroring galgame_cover). Meaningful zero == default zero → default tag safe.
	SortOrder int `gorm:"not null;default:0" json:"sort_order"`
	// Kind labels the cover type (VNDB-ish: main / pkgfront / dig / …); the empty
	// string is allowed (unknown / user upload), continuing galgame_cover semantics.
	Kind string `gorm:"not null;default:''" json:"kind"`
	// PortraitPinned marks the vertical PORTRAIT pin (the value kungal/moyu read
	// for the portrait-first UI). Mirrors galgame_cover.portrait_pinned.
	PortraitPinned bool `gorm:"not null;default:false" json:"portrait_pinned"`
	// Sexual/Violence are the per-image content-rating flags (0 = safe), matching
	// galgame_cover; 0 is both the intended default and the zero value (no trap).
	Sexual   int16 `gorm:"not null;default:0" json:"sexual"`
	Violence int16 `gorm:"not null;default:0" json:"violence"`
	// SourceID is the provenance FK (see the type doc). Part of no unique key —
	// several covers may share a source; the (work, image_hash) key is the identity.
	SourceID  int16     `gorm:"not null" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkCover) TableName() string { return "catalog_work_cover" }

// CatalogWorkScreenshot is one screenshot image row for a BODYLESS work (site=”
// — no product database to hold its media), the media-aggregation wave's
// closing native table (refs/proj/51 §3, step 54). It mirrors the
// galgame_screenshot shape (same columns, INDEPENDENT table — never the same
// row) so the read face can merge it with the CLAIMED bridge: a claimed
// galgame_wiki work reads its screenshots directly from galgame_screenshot
// (bridge-not-copy, §2) and NEVER writes a row here. One row per
// (work, image_hash): the unique key lets a work carry several screenshots, and
// the read face orders them by sort_order. Unlike catalog_work_cover it carries
// a caption and has no kind / portrait_pinned (galgame_screenshot's shape).
//
// Byte discipline (§4): a bodyless screenshot's bytes live in the CATALOG image
// scope (the same `catalog` image client the portrait/cover waves opened) —
// distinct from galgame screenshots, which live in the galgame_wiki scope and
// are only ever bridge-READ here. shadow-never-delete (§8.B, the byte-version
// live wire): a bodyless work later claimed keeps its screenshot rows (claim is
// reversible); the read face's strict XOR stops reading them, but their bytes
// stay in catalog scope, so catalog-image-refping MUST keep pinging them (a
// missed shadowed row = GC eats a live image, the 66k-frozen failure class).
//
// source_id is row-level provenance (§8.C) — NOT NULL with NO default (the
// default-tag zero-value trap: a legitimately-low source id would drop from the
// INSERT). sexual/violence/sort_order default 0 (0 is their intended value AND
// zero, so the default tag is safe — no trap); caption defaults to the empty
// string (no caption), continuing galgame_screenshot semantics.
type CatalogWorkScreenshot struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_screenshot" json:"work_id"`
	// ImageHash is the sha-256 the bytes are keyed by in the image service
	// (catalog scope). Part of the unique key.
	ImageHash string `gorm:"not null;uniqueIndex:uq_catalog_work_screenshot" json:"image_hash"`
	// SortOrder is the gallery position. Meaningful zero == default zero →
	// default tag safe.
	SortOrder int `gorm:"not null;default:0" json:"sort_order"`
	// Caption is the screenshot caption; the empty string is allowed (no
	// caption), continuing galgame_screenshot semantics.
	Caption string `gorm:"type:text;not null;default:''" json:"caption"`
	// Sexual/Violence are the per-image content-rating flags (0 = safe), matching
	// galgame_screenshot; 0 is both the intended default and the zero value (no trap).
	Sexual   int16 `gorm:"not null;default:0" json:"sexual"`
	Violence int16 `gorm:"not null;default:0" json:"violence"`
	// SourceID is the provenance FK (see the type doc). Part of no unique key —
	// several screenshots may share a source; the (work, image_hash) key is the identity.
	SourceID  int16     `gorm:"not null" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkScreenshot) TableName() string { return "catalog_work_screenshot" }

// CatalogWorkRating is one source's rating on a BODYLESS work (site=” — no
// product database to hold source-owned rating meta), the media-aggregation
// ratings facet's native table (refs/proj/58 Facet A, step 58a). It is
// source-generic (one row per (work, source), UNIQUE key) so any scored source
// lands in the same shape: the 58a backfill writes bangumi (BGM anchors ×
// src_bangumi.subject) and erogamespace (EG anchors × the EG mirror) rows. The
// read face merges it with the CLAIMED bridge: a claimed galgame_wiki work
// reads its ratings directly from galgame_bangumi_meta / galgame_eg_meta
// (bridge-not-copy, §2) and NEVER writes a row here.
//
// Score is the SOURCE-NATIVE scale, never normalized (58 拍板): bangumi is a
// 0-10 mean, erogamespace a 0-100 median — different semantics, so consumers
// render per source (source_id is on every row). NOT NULL with no default: a
// row without a score is meaningless and is never written (the backfill skips
// unscored subjects / NULL medians). Rank is the source-internal rank, NULL
// when the source has none (EG) or the subject is unranked (bangumi rank 0).
// vote_count 0 is a legitimate value AND the zero value, so its default tag is
// safe (no default-tag trap); source_id is NOT NULL with NO default (the trap).
// shadow-never-delete (§8.B): a bodyless work later claimed keeps its rows;
// the read face's strict XOR just stops reading them (pure DB — no bytes, so
// no refping concern).
type CatalogWorkRating struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_rating" json:"work_id"`
	// SourceID is the provenance FK AND part of the unique key: one rating row
	// per (work, source).
	SourceID int16 `gorm:"not null;uniqueIndex:uq_catalog_work_rating" json:"source_id"`
	// Score on the source-native scale (see the type doc). numeric keeps the
	// upstream precision (bangumi carries one decimal, e.g. 6.3).
	Score float64 `gorm:"type:numeric;not null" json:"score"`
	// VoteCount is how many ratings back the score (bangumi: sum of the
	// score_details buckets; EG: count2).
	VoteCount int `gorm:"not null;default:0" json:"vote_count"`
	// Rank is the source-internal rank; NULL = the source has no rank facet or
	// the work is unranked there.
	Rank      *int      `json:"rank"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkRating) TableName() string { return "catalog_work_rating" }

// CatalogWorkTag is one folksonomy tag on a BODYLESS work (site=” — no product
// database to hold source-owned tag data), the media-aggregation tags facet's
// native table (refs/proj/58 Facet B, step 58b). Tags are stored VERBATIM
// (58 拍板): no vocabulary mapping, no normalization beyond whitespace trim —
// the Bangumi folksonomy name (百合/拔作/PC/…) lands as-is with its vote count,
// and a future "tag normalization wave" can layer a mapping on top without
// touching this table. Content tags NEVER enter catalog_label (the attribution
// vocabulary — brand/publisher/circle/group organizational responsibility — a
// hard red line; polluting it with folksonomy is the failure mode this table
// exists to prevent).
//
// The read face merges it with the CLAIMED bridge: a claimed galgame_wiki work
// reads its tags directly from galgame_tag_relation ⋈ galgame_tag
// (bridge-not-copy, §2) and NEVER writes a row here. Count is the tag's vote
// count on the source (Bangumi folksonomy votes); 0 is a legitimate value AND
// the zero value, so its default tag is safe (no default-tag trap); source_id
// is NOT NULL with NO default (the trap). UNIQUE (work_id, name, source_id):
// one row per tag name per source — store-all, no threshold (count=1 rows are
// kept; consumers filter by count when rendering). shadow-never-delete (§8.B):
// a bodyless work later claimed keeps its rows; the read face's strict XOR
// just stops reading them (pure DB — no bytes, so no refping concern).
type CatalogWorkTag struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_tag" json:"work_id"`
	// Name is the tag text VERBATIM from the source (whitespace-trimmed only —
	// never mapped, localized, or case-folded here).
	Name string `gorm:"type:text;not null;uniqueIndex:uq_catalog_work_tag" json:"name"`
	// Count is the tag's vote count on the source (Bangumi: how many users
	// applied it to the subject).
	Count int `gorm:"not null;default:0" json:"count"`
	// SourceID is the provenance FK AND part of the unique key: one row per
	// (work, name, source).
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_work_tag" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkTag) TableName() string { return "catalog_work_tag" }

// CatalogWorkPopularity is one source's popularity counter on a BODYLESS work
// (site=” — no product database to hold source-owned popularity meta), the
// media-aggregation popularity facet's native table (refs/proj/62, ledger R1's
// companion facet). One row per (work, source, metric) — the UNIQUE key — so
// any counting source lands in the same shape: the step-62 backfill writes the
// DLsite trio (downloads / wishlist / reviews); a future PR adds e.g. the
// Bangumi favorite buckets by extending the PopularityMetric* vocabulary. The
// read face merges it with the CLAIMED bridge: a claimed galgame_wiki work
// reads its popularity directly from galgame_dlsite_meta (bridge-not-copy, §2)
// and NEVER writes a row here.
//
// Value is the raw counter VERBATIM from the source (never combined across
// sources — a DLsite sale and a Bangumi favorite are different units, so
// consumers render per (source_id, metric)). NOT NULL with no default: a row
// without a value is meaningless and never written; 0 is a legitimate value
// (an absent source counter never becomes a 0 row — the backfill skips absent
// fields). These counters are VOLATILE, so the write path is
// ON CONFLICT DO UPDATE (change-detected): re-running the backfill after a
// mirror refresh updates rows in place. metric/source_id carry NO default tag
// (metric 0 = downloads is meaningful — the default-tag zero-value trap).
// shadow-never-delete (§8.B): a bodyless work later claimed keeps its rows;
// the read face's strict XOR just stops reading them (pure DB — no bytes, so
// no refping concern).
type CatalogWorkPopularity struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_popularity" json:"work_id"`
	// SourceID is the provenance FK AND part of the unique key.
	SourceID int16 `gorm:"not null;uniqueIndex:uq_catalog_work_popularity" json:"source_id"`
	// Metric uses the PopularityMetric* constants (0=downloads 1=wishlist
	// 2=reviews; extensible vocabulary — see constants.go).
	Metric int16 `gorm:"not null;uniqueIndex:uq_catalog_work_popularity" json:"metric"`
	// Value is the counter on the source, verbatim (see the type doc).
	Value     int64     `gorm:"not null" json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkPopularity) TableName() string { return "catalog_work_popularity" }

// CatalogWorkPlaytime is one source's playtime estimate on a work — the
// media-aggregation playtime facet's native table (refs/proj/91, ledger 时长
// row). Unlike ratings/tags/popularity this facet has NO claimed bridge lane:
// the wiki galgame family carries no playtime field, so the native table
// serves claimed and bodyless works alike (the (facet,source) XOR's
// degenerate case, step-88 semantics: the bridge set is empty by
// construction).
//
// Minutes is normalized to MINUTES — a unit conversion, not a scale
// normalization (the 58 拍板 "source-native scale" rule is about estimate
// semantics, which stay source-native: vndb = vote-backed median,
// erogamespace = community median). The EG lane converts its hours ×60; the
// vndb lane stores c_length verbatim (already minutes). NOT NULL with no
// default: a row without a playtime is meaningless and never written.
// vote_count backs the estimate (vndb c_lengthnum; EG publishes no per-work
// count → 0, a legitimate zero — the default tag is safe). UNIQUE
// (work_id, source_id): one estimate per source per work. Writes are
// ON CONFLICT DO UPDATE with change detection (the 62 upsert discipline), so
// a mirror/dump refresh + re-run updates rows in place and an unchanged
// re-run is a no-op.
type CatalogWorkPlaytime struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_playtime" json:"work_id"`
	// SourceID is the provenance FK AND part of the unique key.
	SourceID int16 `gorm:"not null;uniqueIndex:uq_catalog_work_playtime" json:"source_id"`
	// Minutes is the median playtime in minutes (see the type doc).
	Minutes int `gorm:"not null" json:"minutes"`
	// VoteCount is how many user reports back the estimate; 0 = the source
	// publishes no per-work count (EG).
	VoteCount int       `gorm:"not null;default:0" json:"vote_count"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkPlaytime) TableName() string { return "catalog_work_playtime" }

// CatalogRelease is the SKU/edition anchor point (doc 17 R3), REGISTRY-grade:
// identity + date + platform + the anchor external refs hang off when an
// external ID is SKU-natured (DLsite workno, VNDB release, store pages).
// It is NOT a merchandise/file model — prices stay in staging, file trees
// are content-grade and never enter catalog. Built day-1 because adding the
// layer later is the most expensive direction (Discogs lesson); per-medium
// use is optional.
type CatalogRelease struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;index" json:"work_id"`
	// Kind uses the ReleaseKind* constants.
	Kind     int16   `gorm:"not null" json:"kind"`
	Title    *string `json:"title"`
	Lang     *string `json:"lang"`
	Platform *string `json:"platform"`
	// Fuzzy release date (three nullable columns, doc 17 R9).
	ReleasedY *int16 `json:"released_y"`
	ReleasedM *int16 `json:"released_m"`
	ReleasedD *int16 `json:"released_d"`
	// EventID is the doujin-convention slot reserved day-1 (every doujin
	// precedent hangs the event off the release). Deliberately NO FK: the
	// event table is built when real convention data arrives (doc 17 §9).
	EventID *int64 `json:"event_id"`
	// Extra: governed escape hatch, same CHECKs as catalog_work.
	Extra     datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"extra"`
	CreatedAt time.Time      `json:"created_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`

	Work *CatalogWork `gorm:"foreignKey:WorkID" json:"work,omitempty"`
}

func (CatalogRelease) TableName() string { return "catalog_release" }

// CatalogSeries is one work series (step 94, refs/proj/94 option B): a
// first-class grouping entity rather than O(n²) pairwise same_series edges —
// the series id/name from the source stays addressable (a future series page),
// membership is O(n), and future vndb/bgm series lanes append rows to the SAME
// table with their own source_id. Currently dlsite-sourced only (series_id
// "SRI…" + series_name from product_json); only series with >=2 anchored
// members are materialized (a single-member series has no read value — it
// stays in the mirror).
type CatalogSeries struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// DisplayName is the source's series name verbatim (dlsite series_name);
	// falls back to the external id when the source carries no name.
	DisplayName string `gorm:"not null" json:"display_name"`
	// SourceID + ExternalID anchor the series in its source vocabulary —
	// UNIQUE: one row per source series.
	SourceID   int16     `gorm:"not null;uniqueIndex:uq_catalog_series_source,priority:1" json:"source_id"`
	ExternalID string    `gorm:"not null;uniqueIndex:uq_catalog_series_source,priority:2" json:"external_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`

	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogSeries) TableName() string { return "catalog_series" }

// CatalogSeriesMember is one work's membership in a series (step 94). UNIQUE
// (series_id, work_id); work_id carries its own index for the read face's
// reverse lookup (work → its series). Membership mirrors the source: the
// importer inserts missing members and deletes stale ones (the mirror is the
// truth — the step-93 edge discipline).
type CatalogSeriesMember struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	SeriesID  int64     `gorm:"not null;uniqueIndex:uq_catalog_series_member,priority:1" json:"series_id"`
	WorkID    int64     `gorm:"not null;index;uniqueIndex:uq_catalog_series_member,priority:2" json:"work_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Series *CatalogSeries `gorm:"foreignKey:SeriesID" json:"series,omitempty"`
	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
}

func (CatalogSeriesMember) TableName() string { return "catalog_series_member" }

// CatalogWorkPlatform is one platform assertion on a WORK (step 96): the bgm
// lane's landing surface — Bangumi carries platforms on the SUBJECT (work)
// and its bodyless works have no release rows to hang them on (only
// 1,875/13,293 have any release), so the work level is that source's natural
// grain. The vndb face keeps platforms on RELEASES (catalog_release.platform
// + extra.platforms — a port is a release-level fact there); consumers union
// the two faces as needed. Platform is a TEXT code from the catalog_platform
// registry (the lang-column convention).
type CatalogWorkPlatform struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_platform,priority:1" json:"work_id"`
	// Platform is the registry code (win/and/ios/…), part of the unique key.
	Platform string `gorm:"not null;uniqueIndex:uq_catalog_work_platform,priority:2" json:"platform"`
	// SourceID is the provenance FK (§8.C), part of the unique key so a future
	// second source lands additively.
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_work_platform,priority:3" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkPlatform) TableName() string { return "catalog_work_platform" }
