package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// CatalogWork is the work registry row (doc 17 R2): ONE global ID space for
// every medium (no per-type ID blocks — the TMDB collision tax). It is the
// identity + graph anchor; the work BODY always lives in a product database.
//
// Claiming: site + product_work_id are BOTH NULL for an unclaimed row (DLsite
// voice works, Bangumi anime/manga subjects — data that predates its
// product); claiming is one UPDATE filling both. Claim semantics (service
// side, step 05 + ingestion): a product creating a work FIRST looks up an
// existing row by (medium, external anchors) and claims it — a claim must
// never mint a second identity. Unclaimed-row hygiene (OpenLibrary lesson):
// rows without an external_ref anchor and below the metadata bar can only be
// status=stub and stay out of public aggregation.
type CatalogWork struct {
	ID       int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	MediumID int16 `gorm:"not null;uniqueIndex:uq_catalog_work_claim;index:idx_catalog_work_medium_status,priority:1" json:"medium_id"`
	// The claim unique treats NULLs as distinct (PG semantics): unclaimed
	// rows coexist freely, while a claimed (medium, site, product_work_id)
	// triple is globally unique — exactly the wanted rule.
	Site          *string `gorm:"uniqueIndex:uq_catalog_work_claim" json:"site"`
	ProductWorkID *int64  `gorm:"uniqueIndex:uq_catalog_work_claim" json:"product_work_id"`
	// OLang is the original language (BCP-47); it decides which title row is
	// primary (VNDB model). Write paths default it to 'ja' explicitly — no
	// DB default on purpose.
	OLang string `gorm:"column:olang;not null" json:"olang"`
	// DisplayName is the denormalized display fast-path; titles are truth.
	DisplayName string `gorm:"not null" json:"display_name"`
	// ContentRating uses the ContentRating* constants.
	ContentRating int16 `gorm:"not null" json:"content_rating"`
	// Status uses the WorkStatus* constants.
	Status int16 `gorm:"not null;index:idx_catalog_work_medium_status,priority:2" json:"status"`
	// Extra is the governed escape hatch (doc 17 R9): object-only + 64KB cap
	// (CHECKs in the raw-SQL section). Rule: a key that gets queried
	// regularly must be promoted to a real column — extra is a buffer, not a
	// home.
	Extra           datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"extra"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`

	Medium *CatalogMedium `gorm:"foreignKey:MediumID" json:"medium,omitempty"`
}

func (CatalogWork) TableName() string { return "catalog_work" }

// CatalogWorkTitle is one title row per language/kind (doc 17 R2/R5):
// romaji/latin lives on the row, NOT as a separate row (VNDB v3 shape).
type CatalogWorkTitle struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_title" json:"work_id"`
	// Lang is BCP-47 and part of the uniqueness key, hence NOT NULL
	// DEFAULT '' (same rationale as the alias tables).
	Lang      string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_work_title" json:"lang"`
	Title     string  `gorm:"not null;uniqueIndex:uq_catalog_work_title" json:"title"`
	TitleNorm string  `gorm:"->;-:migration" json:"title_norm"`
	Latin     *string `json:"latin"`
	// Kind uses the WorkTitleKind* constants.
	Kind int16 `gorm:"not null;uniqueIndex:uq_catalog_work_title" json:"kind"`

	Work *CatalogWork `gorm:"foreignKey:WorkID" json:"work,omitempty"`
}

func (CatalogWorkTitle) TableName() string { return "catalog_work_title" }

// CatalogWorkIntro is one multilingual intro/description row for a BODYLESS
// work (site=” — no product database to hold its body), the media-aggregation
// pilot's first native media table (refs/proj/51 §3, step 52). It mirrors the
// catalog_work_title shape so the read face can merge it with the CLAIMED
// bridge (a claimed galgame_wiki work reads its intro directly from
// galgame.intro_* — a column→row pivot — and NEVER writes a row here:
// bridge-not-copy, §2). One row per (work, language, source): the unique key
// lets several sources coexist for the same language, and the read face merges
// them per language (source_id ascending wins).
//
// source_id is row-level provenance (§8.C) — NOT NULL with NO default: a
// meaningful source is always known at write time, and the default tag would
// drop a legitimately-low source id from the INSERT (the default-tag zero-value
// trap). shadow-never-delete (§8.B): a bodyless work later claimed keeps its
// rows (claim is reversible); the read face's strict XOR just stops reading
// them.
type CatalogWorkIntro struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_intro" json:"work_id"`
	// Lang is BCP-47 and part of the uniqueness key, hence NOT NULL DEFAULT ''
	// (same rationale as catalog_work_title / the alias tables).
	Lang string `gorm:"not null;default:'';uniqueIndex:uq_catalog_work_intro" json:"lang"`
	// Intro is the body text (verbatim from the source in this pilot — no
	// cleaning; §5). NOT NULL, no default: content is always supplied.
	Intro string `gorm:"type:text;not null" json:"intro"`
	// SourceID is the provenance FK (see the type doc). Part of the unique key.
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_work_intro" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkIntro) TableName() string { return "catalog_work_intro" }

// CatalogWorkCover is one cover image row for a BODYLESS work (site=” — no
// product database to hold its media), the media-aggregation wave's first
// byte-bearing native table (refs/proj/51 §3, step 53). It mirrors the
// galgame_cover shape (same columns, INDEPENDENT table — never the same row) so
// the read face can merge it with the CLAIMED bridge: a claimed galgame_wiki
// work reads its covers directly from galgame_cover (bridge-not-copy, §2) and
// NEVER writes a row here. One row per (work, image_hash): the unique key lets a
// work carry several covers, and the read face orders them by sort_order.
//
// Byte discipline (§4): a bodyless cover's bytes live in the CATALOG image
// scope (the same `catalog` image client the portrait wave opened) — distinct
// from galgame covers, which live in the galgame_wiki scope and are only ever
// bridge-READ here. shadow-never-delete (§8.B, the byte-version live wire): a
// bodyless work later claimed keeps its cover rows (claim is reversible); the
// read face's strict XOR stops reading them, but their bytes stay in catalog
// scope, so catalog-image-refping MUST keep pinging them (a missed shadowed row
// = GC eats a live image, the 66k-frozen failure class).
//
// source_id is row-level provenance (§8.C) — NOT NULL with NO default (the
// default-tag zero-value trap: a legitimately-low source id would drop from the
// INSERT). sexual/violence/sort_order default 0 (0 is their intended value AND
// zero, so the default tag is safe — no trap); kind allows the empty string
// (unknown / user upload), continuing galgame_cover semantics.
type CatalogWorkCover struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_cover" json:"work_id"`
	// ImageHash is the sha-256 the bytes are keyed by in the image service
	// (catalog scope). Part of the unique key.
	ImageHash string `gorm:"not null;uniqueIndex:uq_catalog_work_cover" json:"image_hash"`
	// SortOrder is the gallery/pin position (0 = pinned landscape banner,
	// mirroring galgame_cover). Meaningful zero == default zero → default tag safe.
	SortOrder int `gorm:"not null;default:0" json:"sort_order"`
	// Kind labels the cover type (VNDB-ish: main / pkgfront / dig / …); the empty
	// string is allowed (unknown / user upload), continuing galgame_cover semantics.
	Kind string `gorm:"not null;default:''" json:"kind"`
	// PortraitPinned marks the vertical PORTRAIT pin (the value kungal/moyu read
	// for the portrait-first UI). Mirrors galgame_cover.portrait_pinned.
	PortraitPinned bool `gorm:"not null;default:false" json:"portrait_pinned"`
	// Sexual/Violence are the per-image content-rating flags (0 = safe), matching
	// galgame_cover; 0 is both the intended default and the zero value (no trap).
	Sexual   int16 `gorm:"not null;default:0" json:"sexual"`
	Violence int16 `gorm:"not null;default:0" json:"violence"`
	// SourceID is the provenance FK (see the type doc). Part of no unique key —
	// several covers may share a source; the (work, image_hash) key is the identity.
	SourceID  int16     `gorm:"not null" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkCover) TableName() string { return "catalog_work_cover" }

// CatalogWorkScreenshot is one screenshot image row for a BODYLESS work (site=”
// — no product database to hold its media), the media-aggregation wave's
// closing native table (refs/proj/51 §3, step 54). It mirrors the
// galgame_screenshot shape (same columns, INDEPENDENT table — never the same
// row) so the read face can merge it with the CLAIMED bridge: a claimed
// galgame_wiki work reads its screenshots directly from galgame_screenshot
// (bridge-not-copy, §2) and NEVER writes a row here. One row per
// (work, image_hash): the unique key lets a work carry several screenshots, and
// the read face orders them by sort_order. Unlike catalog_work_cover it carries
// a caption and has no kind / portrait_pinned (galgame_screenshot's shape).
//
// Byte discipline (§4): a bodyless screenshot's bytes live in the CATALOG image
// scope (the same `catalog` image client the portrait/cover waves opened) —
// distinct from galgame screenshots, which live in the galgame_wiki scope and
// are only ever bridge-READ here. shadow-never-delete (§8.B, the byte-version
// live wire): a bodyless work later claimed keeps its screenshot rows (claim is
// reversible); the read face's strict XOR stops reading them, but their bytes
// stay in catalog scope, so catalog-image-refping MUST keep pinging them (a
// missed shadowed row = GC eats a live image, the 66k-frozen failure class).
//
// source_id is row-level provenance (§8.C) — NOT NULL with NO default (the
// default-tag zero-value trap: a legitimately-low source id would drop from the
// INSERT). sexual/violence/sort_order default 0 (0 is their intended value AND
// zero, so the default tag is safe — no trap); caption defaults to the empty
// string (no caption), continuing galgame_screenshot semantics.
type CatalogWorkScreenshot struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_screenshot" json:"work_id"`
	// ImageHash is the sha-256 the bytes are keyed by in the image service
	// (catalog scope). Part of the unique key.
	ImageHash string `gorm:"not null;uniqueIndex:uq_catalog_work_screenshot" json:"image_hash"`
	// SortOrder is the gallery position. Meaningful zero == default zero →
	// default tag safe.
	SortOrder int `gorm:"not null;default:0" json:"sort_order"`
	// Caption is the screenshot caption; the empty string is allowed (no
	// caption), continuing galgame_screenshot semantics.
	Caption string `gorm:"type:text;not null;default:''" json:"caption"`
	// Sexual/Violence are the per-image content-rating flags (0 = safe), matching
	// galgame_screenshot; 0 is both the intended default and the zero value (no trap).
	Sexual   int16 `gorm:"not null;default:0" json:"sexual"`
	Violence int16 `gorm:"not null;default:0" json:"violence"`
	// SourceID is the provenance FK (see the type doc). Part of no unique key —
	// several screenshots may share a source; the (work, image_hash) key is the identity.
	SourceID  int16     `gorm:"not null" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkScreenshot) TableName() string { return "catalog_work_screenshot" }

// CatalogWorkRating is one source's rating on a BODYLESS work (site=” — no
// product database to hold source-owned rating meta), the media-aggregation
// ratings facet's native table (refs/proj/58 Facet A, step 58a). It is
// source-generic (one row per (work, source), UNIQUE key) so any scored source
// lands in the same shape: the 58a backfill writes bangumi (BGM anchors ×
// src_bangumi.subject) and erogamespace (EG anchors × the EG mirror) rows. The
// read face merges it with the CLAIMED bridge: a claimed galgame_wiki work
// reads its ratings directly from galgame_bangumi_meta / galgame_eg_meta
// (bridge-not-copy, §2) and NEVER writes a row here.
//
// Score is the SOURCE-NATIVE scale, never normalized (58 拍板): bangumi is a
// 0-10 mean, erogamespace a 0-100 median — different semantics, so consumers
// render per source (source_id is on every row). NOT NULL with no default: a
// row without a score is meaningless and is never written (the backfill skips
// unscored subjects / NULL medians). Rank is the source-internal rank, NULL
// when the source has none (EG) or the subject is unranked (bangumi rank 0).
// vote_count 0 is a legitimate value AND the zero value, so its default tag is
// safe (no default-tag trap); source_id is NOT NULL with NO default (the trap).
// shadow-never-delete (§8.B): a bodyless work later claimed keeps its rows;
// the read face's strict XOR just stops reading them (pure DB — no bytes, so
// no refping concern).
type CatalogWorkRating struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;uniqueIndex:uq_catalog_work_rating" json:"work_id"`
	// SourceID is the provenance FK AND part of the unique key: one rating row
	// per (work, source).
	SourceID int16 `gorm:"not null;uniqueIndex:uq_catalog_work_rating" json:"source_id"`
	// Score on the source-native scale (see the type doc). numeric keeps the
	// upstream precision (bangumi carries one decimal, e.g. 6.3).
	Score float64 `gorm:"type:numeric;not null" json:"score"`
	// VoteCount is how many ratings back the score (bangumi: sum of the
	// score_details buckets; EG: count2).
	VoteCount int `gorm:"not null;default:0" json:"vote_count"`
	// Rank is the source-internal rank; NULL = the source has no rank facet or
	// the work is unranked there.
	Rank      *int      `json:"rank"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkRating) TableName() string { return "catalog_work_rating" }

// CatalogRelease is the SKU/edition anchor point (doc 17 R3), REGISTRY-grade:
// identity + date + platform + the anchor external refs hang off when an
// external ID is SKU-natured (DLsite workno, VNDB release, store pages).
// It is NOT a merchandise/file model — prices stay in staging, file trees
// are content-grade and never enter catalog. Built day-1 because adding the
// layer later is the most expensive direction (Discogs lesson); per-medium
// use is optional.
type CatalogRelease struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID int64 `gorm:"not null;index" json:"work_id"`
	// Kind uses the ReleaseKind* constants.
	Kind     int16   `gorm:"not null" json:"kind"`
	Title    *string `json:"title"`
	Lang     *string `json:"lang"`
	Platform *string `json:"platform"`
	// Fuzzy release date (three nullable columns, doc 17 R9).
	ReleasedY *int16 `json:"released_y"`
	ReleasedM *int16 `json:"released_m"`
	ReleasedD *int16 `json:"released_d"`
	// EventID is the doujin-convention slot reserved day-1 (every doujin
	// precedent hangs the event off the release). Deliberately NO FK: the
	// event table is built when real convention data arrives (doc 17 §9).
	EventID *int64 `json:"event_id"`
	// Extra: governed escape hatch, same CHECKs as catalog_work.
	Extra     datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"extra"`
	CreatedAt time.Time      `json:"created_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`

	Work *CatalogWork `gorm:"foreignKey:WorkID" json:"work,omitempty"`
}

func (CatalogRelease) TableName() string { return "catalog_release" }
