// Image URL resolver helpers (mirror of apps/web/shared/utils/resolveImage.ts).
//
// See docs/image_service/04-migration-plan.md and 06-integration-guide.md.
//
// Fallback chain for any image-bearing field:
//
//    *_image_hash → image_service URL (with optional variant)
//    legacy URL    → use as-is
//    neither       → caller-provided placeholder
//
// CDN base read from `useRuntimeConfig().public.imageCdnBase`. Helpers
// either take it explicitly via opts.cdnBase, or use the bound `resolveBy`
// factory which does the runtime-config lookup once.

interface ImageURLOptions {
  /** image_service CDN base, e.g. https://image.kungal.iloveren.link */
  cdnBase: string
  /** Output extension. Default 'webp' (V1 always emits webp). */
  ext?: string
  /** Variant suffix (e.g. 'mini', '256', '100'); omitted = main image. */
  variant?: string
}

/** Build a public image_service URL from a content hash. */
export const imageHashUrl = (hash: string, opts: ImageURLOptions): string => {
  const ext = opts.ext ?? 'webp'
  const base = opts.cdnBase.replace(/\/+$/, '')
  if (!hash || hash.length < 4) return ''
  const prefix = `${base}/${hash.slice(0, 2)}/${hash.slice(2, 4)}/${hash}`
  return opts.variant ? `${prefix}_${opts.variant}.${ext}` : `${prefix}.${ext}`
}

/**
 * Resolve a galgame's banner URL.
 *
 * Preference order (matches the backend's effective-banner derivation):
 *   1. effective_banner_hash — image_hash of the pinned cover
 *      (galgame_cover.sort_order=0), computed server-side.
 *   2. banner — original VNDB / user-provided URL (oldest fallback,
 *      used when the galgame has no covers yet).
 *
 * The legacy banner_image_hash branch was removed in PR5 together with
 * the column.
 *
 * For list pages pass `variant: 'mini'` (460×259, generated by image_service).
 * For detail pages omit `variant` to get the full main image.
 */
export const resolveBannerUrl = (
  galgame:
    | {
        banner: string
        effective_banner_hash?: string | null
      }
    | null
    | undefined,
  opts: ImageURLOptions,
  placeholder = ''
): string => {
  if (!galgame) return placeholder
  if (galgame.effective_banner_hash) {
    return imageHashUrl(galgame.effective_banner_hash, opts)
  }
  if (galgame.banner) return galgame.banner
  return placeholder
}

/**
 * Resolve a user's avatar URL.
 *
 * `variant: '256'` is the default avatar tile size; `'100'` is small.
 */
export const resolveAvatarUrl = (
  user: { avatar: string; avatar_image_hash?: string | null } | null | undefined,
  opts: ImageURLOptions,
  placeholder = ''
): string => {
  if (!user) return placeholder
  if (user.avatar_image_hash) {
    return imageHashUrl(user.avatar_image_hash, opts)
  }
  if (user.avatar) return user.avatar
  return placeholder
}
