package model

import "time"

const (
	SourceKeyYmgal  = "ymgal"
	SourceKeyHihyou = "galgame_hihyou"
)

const (
	StatusPending   int16 = 0
	StatusPublished int16 = 1
	StatusRejected  int16 = 2
	StatusWithdrawn int16 = 3
)

const (
	WorkConfidenceManual      int16 = 0
	WorkConfidenceExactAnchor int16 = 1
	WorkConfidenceHeuristic   int16 = 2
)

// PreviewMaxRunes is the hard ceiling the importers truncate to and the DB
// CHECK constraint enforces. It exists because 月幕 authorised the preview
// message and the banner only — "不要文章的全部内容" — so an unbounded text
// column would be a promise we could break by accident.
const PreviewMaxRunes = 200

type NewsSource struct {
	Key          string    `gorm:"primaryKey;column:key" json:"key"`
	DisplayName  string    `gorm:"not null;column:display_name" json:"display_name"`
	HomepageURL  string    `gorm:"not null;column:homepage_url" json:"homepage_url"`
	Attribution  string    `gorm:"not null;column:attribution" json:"attribution"`
	PublisherUID int64     `gorm:"not null;column:publisher_uid" json:"publisher_uid"`
	ColumnURL    string    `gorm:"not null;default:'';column:column_url" json:"column_url"`
	Active       bool      `gorm:"not null;column:active" json:"active"`
	CreatedAt    time.Time `gorm:"not null;default:now();column:created_at" json:"created_at"`
	UpdatedAt    time.Time `gorm:"not null;default:now();column:updated_at" json:"updated_at"`
}

func (NewsSource) TableName() string { return "news_source" }

type NewsItem struct {
	ID          int64      `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	SourceKey   string     `gorm:"not null;column:source_key" json:"source_key"`
	ExternalID  string     `gorm:"not null;column:external_id" json:"external_id"`
	Title       string     `gorm:"not null;column:title" json:"title"`
	Preview     string     `gorm:"not null;column:preview" json:"preview"`
	SourceURL   string     `gorm:"not null;column:source_url" json:"source_url"`
	BannerHash  string     `gorm:"not null;default:'';column:banner_hash" json:"banner_hash"`
	PublishedAt time.Time  `gorm:"not null;column:published_at" json:"published_at"`
	Status      int16      `gorm:"not null;column:status" json:"status"`
	FirstSeenAt time.Time  `gorm:"not null;default:now();column:first_seen_at" json:"first_seen_at"`
	LastSeenAt  time.Time  `gorm:"not null;default:now();column:last_seen_at" json:"last_seen_at"`
	DeadAt      *time.Time `gorm:"column:dead_at" json:"dead_at,omitempty"`
	CreatedAt   time.Time  `gorm:"not null;default:now();column:created_at" json:"created_at"`
	UpdatedAt   time.Time  `gorm:"not null;default:now();column:updated_at" json:"updated_at"`
}

func (NewsItem) TableName() string { return "news_item" }

type NewsItemImage struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ItemID    int64     `gorm:"not null;column:item_id" json:"item_id"`
	ImageHash string    `gorm:"not null;column:image_hash" json:"image_hash"`
	OriginURL string    `gorm:"not null;column:origin_url" json:"origin_url"`
	Position  int       `gorm:"not null;default:0;type:integer;column:position" json:"position"`
	CreatedAt time.Time `gorm:"not null;default:now();column:created_at" json:"created_at"`
}

func (NewsItemImage) TableName() string { return "news_item_image" }

type NewsItemWork struct {
	ItemID     int64     `gorm:"primaryKey;column:item_id" json:"item_id"`
	WorkID     int64     `gorm:"primaryKey;column:work_id" json:"work_id"`
	Confidence int16     `gorm:"not null;column:confidence" json:"confidence"`
	CreatedAt  time.Time `gorm:"not null;default:now();column:created_at" json:"created_at"`
}

func (NewsItemWork) TableName() string { return "news_item_work" }
