#!/usr/bin/env node
/**
 * Bundles the two Tier-A public OpenAPI specs into the app so Scalar renders
 * them WITHOUT any runtime/CDN fetch (strict CSP): reads the source specs from
 * the repo's docs/ (the single source, produced by `cmd/gen-openapi` public
 * targets), prepends a top-level `servers:` block pointing at the live API host
 * (the specs themselves are server-agnostic), and writes
 * `app/generated/specs.ts` exporting each as a YAML string Scalar can parse.
 *
 * The generated file is committed (same pattern as app/assets/kun-icons.ts): a
 * derived build artifact, never hand-edited. Re-run after the public specs
 * change:  pnpm --filter developer sync:specs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = join(__dirname, '..', '..', '..')
const OUTPUT = join(__dirname, '..', 'app/generated/specs.ts')

// The live open-API host (docs/developer-platform/01-design §2). Injected as a
// `servers:` entry so Scalar's "Try It" targets the real endpoint.
const API_BASE_URL = 'https://api.nextmoe.dev'

const SOURCES = [
  {
    key: 'galgameSpec',
    file: join(REPO_ROOT, 'docs/galgame_wiki/public-openapi.yaml')
  },
  {
    key: 'catalogSpec',
    file: join(REPO_ROOT, 'docs/catalog/public-openapi.yaml')
  }
]

const withServers = (yaml) => {
  // The public specs carry no `servers:` block (server-agnostic). Prepend one
  // — YAML top-level keys are order-independent, so this is safe to inject.
  const server = `servers:\n  - url: ${API_BASE_URL}\n    description: NextMoe Open API (production)\n`
  return server + yaml
}

const body = SOURCES.map(({ key, file }) => {
  const raw = readFileSync(file, 'utf8')
  return `export const ${key} = ${JSON.stringify(withServers(raw))}`
}).join('\n\n')

const out = `/**
 * Auto-generated by scripts/sync-specs.mjs — do not edit by hand.
 * Run \`pnpm --filter developer sync:specs\` after the public specs change.
 *
 * The two Tier-A public OpenAPI specs (galgame + catalog faces), bundled as
 * YAML strings with a live \`servers:\` block injected, for Scalar to render
 * with no external/CDN fetch.
 */
${body}
`

mkdirSync(dirname(OUTPUT), { recursive: true })
writeFileSync(OUTPUT, out)
console.log(`Wrote ${SOURCES.length} spec(s) → app/generated/specs.ts`)
