package llmsuggest

import (
	"crypto/sha256"
	"encoding/hex"
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// The src_llm schema is tool-owned rebuildable staging (srcbangumi discipline):
// CREATE SCHEMA + AutoMigrate at startup, entirely outside migrate-catalog's
// Gold order. Every suggestion row is keyed by (task/input_hash/model/
// prompt_version) so a re-run resumes instead of re-querying the model.

// Prompt versions — bump on any prompt change so a re-run re-judges rather than
// resuming stale answers. Single-item and batch prompts are versioned apart.
const (
	PromptNamePairV1   = "name-pair-v1"
	PromptNamePairV1B  = "name-pair-v1-batch"
	PromptResidueV1    = "residue-v1"
	PromptBidVerdictV1 = "bid-verdict-v1"
)

// Verdict values (also the model's guided-JSON enum).
const (
	VerdictSame      = "same"
	VerdictDifferent = "different"
	VerdictUnsure    = "unsure"
)

// Run records one pipeline execution: task, model, prompt version, per-run
// counts and timing — the audit trail of the suggestion batches.
type Run struct {
	ID            int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Task          string         `gorm:"not null" json:"task"`
	Model         string         `gorm:"not null" json:"model"`
	PromptVersion string         `gorm:"not null" json:"prompt_version"`
	Counts        datatypes.JSON `gorm:"type:jsonb" json:"counts"`
	Notes         string         `gorm:"not null;default:''" json:"notes"`
	StartedAt     time.Time      `gorm:"not null" json:"started_at"`
}

func (Run) TableName() string { return "src_llm.run" }

// NamePairJudgment is one "are A and B the same creator's names?" judgment.
// Used by the gold-set calibration (gold_label + source_rule set) and reusable
// for future name-alignment tasks. verdict/reason empty + error set = a call
// that failed after retries (recorded, never crashes the batch). confidence is
// archived for sorting ONLY (doc 17 §4 — never thresholded into an action).
type NamePairJudgment struct {
	ID            int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Task          string  `gorm:"not null;uniqueIndex:uq_name_pair,priority:1" json:"task"`
	InputHash     string  `gorm:"not null;uniqueIndex:uq_name_pair,priority:2" json:"input_hash"`
	Model         string  `gorm:"not null;uniqueIndex:uq_name_pair,priority:3" json:"model"`
	PromptVersion string  `gorm:"not null;uniqueIndex:uq_name_pair,priority:4" json:"prompt_version"`
	A             string  `gorm:"not null" json:"a"`
	B             string  `gorm:"not null" json:"b"`
	GoldLabel     string  `gorm:"not null;default:''" json:"gold_label"`
	SourceRule    string  `gorm:"not null;default:''" json:"source_rule"`
	Verdict       string  `gorm:"not null;default:''" json:"verdict"`
	Reason        string  `gorm:"not null;default:''" json:"reason"`
	Confidence    float64 `gorm:"not null;default:0" json:"confidence"`
	Error         string  `gorm:"not null;default:''" json:"error"`
	CreatedAt     time.Time
}

func (NamePairJudgment) TableName() string { return "src_llm.name_pair_judgment" }

// InfoboxExtraction is a SUGGESTED field extraction for one parse_error residue
// row. extracted mirrors bangumiwiki.Infobox (type + fields) as JSON. The
// Silver infobox_parsed is never touched — consumption (human confirm → adopt)
// is a later step.
type InfoboxExtraction struct {
	ID            int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	SrcTable      string         `gorm:"not null" json:"src_table"`
	SrcID         int64          `gorm:"not null" json:"src_id"`
	InputHash     string         `gorm:"not null;uniqueIndex:uq_infobox_extraction,priority:1" json:"input_hash"`
	Model         string         `gorm:"not null;uniqueIndex:uq_infobox_extraction,priority:2" json:"model"`
	PromptVersion string         `gorm:"not null;uniqueIndex:uq_infobox_extraction,priority:3" json:"prompt_version"`
	Extracted     datatypes.JSON `gorm:"type:jsonb" json:"extracted"`
	Error         string         `gorm:"not null;default:''" json:"error"`
	CreatedAt     time.Time
}

func (InfoboxExtraction) TableName() string { return "src_llm.infobox_extraction" }

// BidIdentityVerdict is one bid-exact pair audited (step 11 carry-over): does
// the wiki galgame's name set and the Bangumi subject's name set refer to the
// same work? layer is the deterministic pre-classification (pass/boundary/
// suspect); verdict/reason are the LLM adjudication for boundary+suspect only
// (pass rows carry no LLM call). Detection only — zero ref re-grading.
type BidIdentityVerdict struct {
	ID            int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID        int64   `gorm:"not null" json:"work_id"`
	GalgameID     int64   `gorm:"not null" json:"galgame_id"`
	BID           int64   `gorm:"column:bid;not null" json:"bid"`
	Layer         string  `gorm:"not null" json:"layer"`
	WikiNames     string  `gorm:"not null;default:''" json:"wiki_names"`
	SubjectNames  string  `gorm:"not null;default:''" json:"subject_names"`
	InputHash     string  `gorm:"not null;uniqueIndex:uq_bid_verdict,priority:1" json:"input_hash"`
	Model         string  `gorm:"not null;uniqueIndex:uq_bid_verdict,priority:2" json:"model"`
	PromptVersion string  `gorm:"not null;uniqueIndex:uq_bid_verdict,priority:3" json:"prompt_version"`
	Verdict       string  `gorm:"not null;default:''" json:"verdict"`
	Reason        string  `gorm:"not null;default:''" json:"reason"`
	Confidence    float64 `gorm:"not null;default:0" json:"confidence"`
	Error         string  `gorm:"not null;default:''" json:"error"`
	CreatedAt     time.Time
	// Human-review resolution (step 20 B-track worklist). The deterministic +
	// LLM layers only DETECT; a human decides here. Resolution is the decision
	// keyword (ok / wrong / wrong:<bid> / smear); a resolved row is excluded
	// from the next --export and skipped by a re-run --apply (idempotency).
	Resolution     string     `gorm:"not null;default:''" json:"resolution"`
	ResolutionNote string     `gorm:"not null;default:''" json:"resolution_note"`
	ResolvedAt     *time.Time `json:"resolved_at"`
}

func (BidIdentityVerdict) TableName() string { return "src_llm.bid_identity_verdict" }

// EnsureSchema creates the src_llm schema and migrates the suggestion tables.
func EnsureSchema(db *gorm.DB) error {
	if err := db.Exec(`CREATE SCHEMA IF NOT EXISTS src_llm`).Error; err != nil {
		return err
	}
	return db.AutoMigrate(&Run{}, &NamePairJudgment{}, &InfoboxExtraction{}, &BidIdentityVerdict{})
}

// hashInput is the resume key: a stable hex digest of the canonical input
// string for a task item.
func hashInput(parts ...string) string {
	h := sha256.New()
	for _, p := range parts {
		h.Write([]byte(p))
		h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil))
}
