package wikirescue

import (
	"context"
	"testing"

	"api/internal/platform/catalog/model"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// w140_test.go — the W1-pre bridge-nativization mirror steps (refs/proj/140,
// refs/plans/10-data-layer-retirement/02-w1pre-bridge-nativization.md).
//
// Every step is exercised the same way, because a mirror has four properties a
// fill-missing step does not and all four are load-bearing:
//
//	① the materialized rows carry the BRIDGE's values, column by column;
//	② the set-diff runs all three ways — insert a new row, UPDATE a stale one,
//	   DELETE one the wiki side no longer justifies;
//	③ rows OUTSIDE the ownership scope are not read, not updated, not deleted;
//	④ a second pass decides nothing (Insert=Update=Delete=0), which is what makes
//	   the step safe as a daily follow-up.
//
// TestMain / the pool wiring live in w2_test.go.

// mirror140GalgameIDs are the wiki body ids these tests own. Cleanup is a targeted
// DELETE, never a TRUNCATE: the galgame tables are shared with other suites.
var mirror140GalgameIDs = []int64{7401, 7402, 7403}

// mirror140TagIDs are the wiki tag vocabulary ids these tests own (names are
// 140-suffixed so the real table's UNIQUE(name) can never collide).
var mirror140TagIDs = []int64{74001, 74002, 74003}

// ensureMirrorStubs provisions every wiki table the p..t steps read. CREATE …
// IF NOT EXISTS is a no-op against the real schema, and the INSERT helpers always
// pass the real schema's defaultless NOT NULL columns.
func ensureMirrorStubs(t *testing.T) {
	t.Helper()
	ensureGalgameMediaStubs(t) // galgame (+ the intro columns) and the two media tables
	for _, col := range []string{"name_ja_jp", "name_en_us", "name_zh_cn", "name_zh_tw"} {
		require.NoError(t, testDB.Exec(
			`ALTER TABLE galgame ADD COLUMN IF NOT EXISTS `+col+` text NOT NULL DEFAULT ''`).Error)
	}
	// content_limit is the editorial display axis step q's second arm mirrors
	// (refs/proj/140 §5b); size/default copied from the wiki model.
	require.NoError(t, testDB.Exec(
		`ALTER TABLE galgame ADD COLUMN IF NOT EXISTS content_limit varchar(10) DEFAULT 'sfw'`).Error)
	for _, stmt := range []string{
		`CREATE TABLE IF NOT EXISTS galgame_alias (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			galgame_id bigint NOT NULL,
			name text NOT NULL DEFAULT '')`,
		`CREATE TABLE IF NOT EXISTS galgame_tag (
			id bigint PRIMARY KEY, name text NOT NULL UNIQUE,
			category text NOT NULL, description text DEFAULT '')`,
		`CREATE TABLE IF NOT EXISTS galgame_tag_relation (
			galgame_id bigint NOT NULL, tag_id bigint NOT NULL,
			spoiler_level bigint DEFAULT 0, source varchar(16) DEFAULT '',
			PRIMARY KEY (galgame_id, tag_id))`,
		`CREATE TABLE IF NOT EXISTS galgame_vndb_meta (
			galgame_id bigint PRIMARY KEY, vndb_id text NOT NULL, rating numeric,
			vote_count bigint NOT NULL, synced_at timestamptz NOT NULL)`,
		`CREATE TABLE IF NOT EXISTS galgame_bangumi_meta (
			galgame_id bigint PRIMARY KEY, bid bigint NOT NULL, score numeric NOT NULL,
			rank bigint NOT NULL, total bigint NOT NULL, nsfw boolean NOT NULL,
			synced_at timestamptz NOT NULL)`,
		`CREATE TABLE IF NOT EXISTS galgame_eg_meta (
			galgame_id bigint PRIMARY KEY, eg_game_id bigint NOT NULL, median bigint,
			vote_count bigint NOT NULL, synced_at timestamptz NOT NULL)`,
		`CREATE TABLE IF NOT EXISTS galgame_dlsite_meta (
			galgame_id bigint PRIMARY KEY, workno text NOT NULL, rate_average_star numeric,
			rate_count bigint, dl_count bigint, wishlist_count bigint, review_count bigint,
			synced_at timestamptz NOT NULL)`,
	} {
		require.NoError(t, testDB.Exec(stmt).Error)
	}
}

// resetMirror clears this suite's wiki rows and the catalog facet tables the
// mirror steps own, so each test starts from a known state.
func resetMirror(t *testing.T) {
	t.Helper()
	ensureMirrorStubs(t)
	require.NoError(t, testDB.Exec(`DELETE FROM galgame_tag_relation WHERE galgame_id IN ?`, mirror140GalgameIDs).Error)
	require.NoError(t, testDB.Exec(`DELETE FROM galgame_tag WHERE id IN ?`, mirror140TagIDs).Error)
	require.NoError(t, testDB.Exec(`DELETE FROM galgame_alias WHERE galgame_id IN ?`, mirror140GalgameIDs).Error)
	for _, tbl := range []string{"galgame_vndb_meta", "galgame_bangumi_meta", "galgame_eg_meta", "galgame_dlsite_meta"} {
		require.NoError(t, testDB.Exec(`DELETE FROM `+tbl+` WHERE galgame_id IN ?`, mirror140GalgameIDs).Error)
	}
	require.NoError(t, testDB.Exec(`DELETE FROM galgame WHERE id IN ?`, mirror140GalgameIDs).Error)
	for _, tbl := range []string{
		"catalog_work_title", "catalog_work_intro", "catalog_work_tag",
		"catalog_work_rating", "catalog_work_popularity", "catalog_external_ref",
		"catalog_tag_source_map", "catalog_tag", "catalog_work",
	} {
		require.NoError(t, testDB.Exec("TRUNCATE "+tbl+" CASCADE").Error)
	}
}

// mkClaimedWork creates a work CLAIMED by the given wiki body — the population
// every mirror step runs over (site + product_work_id, the read face's own
// partition key).
func mkClaimedWork(t *testing.T, galgameID int64, name string) int64 {
	t.Helper()
	site := siteGalgameWiki
	w := model.CatalogWork{
		MediumID: mediumGalgame, OLang: "ja", DisplayName: name,
		Site: &site, ProductWorkID: &galgameID,
	}
	require.NoError(t, testDB.Create(&w).Error)
	return w.ID
}

// mkBody inserts one wiki body with its four name and four intro columns.
func mkBody(t *testing.T, id int64, nameJa, nameEn, nameZhCN, nameZhTW, introJa, introEn, introZhCN string) {
	t.Helper()
	require.NoError(t, testDB.Exec(`INSERT INTO galgame
		(id, catalog_work_id, user_id, name_ja_jp, name_en_us, name_zh_cn, name_zh_tw,
		 intro_ja_jp, intro_en_us, intro_zh_cn, intro_zh_tw)
		VALUES (?, 0, 0, ?, ?, ?, ?, ?, ?, ?, '')`,
		id, nameJa, nameEn, nameZhCN, nameZhTW, introJa, introEn, introZhCN).Error)
}

func mkAlias(t *testing.T, galgameID int64, name string) {
	t.Helper()
	require.NoError(t, testDB.Exec(
		`INSERT INTO galgame_alias (galgame_id, name) VALUES (?, ?)`, galgameID, name).Error)
}

func mkTag(t *testing.T, id int64, name, category string) {
	t.Helper()
	require.NoError(t, testDB.Exec(
		`INSERT INTO galgame_tag (id, name, category) VALUES (?, ?, ?)`, id, name, category).Error)
}

func mkTagEdge(t *testing.T, galgameID, tagID int64, spoiler int, source string) {
	t.Helper()
	require.NoError(t, testDB.Exec(
		`INSERT INTO galgame_tag_relation (galgame_id, tag_id, spoiler_level, source) VALUES (?, ?, ?, ?)`,
		galgameID, tagID, spoiler, source).Error)
}

// runStepTwice applies a step and re-applies it, returning both ledgers — the
// convergence assertion every mirror step owes.
func runStepTwice(t *testing.T, step string) (first, second Stats) {
	t.Helper()
	ctx := context.Background()
	first, err := newRunner(t, true).runStep(ctx, step)
	require.NoError(t, err)
	second, err = newRunner(t, true).runStep(ctx, step)
	require.NoError(t, err)
	return first, second
}

// TestTitleMirror pins step p: the bridge's projection lands column for column
// (four official languages in pivot order, aliases with NO language, in wiki id
// order), an alias equal to an official name never lands, a stale row is UPDATEd
// and an orphan row DELETEd, the SEARCH_HINT lane is untouched, and the second
// pass decides nothing.
func TestTitleMirror(t *testing.T) {
	resetMirror(t)
	ctx := context.Background()

	work := mkClaimedWork(t, 7401, "titles")
	// The zh-Hant column is padded with an IDEOGRAPHIC space and a tab: the bridge
	// trims with strings.TrimSpace (every Unicode space), not SQL btrim.
	mkBody(t, 7401, "夏ノ音", "Natsu no Oto", "夏之音", "　夏之音（繁）\t", "", "", "")
	mkAlias(t, 7401, "なつのおと")
	mkAlias(t, 7401, "夏ノ音")    // == the ja official name → dropped
	mkAlias(t, 7401, "  ")     // blank → not a name
	mkAlias(t, 7401, "なつのおと ") // trims to an alias already seen → one row (the
	// wiki table's unique index forbids RAW duplicates, so the real-world
	// duplicate is exactly this whitespace variant — 4 bodies live)

	// A bodyless work's rows are outside the scope and must survive untouched.
	bodyless := mkWork(t, "bodyless-titles")
	require.NoError(t, testDB.Create(&model.CatalogWorkTitle{
		WorkID: bodyless, Lang: "ja", Title: "無関係", Kind: model.WorkTitleKindOfficial}).Error)
	// The claimed work's SEARCH_HINT row: a foreign lane (the dlsite release-attach
	// importer's kana), inside the claimed work but outside the mirror's scope.
	require.NoError(t, testDB.Create(&model.CatalogWorkTitle{
		WorkID: work, Lang: "ja", Title: "なつのおと(kana)", Kind: model.WorkTitleKindSearchHint}).Error)
	// A STALE official row (right key, wrong latin) → update; and an ORPHAN
	// official row the wiki body no longer carries → delete.
	latin := "stale-latin"
	require.NoError(t, testDB.Create(&model.CatalogWorkTitle{
		WorkID: work, Lang: "ja", Title: "夏ノ音", Kind: model.WorkTitleKindOfficial, Latin: &latin}).Error)
	require.NoError(t, testDB.Create(&model.CatalogWorkTitle{
		WorkID: work, Lang: "en", Title: "an old name the editor deleted", Kind: model.WorkTitleKindOfficial}).Error)

	dry, err := newRunner(t, false).runStep(ctx, "p")
	require.NoError(t, err)
	assert.Equal(t, 7, dry.Source, "4 name columns + 3 non-blank alias rows (a blank alias is not a source unit)")
	assert.Equal(t, 5, dry.Planned, "4 officials + 1 surviving alias")
	assert.Equal(t, 2, dry.Skipped, "the official-duplicate alias + the repeated alias")
	assert.Equal(t, 4, dry.Insert)
	assert.Equal(t, 1, dry.Update, "the stale latin")
	assert.Equal(t, 1, dry.Delete, "the deleted en name")
	assert.Zero(t, dry.Already)
	assert.Zero(t, dry.Written, "dry run writes nothing")
	var beforeApply int64
	require.NoError(t, testDB.Model(&model.CatalogWorkTitle{}).Count(&beforeApply).Error)
	assert.EqualValues(t, 4, beforeApply, "bodyless + search hint + stale + orphan: unchanged by a dry run")

	st, err := newRunner(t, true).runStep(ctx, "p")
	require.NoError(t, err)
	assert.Equal(t, 6, st.Written, "4 inserts + 1 update + 1 delete")
	assert.Equal(t, 1, st.Touched)

	var rows []model.CatalogWorkTitle
	require.NoError(t, testDB.Where("work_id = ?", work).Order("kind, id").Find(&rows).Error)
	require.Len(t, rows, 6, "4 officials + 1 alias + the untouched search hint")
	// Officials arrive in PIVOT order (the bridge's column order), which is what
	// the display lane's (kind, id) read reproduces.
	assert.Equal(t, []string{"ja", "en", "zh-Hans", "zh-Hant"},
		[]string{rows[0].Lang, rows[1].Lang, rows[2].Lang, rows[3].Lang})
	assert.Equal(t, "夏之音（繁）", rows[3].Title, "trimmed with Go's Unicode-wide TrimSpace")
	for _, r := range rows[:4] {
		assert.Equal(t, model.WorkTitleKindOfficial, r.Kind)
		assert.Nil(t, r.Latin, "the wiki body has no romaji column")
	}
	assert.Equal(t, model.WorkTitleKindAlias, rows[4].Kind)
	assert.Equal(t, "なつのおと", rows[4].Title)
	assert.Empty(t, rows[4].Lang, "an alias carries NO language")
	assert.Equal(t, model.WorkTitleKindSearchHint, rows[5].Kind, "the foreign hint lane survives")
	assert.Equal(t, "なつのおと(kana)", rows[5].Title)

	var keptBodyless int64
	require.NoError(t, testDB.Model(&model.CatalogWorkTitle{}).Where("work_id = ?", bodyless).Count(&keptBodyless).Error)
	assert.EqualValues(t, 1, keptBodyless, "a bodyless work's rows are out of scope")

	second, err := newRunner(t, true).runStep(ctx, "p")
	require.NoError(t, err)
	assert.Equal(t, 5, second.Already)
	assert.Zero(t, second.Insert+second.Update+second.Delete+second.Written+second.Touched, "converged")
}

// TestIntroMirror pins step q: the ja/en pivot lands with galgame_wiki
// attribution and provenance=source, the RAW column value is stored while
// EMPTINESS is judged on the trimmed text, zh is never written, a machine
// translation holding the same key is left strictly alone, and the second pass
// decides nothing.
func TestIntroMirror(t *testing.T) {
	resetMirror(t)
	ctx := context.Background()

	work := mkClaimedWork(t, 7401, "intros")
	other := mkClaimedWork(t, 7402, "intros-mt")
	// Leading/trailing whitespace on the ja intro must SURVIVE (the bridge tests
	// the trimmed text but emits the raw column); the en intro is whitespace-only
	// and yields no row; zh_cn is discarded by ruling ①.
	mkBody(t, 7401, "", "", "", "", "  日本語の紹介。  ", "   ", "中文简介")
	mkBody(t, 7402, "", "", "", "", "翻訳元", "", "")

	wikiSrc := sourceID(t, "galgame_wiki")
	// The intromt lane already owns (other, ja, galgame_wiki) with a MACHINE row.
	require.NoError(t, testDB.Create(&model.CatalogWorkIntro{
		WorkID: other, Lang: "ja", Intro: "machine text", SourceID: wikiSrc,
		Provenance: 1, SrcHash: "abc", MTModel: "glm"}).Error)
	// A stale source row on the first work → update.
	require.NoError(t, testDB.Create(&model.CatalogWorkIntro{
		WorkID: work, Lang: "ja", Intro: "outdated", SourceID: wikiSrc}).Error)
	// An orphan en row the body no longer justifies → delete.
	require.NoError(t, testDB.Create(&model.CatalogWorkIntro{
		WorkID: work, Lang: "en", Intro: "deleted upstream", SourceID: wikiSrc}).Error)

	dry, err := newRunner(t, false).runStep(ctx, "q")
	require.NoError(t, err)
	assert.Equal(t, 2, dry.Source, "the ja intro of each body; the blank en one is not text")
	assert.Equal(t, 1, dry.Planned, "the machine-held key is dropped from the plan")
	assert.Equal(t, 1, dry.Skipped)
	assert.Zero(t, dry.Insert)
	assert.Equal(t, 1, dry.Update)
	assert.Equal(t, 1, dry.Delete)

	st, err := newRunner(t, true).runStep(ctx, "q")
	require.NoError(t, err)
	assert.Equal(t, 2, st.Written)

	var got model.CatalogWorkIntro
	require.NoError(t, testDB.Where("work_id = ? AND lang = ?", work, "ja").First(&got).Error)
	assert.Equal(t, "  日本語の紹介。  ", got.Intro, "the RAW column value, whitespace and all")
	assert.Equal(t, wikiSrc, got.SourceID)
	assert.EqualValues(t, 0, got.Provenance)
	assert.Empty(t, got.SrcHash)
	assert.Empty(t, got.MTModel)

	var n int64
	require.NoError(t, testDB.Model(&model.CatalogWorkIntro{}).Where("work_id = ? AND lang = ?", work, "en").Count(&n).Error)
	assert.Zero(t, n, "the orphan en row is deleted")
	require.NoError(t, testDB.Model(&model.CatalogWorkIntro{}).Where("lang LIKE ?", "zh%").Count(&n).Error)
	assert.Zero(t, n, "zh is never mirrored (ruling ①)")

	var mt model.CatalogWorkIntro
	require.NoError(t, testDB.Where("work_id = ?", other).First(&mt).Error)
	assert.Equal(t, "machine text", mt.Intro, "the machine row is byte-identical")
	assert.EqualValues(t, 1, mt.Provenance)
	assert.Equal(t, "abc", mt.SrcHash)

	second, err := newRunner(t, true).runStep(ctx, "q")
	require.NoError(t, err)
	assert.Equal(t, 1, second.Already)
	assert.Zero(t, second.Insert+second.Update+second.Delete+second.Written+second.Touched, "converged")
}

// TestTagMirror pins step r: the relation ⋈ tag join lands with the bridge's
// source mapping, spoiler clamp and sexual flag, spoiler=2 edges included (the
// mirror holds the whole truth — the ceiling moved to the read face), the
// bangumi/dlsite folksonomy rows on the same work are untouched, catalog_tag.sexual
// is corrected both ways, and the second pass decides nothing.
func TestTagMirror(t *testing.T) {
	resetMirror(t)
	ctx := context.Background()

	work := mkClaimedWork(t, 7401, "tags")
	mkBody(t, 7401, "", "", "", "", "", "", "")
	mkTag(t, 74001, "純愛-140", "content")
	mkTag(t, 74002, "強姦-140", "sexual")
	mkTag(t, 74003, "実写-140", "technical")
	mkTagEdge(t, 7401, 74001, 0, "")     // user-curated → galgame_wiki
	mkTagEdge(t, 7401, 74002, 9, "vndb") // clamped to 2; sexual category
	mkTagEdge(t, 7401, 74003, -3, "")    // clamped to 0

	wikiSrc, vndbSrc, bgmSrc := sourceID(t, "galgame_wiki"), sourceID(t, "vndb"), sourceID(t, "bangumi")
	// A bangumi folksonomy row on the SAME work: the step-88 importer's property,
	// a red line for this step.
	require.NoError(t, testDB.Create(&model.CatalogWorkTag{
		WorkID: work, Name: "百合", Count: 24, SourceID: bgmSrc}).Error)
	// A stale wiki-lane row (wrong spoiler + sexual) → update; and an orphan one
	// the wiki side dropped → delete.
	require.NoError(t, testDB.Create(&model.CatalogWorkTag{
		WorkID: work, Name: "純愛-140", SourceID: wikiSrc, Spoiler: 2, Sexual: true}).Error)
	require.NoError(t, testDB.Create(&model.CatalogWorkTag{
		WorkID: work, Name: "撤回されたタグ", SourceID: vndbSrc}).Error)

	// The canonical vocabulary: one tag anchored to the SEXUAL wiki tag (must be
	// promoted) and one wrongly flagged sexual (must be demoted).
	promote := model.CatalogTag{Name: "canon-sexual-140", Tier: 0, Kind: 0}
	require.NoError(t, testDB.Create(&promote).Error)
	demote := model.CatalogTag{Name: "canon-plain-140", Tier: 0, Kind: 0, Sexual: true}
	require.NoError(t, testDB.Create(&demote).Error)
	require.NoError(t, testDB.Create(&model.CatalogExternalRef{
		EntityType: model.EntityTypeTag, EntityID: promote.ID, SourceID: wikiSrc,
		ExternalID: "74002", LinkKind: model.LinkKindExact}).Error)
	require.NoError(t, testDB.Create(&model.CatalogExternalRef{
		EntityType: model.EntityTypeTag, EntityID: demote.ID, SourceID: wikiSrc,
		ExternalID: "74001", LinkKind: model.LinkKindExact}).Error)

	dry, err := newRunner(t, false).runStep(ctx, "r")
	require.NoError(t, err)
	// Source is the WHOLE wiki join for this step (the ledger figure the design
	// reconciles against), so it also counts the bodies other suites leave in the
	// shared test database; Planned is the claim-scoped number.
	assert.GreaterOrEqual(t, dry.Source, 3)
	assert.Equal(t, 3, dry.Planned)
	assert.Equal(t, 2, dry.Insert)
	assert.Equal(t, 1, dry.Update)
	assert.Equal(t, 1, dry.Delete)
	assert.Equal(t, 2, dry.Vocab, "one promotion + one demotion")
	var stillSexual bool
	require.NoError(t, testDB.Raw(`SELECT sexual FROM catalog_tag WHERE id = ?`, demote.ID).Scan(&stillSexual).Error)
	assert.True(t, stillSexual, "dry run writes nothing")

	st, err := newRunner(t, true).runStep(ctx, "r")
	require.NoError(t, err)
	assert.Equal(t, 4, st.Written)
	assert.Equal(t, 2, st.Vocab)

	var rows []model.CatalogWorkTag
	require.NoError(t, testDB.Where("work_id = ?", work).Order("name").Find(&rows).Error)
	require.Len(t, rows, 4, "3 wiki rows + the untouched bangumi row")
	byName := map[string]model.CatalogWorkTag{}
	for _, r := range rows {
		byName[r.Name] = r
	}
	pure := byName["純愛-140"]
	assert.Equal(t, wikiSrc, pure.SourceID, "an unsourced edge is wiki curation")
	assert.EqualValues(t, 0, pure.Spoiler, "the stale spoiler 2 is corrected")
	assert.False(t, pure.Sexual, "and the stale sexual flag with it")
	assert.Zero(t, pure.Count, "the wiki tag layer has no votes")
	rape := byName["強姦-140"]
	assert.Equal(t, vndbSrc, rape.SourceID)
	assert.EqualValues(t, 2, rape.Spoiler, "spoiler_level 9 clamps to 2, NOT filtered out")
	assert.True(t, rape.Sexual)
	assert.EqualValues(t, 0, byName["実写-140"].Spoiler, "a negative spoiler_level clamps to 0")
	assert.False(t, byName["実写-140"].Sexual, "technical is not sexual")
	bgm := byName["百合"]
	assert.Equal(t, bgmSrc, bgm.SourceID)
	assert.Equal(t, 24, bgm.Count, "the bangumi row is byte-identical")
	assert.EqualValues(t, 0, bgm.Spoiler)
	assert.False(t, bgm.Sexual)

	var promoted, demoted bool
	require.NoError(t, testDB.Raw(`SELECT sexual FROM catalog_tag WHERE id = ?`, promote.ID).Scan(&promoted).Error)
	require.NoError(t, testDB.Raw(`SELECT sexual FROM catalog_tag WHERE id = ?`, demote.ID).Scan(&demoted).Error)
	assert.True(t, promoted, "anchored to a sexual-category wiki tag")
	assert.False(t, demoted, "anchored to a content-category one")

	second, err := newRunner(t, true).runStep(ctx, "r")
	require.NoError(t, err)
	assert.Equal(t, 3, second.Already)
	assert.Zero(t, second.Insert+second.Update+second.Delete+second.Written+second.Touched, "converged")
	assert.Zero(t, second.Vocab, "and the vocabulary is in step")
}

// TestRatingVndbMirror pins step s: the kana wire scale is decoded ÷10 and stored
// so it reads back as the EXACT float64 the bridge produced, a NULL rating never
// becomes a row, rank stays NULL, the sibling sources' rows are outside the scope,
// and the second pass decides nothing.
func TestRatingVndbMirror(t *testing.T) {
	resetMirror(t)

	work := mkClaimedWork(t, 7401, "vndb-rated")
	unrated := mkClaimedWork(t, 7402, "vndb-unrated")
	mkBody(t, 7401, "", "", "", "", "", "", "")
	mkBody(t, 7402, "", "", "", "", "", "", "")
	// 82.34 is the ulp case: 82.34/10 in float64 is NOT the nearest double to the
	// numeric quotient 8.234, so the stored decimal has to come from the float64.
	require.NoError(t, testDB.Exec(`INSERT INTO galgame_vndb_meta
		(galgame_id, vndb_id, rating, vote_count, synced_at) VALUES (?, 'v1', 82.34, 1234, now())`, 7401).Error)
	require.NoError(t, testDB.Exec(`INSERT INTO galgame_vndb_meta
		(galgame_id, vndb_id, rating, vote_count, synced_at) VALUES (?, 'v2', NULL, 0, now())`, 7402).Error)

	bgmSrc := sourceID(t, "bangumi")
	// A bangumi rating on the same work: the importer's property since the claim
	// guard came off, and outside step s's scope.
	require.NoError(t, testDB.Create(&model.CatalogWorkRating{
		WorkID: work, SourceID: bgmSrc, Score: 7.4, VoteCount: 42}).Error)

	first, second := runStepTwice(t, "s")
	// Source is the WHOLE rated-meta read for this step, so it also counts the rows
	// other suites leave in the shared test database; that the NULL-rating row is
	// filtered shows up claim-scoped, in Insert here and in the unrated work's empty
	// rating set below.
	assert.GreaterOrEqual(t, first.Source, 1)
	assert.Equal(t, 1, first.Insert)
	assert.Equal(t, 1, first.Written)
	assert.Zero(t, second.Insert+second.Update+second.Delete+second.Written, "converged")
	assert.Equal(t, 1, second.Already)

	var got model.CatalogWorkRating
	require.NoError(t, testDB.Where("work_id = ? AND source_id = ?", work, sourceID(t, "vndb")).First(&got).Error)
	assert.Equal(t, 82.34/10, got.Score, "bit-identical to the bridge's float64 division")
	assert.Equal(t, 1234, got.VoteCount)
	assert.Nil(t, got.Rank, "the vndb meta table carries no rank")

	var n int64
	require.NoError(t, testDB.Model(&model.CatalogWorkRating{}).Where("work_id = ?", unrated).Count(&n).Error)
	assert.Zero(t, n, "no fake zero for a VN VNDB publishes no rating for")
	var bgm model.CatalogWorkRating
	require.NoError(t, testDB.Where("work_id = ? AND source_id = ?", work, bgmSrc).First(&bgm).Error)
	assert.Equal(t, 42, bgm.VoteCount, "the bangumi row is untouched")
}

// TestMetaAdopt pins step t: the three source lanes and the DLsite counter trio
// land with the bridge's filters and decodings, an unpublished counter never
// becomes a row while a published 0 does, the vndb row and the bangumi POPULARITY
// shelves stay outside the scope, an extra row is KEPT (no delete arm — the
// importers own these rows now), and the second pass decides nothing.
func TestMetaAdopt(t *testing.T) {
	resetMirror(t)

	work := mkClaimedWork(t, 7401, "meta-full")
	unscored := mkClaimedWork(t, 7402, "meta-unscored")
	mkBody(t, 7401, "", "", "", "", "", "", "")
	mkBody(t, 7402, "", "", "", "", "", "", "")

	require.NoError(t, testDB.Exec(`INSERT INTO galgame_bangumi_meta
		(galgame_id, bid, score, rank, total, nsfw, synced_at)
		VALUES (?, 1, 7.4, 321, 42, false, now()), (?, 2, 0, 0, 0, false, now())`, 7401, 7402).Error)
	require.NoError(t, testDB.Exec(`INSERT INTO galgame_eg_meta
		(galgame_id, eg_game_id, median, vote_count, synced_at)
		VALUES (?, 1, 78, 40, now()), (?, 2, NULL, 0, now())`, 7401, 7402).Error)
	// dl_count unpublished (NULL → no row), review_count a published 0 (→ a row).
	require.NoError(t, testDB.Exec(`INSERT INTO galgame_dlsite_meta
		(galgame_id, workno, rate_average_star, rate_count, dl_count, wishlist_count, review_count, synced_at)
		VALUES (?, 'RJ140', 4.36, 120, NULL, 300, 0, now())`, 7401).Error)
	// A rated-but-vote-less dlsite row: the pair lives and dies together.
	require.NoError(t, testDB.Exec(`INSERT INTO galgame_dlsite_meta
		(galgame_id, workno, rate_average_star, rate_count, dl_count, wishlist_count, review_count, synced_at)
		VALUES (?, 'RJ141', 4.9, 0, NULL, NULL, NULL, now())`, 7402).Error)

	vndbSrc, dlSrc := sourceID(t, "vndb"), sourceID(t, "dlsite")
	// Outside the scope: the vndb rating (step s owns it) and a bangumi favorite
	// shelf (metric 10, the T2b importer's).
	require.NoError(t, testDB.Create(&model.CatalogWorkRating{
		WorkID: work, SourceID: vndbSrc, Score: 8.234, VoteCount: 1234}).Error)
	require.NoError(t, testDB.Create(&model.CatalogWorkPopularity{
		WorkID: work, SourceID: sourceID(t, "bangumi"), Metric: model.PopularityMetricBgmWish, Value: 99}).Error)
	// An EXTRA dlsite counter the wiki meta does not justify: kept, because the
	// importer owns this lane from now on.
	require.NoError(t, testDB.Create(&model.CatalogWorkPopularity{
		WorkID: work, SourceID: dlSrc, Metric: model.PopularityMetricDownloads, Value: 2000}).Error)

	first, second := runStepTwice(t, "t")
	// One shared step ledger folds BOTH arms: 3 ratings (bangumi + dlsite + eg)
	// plus 2 popularity counters (wishlist + the published-0 reviews; the
	// pre-existing downloads row is the importers' and is neither desired nor
	// deleted).
	assert.Equal(t, 5, first.Insert)
	assert.Zero(t, second.Insert+second.Update+second.Delete+second.Written, "converged")

	var ratings []model.CatalogWorkRating
	require.NoError(t, testDB.Where("work_id = ?", work).Order("source_id").Find(&ratings).Error)
	require.Len(t, ratings, 4, "vndb (out of scope) + the three adopted")
	bySrc := map[int16]model.CatalogWorkRating{}
	for _, r := range ratings {
		bySrc[r.SourceID] = r
	}
	assert.Equal(t, 8.234, bySrc[vndbSrc].Score, "step s's row is untouched")
	bgm := bySrc[sourceID(t, "bangumi")]
	assert.Equal(t, 7.4, bgm.Score)
	assert.Equal(t, 42, bgm.VoteCount, "vote_count is the meta's total")
	require.NotNil(t, bgm.Rank)
	assert.Equal(t, 321, *bgm.Rank)
	assert.Equal(t, 4.36, bySrc[dlSrc].Score, "DLsite's own 0-5 star average")
	assert.Equal(t, 120, bySrc[dlSrc].VoteCount)
	assert.Nil(t, bySrc[dlSrc].Rank)
	assert.Equal(t, float64(78), bySrc[sourceID(t, "erogamespace")].Score, "EG's 0-100 median, unnormalized")

	var unscoredRatings int64
	require.NoError(t, testDB.Model(&model.CatalogWorkRating{}).Where("work_id = ?", unscored).Count(&unscoredRatings).Error)
	assert.Zero(t, unscoredRatings, "score 0 / NULL median / vote-less star are all skipped")

	var pops []model.CatalogWorkPopularity
	require.NoError(t, testDB.Where("work_id = ? AND source_id = ?", work, dlSrc).Order("metric").Find(&pops).Error)
	require.Len(t, pops, 3, "the KEPT downloads row + wishlist + the published 0 reviews")
	assert.Equal(t, model.PopularityMetricDownloads, pops[0].Metric)
	assert.EqualValues(t, 2000, pops[0].Value, "an unjustified row is kept, not deleted")
	assert.Equal(t, model.PopularityMetricWishlist, pops[1].Metric)
	assert.EqualValues(t, 300, pops[1].Value)
	assert.Equal(t, model.PopularityMetricReviews, pops[2].Metric)
	assert.EqualValues(t, 0, pops[2].Value, "a published 0 IS a row")

	var shelf model.CatalogWorkPopularity
	require.NoError(t, testDB.Where("work_id = ? AND metric = ?", work, model.PopularityMetricBgmWish).First(&shelf).Error)
	assert.EqualValues(t, 99, shelf.Value, "the bangumi shelves are outside the scope")
}

// TestMirrorStepsSkipUnclaimed pins the population boundary: a wiki body whose
// work is NOT claimed (or is soft-deleted) contributes nothing to any mirror step,
// because the read face would never have bridged it either.
func TestMirrorStepsSkipUnclaimed(t *testing.T) {
	resetMirror(t)
	ctx := context.Background()

	// 7401: a body with no catalog_work at all. 7402: claimed by a SOFT-DELETED
	// work. 7403: a body whose work is BODYLESS (site empty) and merely points at
	// it — not a claim.
	mkBody(t, 7401, "orphan", "", "", "", "orphan intro", "", "")
	mkBody(t, 7402, "deleted", "", "", "", "deleted intro", "", "")
	mkBody(t, 7403, "bodyless", "", "", "", "bodyless intro", "", "")
	dead := mkClaimedWork(t, 7402, "soft-deleted")
	require.NoError(t, testDB.Exec(`UPDATE catalog_work SET deleted_at = now() WHERE id = ?`, dead).Error)
	pointer := mkWork(t, "not-a-claim")
	require.NoError(t, testDB.Exec(`UPDATE catalog_work SET product_work_id = ? WHERE id = ?`, 7403, pointer).Error)

	for _, step := range []string{"p", "q", "r", "s", "t"} {
		st, err := newRunner(t, true).runStep(ctx, step)
		require.NoError(t, err, "step %s", step)
		assert.Zero(t, st.Planned, "step %s plans nothing for an unclaimed body", step)
		assert.Zero(t, st.Written, "step %s writes nothing", step)
	}
	for _, tbl := range []string{"catalog_work_title", "catalog_work_intro", "catalog_work_tag"} {
		var n int64
		require.NoError(t, testDB.Table(tbl).Count(&n).Error)
		assert.Zero(t, n, "%s stayed empty", tbl)
	}
}

// setBodyLimit sets one wiki body's editorial display flag.
func setBodyLimit(t *testing.T, galgameID int64, limit string) {
	t.Helper()
	require.NoError(t, testDB.Exec(
		`UPDATE galgame SET content_limit = ? WHERE id = ?`, limit, galgameID).Error)
}

// displayNSFW reads one work's editorial display flag back.
func displayNSFW(t *testing.T, workID int64) bool {
	t.Helper()
	var got bool
	require.NoError(t, testDB.Raw(
		`SELECT display_nsfw FROM catalog_work WHERE id = ?`, workID).Scan(&got).Error)
	return got
}

// TestDisplayNSFWMirror pins step q's SECOND arm — the A2-R5 editorial display
// axis nativized onto catalog_work.display_nsfw (refs/proj/140 §5b).
//
// The four cases are the whole projection: the wiki 'nsfw' spelling is the ONLY
// true, every other value (including a body that is simply gone) is false, both
// directions are corrected so the column converges, and a BODYLESS work's column
// is outside the scope — it is never read by the display projection and must not
// be written by this step. The bodies carry no intro text, so the step's Touched
// counts display flips alone.
func TestDisplayNSFWMirror(t *testing.T) {
	resetMirror(t)
	ctx := context.Background()

	mkBody(t, 7401, "", "", "", "", "", "", "")
	mkBody(t, 7402, "", "", "", "", "", "", "")
	mkBody(t, 7403, "", "", "", "", "", "", "")
	setBodyLimit(t, 7401, "nsfw")
	setBodyLimit(t, 7402, "sfw")
	setBodyLimit(t, 7403, "nsfw")

	promote := mkClaimedWork(t, 7401, "wiki says nsfw")
	stays := mkClaimedWork(t, 7402, "wiki says sfw")
	already := mkClaimedWork(t, 7403, "already flagged")
	// A claim whose wiki body is GONE declares nothing → false, so a stale true
	// has to come back down.
	demote := mkClaimedWork(t, 7499, "body vanished")
	bodyless := mkWork(t, "no claim at all")
	require.NoError(t, testDB.Exec(
		`UPDATE catalog_work SET display_nsfw = true WHERE id IN ?`,
		[]int64{already, demote, bodyless}).Error)

	dry, err := newRunner(t, false).runStep(ctx, "q")
	require.NoError(t, err)
	assert.Equal(t, 2, dry.Scalar, "one promotion and one demotion decided")
	assert.Equal(t, 2, dry.Touched, "the forecast marks exactly the flipping works")
	assert.False(t, displayNSFW(t, promote), "a dry run writes nothing")
	assert.True(t, displayNSFW(t, demote), "a dry run writes nothing")

	st, err := newRunner(t, true).runStep(ctx, "q")
	require.NoError(t, err)
	assert.Equal(t, 2, st.Scalar)
	assert.True(t, displayNSFW(t, promote), "wiki 'nsfw' → true")
	assert.False(t, displayNSFW(t, stays), "wiki 'sfw' → false")
	assert.True(t, displayNSFW(t, already), "left alone, already correct")
	assert.False(t, displayNSFW(t, demote), "no body declares nothing → false")
	assert.True(t, displayNSFW(t, bodyless), "a bodyless work's column is outside the scope")

	second, err := newRunner(t, true).runStep(ctx, "q")
	require.NoError(t, err)
	assert.Zero(t, second.Scalar, "converged")
	assert.Zero(t, second.Touched, "and touches nothing")
}

// TestTagVocabularySexualIgnoresNonExactAndForeignAnchors pins the anchor
// discipline of step r's vocabulary arm — the assertion that moved here from the
// read face (service.TestTagSexualIgnoresNonExactAndForeignAnchors) when the
// derivation itself did.
//
// Only the EXACT galgame_wiki tag anchor may set catalog_tag.sexual. A probable
// anchor is an unreviewed hypothesis, and another source's anchor is a different
// key space that happens to spell the same digits — neither may flip a safety flag.
func TestTagVocabularySexualIgnoresNonExactAndForeignAnchors(t *testing.T) {
	resetMirror(t)
	ctx := context.Background()

	mkTag(t, 74002, "エロ-140", "sexual")
	wikiSrc, vndbSrc := sourceID(t, "galgame_wiki"), sourceID(t, "vndb")

	probable := model.CatalogTag{Name: "probable-140", Tier: 0, Kind: 0}
	require.NoError(t, testDB.Create(&probable).Error)
	foreign := model.CatalogTag{Name: "foreign-140", Tier: 0, Kind: 0}
	require.NoError(t, testDB.Create(&foreign).Error)
	require.NoError(t, testDB.Create(&model.CatalogExternalRef{
		EntityType: model.EntityTypeTag, EntityID: probable.ID, SourceID: wikiSrc,
		ExternalID: "74002", LinkKind: model.LinkKindProbable}).Error)
	require.NoError(t, testDB.Create(&model.CatalogExternalRef{
		EntityType: model.EntityTypeTag, EntityID: foreign.ID, SourceID: vndbSrc,
		ExternalID: "74002", LinkKind: model.LinkKindExact}).Error)

	st, err := newRunner(t, true).runStep(ctx, "r")
	require.NoError(t, err)
	assert.Zero(t, st.Vocab, "neither anchor justifies a flag")
	for _, tc := range []struct {
		id   int64
		name string
	}{{probable.ID, "a PROBABLE anchor"}, {foreign.ID, "another source's anchor"}} {
		var sexual bool
		require.NoError(t, testDB.Raw(`SELECT sexual FROM catalog_tag WHERE id = ?`, tc.id).Scan(&sexual).Error)
		assert.False(t, sexual, "%s must not flip the sexual flag", tc.name)
	}
}
