package model

import "time"

type AIUsage struct {
	ID               int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site             string    `gorm:"not null;column:site" json:"site"`
	Route            string    `gorm:"not null;column:route" json:"route"`
	Status           int16     `gorm:"not null;column:status" json:"status"`
	Channel          string    `gorm:"not null;default:'';column:channel" json:"channel"`
	PromptTokens     int       `gorm:"not null;default:0;type:integer;column:prompt_tokens" json:"prompt_tokens"`
	CompletionTokens int       `gorm:"not null;default:0;type:integer;column:completion_tokens" json:"completion_tokens"`
	CostMicro        int64     `gorm:"not null;default:0;column:cost_micro" json:"cost_micro"`
	LatencyMs        int       `gorm:"not null;default:0;type:integer;column:latency_ms" json:"latency_ms"`
	CreatedAt        time.Time `gorm:"not null;default:now();column:created_at" json:"created_at"`
}

func (AIUsage) TableName() string { return "ai_usage" }
