package model

import "time"

// AIUsage is one metered row per gateway call (doc 20 §5): tenant × route ×
// channel × cost × latency × status. Written best-effort AFTER the main return
// so a metering failure never fails the caller's moderation result.
//
// Column discipline (章程 ruling 8):
//   - site / route / status are INTENT columns → NOT NULL, NO default. status=0
//     (ok) is a meaningful zero, so a `default:0` would let the GORM zero-value
//     INSERT trap silently stamp ok on an omitted field.
//   - prompt_tokens / completion_tokens / cost_micro / latency_ms are BOOKKEEPING
//     counters → a legitimate 0 (nothing billed / instantaneous), so default 0 is
//     correct and lets a partial write still land.
//   - channel default ” is a DELIBERATE semantic (documented on the field), not
//     the zero-value trap: ” means "no upstream channel was hit" (degraded).
type AIUsage struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// Site is the tenant, DERIVED from the S2S client's catalog_site — never on
	// the wire (invariant 3). Route is the semantic route (v0 always
	// moderate-text). Both intent columns.
	Site   string `gorm:"not null;column:site" json:"site"`
	Route  string `gorm:"not null;column:route" json:"route"`
	Status int16  `gorm:"not null;column:status" json:"status"`
	// Channel is the actual upstream channel/model recorded from the response (or
	// the requested model when the response omits it). '' when degraded — a
	// deliberate default, distinct from a real channel name.
	Channel string `gorm:"not null;default:'';column:channel" json:"channel"`
	// Bookkeeping counters. Token counts / latency are 32-bit (type:integer pins
	// them so Go int does not widen to bigint — matching the spec DDL). cost_micro
	// is micro-currency (channel unit price × tokens) and stays bigint; v0 leaves
	// it 0 until pricing is configured (trigger-based), so the budget fuse is
	// present but inert on real traffic until then.
	PromptTokens     int       `gorm:"not null;default:0;type:integer;column:prompt_tokens" json:"prompt_tokens"`
	CompletionTokens int       `gorm:"not null;default:0;type:integer;column:completion_tokens" json:"completion_tokens"`
	CostMicro        int64     `gorm:"not null;default:0;column:cost_micro" json:"cost_micro"`
	LatencyMs        int       `gorm:"not null;default:0;type:integer;column:latency_ms" json:"latency_ms"`
	CreatedAt        time.Time `gorm:"not null;default:now();column:created_at" json:"created_at"`
}

func (AIUsage) TableName() string { return "ai_usage" }
