// Package model holds the GORM models of the kun_community database — the
// community primitive's storage layer (doc 11 §4). ONE multi-tenant discussion
// service whose only unit is a thread; the anchor decides the three shapes
// (board topic / entity-resource comments / feedback with a status flow).
//
// Storage conventions (see also the doc 11 invariant references on each model):
//
//   - Identity primary keys are `bigint GENERATED BY DEFAULT AS IDENTITY`
//     (the catalog recipe — every part of the tag is load-bearing; see
//     internal/platform/catalog/model/person.go for the full rationale).
//     Tables whose PK is an externally-supplied global user id (community_trust)
//     use a plain non-identity PK instead.
//   - Deletion is a status tombstone, NEVER gorm.DeletedAt (invariant 13): a
//     deleted post keeps its post_number so the thread numbering never
//     collapses. No model here carries a soft-delete column.
//   - Every row is tenant-stamped with `site` and all access indexes lead with
//     the tenant (invariant 7).
//   - Fields whose ZERO value is meaningful (kind / status / content_rating /
//     level / format / notification_level ...) are `not null` WITHOUT a gorm
//     default tag: a default tag makes GORM omit the zero from INSERTs and the
//     DB default silently wins (the catalog trust_tier lesson). The value is
//     always written explicitly by the service layer. App-maintained counters
//     (posts_count, first_posts_held_remaining ...) keep their DDL default —
//     their creation-time value is fixed, not a meaningful caller choice.
//
// These are CODE-COUPLED enum constants: adding a value ships with new code, so
// smallint constants are the right form. All values are persisted; NEVER
// renumber an existing constant.
package model

// Thread kinds (community_thread.kind) — the anchor-driven shape discriminator
// (invariant 3). topic/comments/feedback are one storage, not three tables.
const (
	ThreadKindTopic    int16 = 0 // board topic: has title/header image, one board many threads
	ThreadKindComments int16 = 1 // entity/resource comments: no title, ONE thread per anchor (invariant 4)
	ThreadKindFeedback int16 = 2 // feedback: title + status flow, one anchor many threads
)

// Anchor kinds (community_thread.anchor_kind) — what the thread is anchored to
// (invariant 2: anchor a STABLE internal id, URL mapping kept separate).
// anchor_id stores the local id for site anchors, the prefixed entity id (e.g.
// "w345") for catalog anchors.
const (
	AnchorKindBoard         int16 = 0 // community_board.id
	AnchorKindSiteGame      int16 = 1 // a site's local game id
	AnchorKindSiteResource  int16 = 2 // a site's local resource id
	AnchorKindCatalogWork   int16 = 3 // catalog work entity
	AnchorKindCatalogPerson int16 = 4 // catalog person entity
)

// Content rating (community_thread.content_rating + community_post.content_rating)
// — day-1 field (invariant 12), default inherited from the anchor by the
// service layer. NextMoe's R18 wall depends on this being present from the
// start; back-filling a rating later means a full re-label.
const (
	ContentRatingAll int16 = 0 // all ages
	ContentRatingR15 int16 = 1
	ContentRatingR18 int16 = 2
)

// Thread status (community_thread.status). status=deleted is the tombstone
// (invariant 13) and drops the thread out of the per-anchor comments unique
// (invariant 4), allowing a fresh thread for the same anchor.
const (
	ThreadStatusOpen    int16 = 0
	ThreadStatusClosed  int16 = 1
	ThreadStatusHidden  int16 = 2
	ThreadStatusDeleted int16 = 3
)

// Feedback status (community_thread.fb_status; kind=feedback only, else NULL) —
// the Fider/Canny status flow.
const (
	FeedbackStatusOpen      int16 = 0
	FeedbackStatusConfirmed int16 = 1
	FeedbackStatusPlanned   int16 = 2
	FeedbackStatusFixed     int16 = 3
	FeedbackStatusDeclined  int16 = 4
	FeedbackStatusDuplicate int16 = 5
)

// Post status (community_post.status). hidden = flag-auto-hidden / held;
// deleted = tombstone (content cleared, post_number preserved).
const (
	PostStatusVisible int16 = 0
	PostStatusHidden  int16 = 1
	PostStatusDeleted int16 = 2
)

// Reaction kinds (community_reaction.kind). Starts from a single value (open
// decision doc 11 §10.1, leaning "like" only); more kinds are additive.
const (
	ReactionKindLike int16 = 0
)

// Notification level (community_thread_user.notification_level) — Discourse
// tracking states. 0=muted is a meaningful zero, so the column carries no DB
// default; the service layer writes normal(1) for auto-created interaction rows.
const (
	NotificationLevelMuted    int16 = 0
	NotificationLevelNormal   int16 = 1
	NotificationLevelTracking int16 = 2
	NotificationLevelWatching int16 = 3
)

// Board format (community_board.format) — the GitHub Discussions category
// format.
const (
	BoardFormatDiscussion   int16 = 0
	BoardFormatQA           int16 = 1
	BoardFormatAnnouncement int16 = 2
)

// Trust level (community_trust.level) — TL0-4 (invariant 8). TL4 is granted by
// humans only; the metering columns drive TL1-3 promotion (service layer, 03).
const (
	TrustLevelNew     int16 = 0 // TL0: newcomer sandbox
	TrustLevelBasic   int16 = 1 // TL1
	TrustLevelMember  int16 = 2 // TL2
	TrustLevelRegular int16 = 3 // TL3
	TrustLevelLeader  int16 = 4 // TL4 (manual only)
)

// Granted-boost source (community_trust.granted_boost; NULL = no boost) — the
// starter-bonus origin (SE association-bonus localized): veterans and creators
// skip the TL0 cold start, spam accounts still climb from TL0 everywhere.
const (
	GrantedBoostNone    int16 = 0
	GrantedBoostVeteran int16 = 1 // established old-site account age + tenure
	GrantedBoostCreator int16 = 2
	GrantedBoostStaff   int16 = 3
)

// Flag reason (community_flag.reason; NULL = unspecified) — finalized (step 03).
// Values 0-3 are kept from the step-02 provisional set (never renumber a
// persisted value); nsfw_mislabel is appended. Slot 1 is renamed Offensive→
// Abuse (same meaning, sharper word). The maintenance-community bias: mislabeled
// content rating (nsfw_mislabel) is its own reason because a resource site's
// primary report is "this is tagged wrong", not "this is abuse".
const (
	FlagReasonSpam         int16 = 0
	FlagReasonAbuse        int16 = 1
	FlagReasonOffTopic     int16 = 2
	FlagReasonOther        int16 = 3
	FlagReasonNsfwMislabel int16 = 4
)

// Flag status (community_flag.status) — the reviewer's disposition, feeding the
// reporter's historical accuracy weight.
const (
	FlagStatusPending   int16 = 0
	FlagStatusAgreed    int16 = 1
	FlagStatusDisagreed int16 = 2
	FlagStatusIgnored   int16 = 3
)

// Review-item source (community_review_item.source; NULL = unspecified) — why
// the post entered the centralized queue (Coral multi-site single queue).
const (
	ReviewSourceFlags         int16 = 0
	ReviewSourceFirstPostHold int16 = 1
	ReviewSourceSuspectWords  int16 = 2
	ReviewSourceExternal      int16 = 3 // external moderation-service callback
)

// Review-item status (community_review_item.status).
const (
	ReviewStatusPending  int16 = 0
	ReviewStatusApproved int16 = 1
	ReviewStatusRejected int16 = 2
)
