package model

import "time"

// CommunityThreadUser is the SPARSE unread/subscription row (Discourse
// topic_users): a row exists only once a user has interacted with a thread.
// Unread = thread.highest_post_number − last_read_post_number. Composite PK
// (thread_id, user_id); no FK (hot, sparse), no timestamps beyond last visit.
type CommunityThreadUser struct {
	ThreadID int64 `gorm:"primaryKey;autoIncrement:false;column:thread_id" json:"thread_id"`
	UserID   int64 `gorm:"primaryKey;autoIncrement:false;column:user_id" json:"user_id"`
	// LastReadPostNumber is app-maintained; its creation value is 0, so the DDL
	// default stays.
	LastReadPostNumber int32 `gorm:"not null;default:0;column:last_read_post_number" json:"last_read_post_number"`
	// NotificationLevel uses the NotificationLevel* constants. 0=muted is a
	// meaningful zero, so NO default tag — the service writes normal(1) for
	// auto-created rows explicitly.
	NotificationLevel int16      `gorm:"not null;column:notification_level" json:"notification_level"`
	LastVisitedAt     *time.Time `gorm:"column:last_visited_at" json:"last_visited_at"`
}

func (CommunityThreadUser) TableName() string { return "community_thread_user" }

// CommunityBoard is a board — the anchor of a topic thread (invariant 3,
// anchor_kind=board). letmoe starts with a single default board per site
// (board management is a later surface). UNIQUE(site, slug) keeps slugs
// per-tenant.
type CommunityBoard struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// Site leads the uniqueness key (invariant 7).
	Site string `gorm:"not null;uniqueIndex:uq_community_board_site_slug,priority:1;column:site" json:"site"`
	Name string `gorm:"not null;column:name" json:"name"`
	// Slug is nullable (NULLs distinct under the unique); Position/Description
	// are optional presentation fields.
	Slug        *string `gorm:"uniqueIndex:uq_community_board_site_slug,priority:2;column:slug" json:"slug"`
	Position    *int32  `gorm:"column:position" json:"position"`
	Description *string `gorm:"column:description" json:"description"`
	// Format uses the BoardFormat* constants; 0=discussion is a meaningful zero,
	// so NO default tag.
	Format int16 `gorm:"not null;column:format" json:"format"`
}

func (CommunityBoard) TableName() string { return "community_board" }
