package model

import (
	"time"

	"gorm.io/datatypes"
)

// CommunityThread is THE unit of the community primitive (invariant 3): one
// storage, three shapes selected by kind + anchor. id is globally stable so any
// surface can render it (invariant 10). The thread BODY (posts) lives in
// community_post; this row is identity + anchor + the shape-specific decoration.
type CommunityThread struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// Site is the tenant where the thread lives (= OAuth client/site). Every
	// access index leads with it (invariant 7).
	Site string `gorm:"not null;column:site" json:"site"`
	// Kind / AnchorKind use the ThreadKind* / AnchorKind* constants. No default
	// tag: 0 is a meaningful value (topic / board) written explicitly.
	Kind       int16 `gorm:"not null;column:kind" json:"kind"`
	AnchorKind int16 `gorm:"not null;column:anchor_kind" json:"anchor_kind"`
	// AnchorID is the stable internal id of the anchor (local id for site
	// anchors, prefixed entity id for catalog anchors); text so every anchor id
	// space shares the column (invariant 2).
	AnchorID string `gorm:"not null;column:anchor_id" json:"anchor_id"`
	// Title is present for topic/feedback, NULL for a comments thread.
	Title *string `gorm:"column:title" json:"title"`
	// HeaderImageHashes is the letmoe header-image hash list (also the refping
	// aggregation source). Nullable jsonb array.
	HeaderImageHashes datatypes.JSON `gorm:"type:jsonb;column:header_image_hashes" json:"header_image_hashes"`
	// ContentRating uses the ContentRating* constants (invariant 12); no default.
	ContentRating int16 `gorm:"not null;column:content_rating" json:"content_rating"`
	// Status uses the ThreadStatus* constants; no default. Tombstone = deleted.
	Status int16 `gorm:"not null;column:status" json:"status"`

	// Feedback-only decoration (kind=feedback; NULL for topic/comments).
	FbStatus      *int16     `gorm:"column:fb_status" json:"fb_status"`     // FeedbackStatus* constants
	FbResponse    *string    `gorm:"column:fb_response" json:"fb_response"` // official response body
	FbResponderID *int64     `gorm:"column:fb_responder_id" json:"fb_responder_id"`
	FbRespondedAt *time.Time `gorm:"column:fb_responded_at" json:"fb_responded_at"`
	// MergedIntoID is the reversible duplicate-merge redirect (Canny model): a
	// feedback thread merged into another points here. Self-referential FK.
	MergedIntoID *int64 `gorm:"type:bigint;column:merged_into_id" json:"merged_into_id"`
	// AnswerPostID marks the accepted answer (Q&A-style feedback). No FK by
	// design — it points into community_post, which has no back-reference.
	AnswerPostID *int64 `gorm:"column:answer_post_id" json:"answer_post_id"`

	// App-maintained denormalized counters (doc 11 §4.3: no DB triggers). Their
	// creation-time value is fixed (not a meaningful caller choice), so the DDL
	// default stays — the service layer maintains them transactionally (02).
	PostsCount        int32      `gorm:"not null;default:0;column:posts_count" json:"posts_count"`
	ParticipantsCount int32      `gorm:"not null;default:1;column:participants_count" json:"participants_count"`
	HighestPostNumber int32      `gorm:"not null;default:0;column:highest_post_number" json:"highest_post_number"`
	LastPostedAt      *time.Time `gorm:"column:last_posted_at" json:"last_posted_at"`

	// CreatedBy is the global user id of the thread opener.
	CreatedBy int64     `gorm:"not null;column:created_by" json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	// MergedInto is the self-referential association for MergedIntoID. GORM
	// AutoMigrate creates the FK to community_thread.
	MergedInto *CommunityThread `gorm:"foreignKey:MergedIntoID" json:"merged_into,omitempty"`
}

func (CommunityThread) TableName() string { return "community_thread" }

// CommunityPost is a flat post inside a thread (invariant 5): identity +
// post_number + root/reply/target pointers. Whether the render is threaded
// (root grouping) or a flat stream is a RENDER decision; storage never changes.
type CommunityPost struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// ThreadID references community_thread (DDL explicit FK). Part of the
	// (thread_id, post_number) unique (invariant 5) and the in-thread reply
	// sub-page index.
	ThreadID int64 `gorm:"not null;type:bigint;uniqueIndex:uq_community_post_thread_number,priority:1;index:idx_community_post_thread_root,priority:1;column:thread_id" json:"thread_id"`
	// PostNumber is the in-thread sequence (keyset pagination + permalink
	// /t/{tid}/{n}). Integer — 2.1B posts per thread is unreachable.
	PostNumber int32 `gorm:"not null;uniqueIndex:uq_community_post_thread_number,priority:2;index:idx_community_post_thread_root,priority:3;column:post_number" json:"post_number"`
	// RootPostID groups the root-based sub-thread render (kungal-style); NULL
	// for a top-level post. No FK (self-pointer, hot table).
	RootPostID    *int64 `gorm:"index:idx_community_post_thread_root,priority:2;column:root_post_id" json:"root_post_id"`
	ReplyToPostID *int64 `gorm:"column:reply_to_post_id" json:"reply_to_post_id"`
	TargetUserID  *int64 `gorm:"column:target_user_id" json:"target_user_id"`
	// AuthorID is the global user id.
	AuthorID int64 `gorm:"not null;column:author_id" json:"author_id"`
	// ContentRaw is the portable markdown source; ContentHTML the write-time
	// sanitized product (invariant 6, shared whitelist); SanitizerVersion pins
	// which sanitizer produced it (re-cook on bump).
	ContentRaw       string `gorm:"not null;column:content_raw" json:"content_raw"`
	ContentHTML      string `gorm:"not null;column:content_html" json:"content_html"`
	SanitizerVersion int32  `gorm:"not null;column:sanitizer_version" json:"sanitizer_version"`
	// ContentRating (invariant 12) + Status (PostStatus* tombstone); no default.
	ContentRating int16      `gorm:"not null;column:content_rating" json:"content_rating"`
	Status        int16      `gorm:"not null;column:status" json:"status"`
	EditedAt      *time.Time `gorm:"column:edited_at" json:"edited_at"`
	CreatedAt     time.Time  `json:"created_at"`

	// Thread is the association for ThreadID; GORM AutoMigrate creates the FK.
	Thread *CommunityThread `gorm:"foreignKey:ThreadID" json:"thread,omitempty"`
}

// The in-thread root/number index (idx_community_post_thread_root) is declared
// on the fields above; the user-footprint index (author_id, created_at DESC)
// carries a DESC sort and is created in the migrate raw-SQL section.

func (CommunityPost) TableName() string { return "community_post" }

// CommunityReaction is a post reaction. Composite PK (post_id, user_id, kind):
// one user, one reaction of each kind per post. No FK on post_id by design —
// this is a hot append table (Discourse-style).
type CommunityReaction struct {
	PostID    int64     `gorm:"primaryKey;autoIncrement:false;column:post_id" json:"post_id"`
	UserID    int64     `gorm:"primaryKey;autoIncrement:false;column:user_id" json:"user_id"`
	Kind      int16     `gorm:"primaryKey;autoIncrement:false;column:kind" json:"kind"` // ReactionKind* constants
	CreatedAt time.Time `json:"created_at"`
}

func (CommunityReaction) TableName() string { return "community_reaction" }
