package model

import "time"

// CommunityTrust is the per-user trust state (invariant 8). The PK is the
// GLOBAL user id — trust is one row across every tenant (identity is global,
// authority is local; cross-site signals only soft-hold, never hard-ban,
// invariant 9). It is NOT an identity column: the id is supplied by the IdP.
//
// The metering columns are Discourse's reading-behavior thresholds; they are
// nullable per the DDL sketch (a fresh row may leave them unset until the
// service starts accruing) and maintained by the trust engine (03). The
// promotion constants live in code (03), not here.
type CommunityTrust struct {
	UserID int64 `gorm:"primaryKey;autoIncrement:false;column:user_id" json:"user_id"`
	// Level uses the TrustLevel* constants. 0=TL0 is a meaningful zero → NO
	// default tag; the service writes it explicitly at row creation.
	Level int16 `gorm:"not null;column:level" json:"level"`

	// Promotion metering (nullable; accrued by the trust engine).
	TopicsEntered  *int32 `gorm:"column:topics_entered" json:"topics_entered"`
	PostsRead      *int32 `gorm:"column:posts_read" json:"posts_read"`
	ReadTimeS      *int32 `gorm:"column:read_time_s" json:"read_time_s"`
	DaysVisited    *int32 `gorm:"column:days_visited" json:"days_visited"`
	LikesGiven     *int32 `gorm:"column:likes_given" json:"likes_given"`
	LikesReceived  *int32 `gorm:"column:likes_received" json:"likes_received"`
	FlagsAgreed    *int32 `gorm:"column:flags_agreed" json:"flags_agreed"`
	FlagsDisagreed *int32 `gorm:"column:flags_disagreed" json:"flags_disagreed"`

	// FirstPostsHeldRemaining is the first-N-posts hold counter (approve_post_count
	// model). Wave 07 retired the blanket newcomer hold: the creation value is now
	// 0, so this is an INTENT column (no gorm default — a default tag would make
	// GORM omit the zero from INSERTs and let the DDL default win silently, the
	// gorm-default-tag-zero-value-trap). Retiring it was a measurement, not a
	// preference: across 208 production hold items it caught zero harmful posts,
	// 94.5% were approved, and the 11 rejections were all benign galgame comments
	// (one was a legitimate resource bug report). The holds that remain are the
	// ones that actually work — the synchronous Tier0 word list at write time, and
	// an AI live-mode verdict retroactively (doc 18 §6 P2).
	FirstPostsHeldRemaining int32 `gorm:"not null;column:first_posts_held_remaining" json:"first_posts_held_remaining"`
	// GrantedBoost uses the GrantedBoost* constants; NULL = no starter bonus.
	GrantedBoost *int16    `gorm:"column:granted_boost" json:"granted_boost"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (CommunityTrust) TableName() string { return "community_trust" }

// CommunityFlag is one report on a post. UNIQUE(post_id, flagger_id): one user
// flags a post once. Weight is the reporter-reputation-weighted vote (TL +
// historical accuracy, the brigading defense); a post's accumulated weight over
// threshold auto-hides it and enqueues it (service layer, 03).
type CommunityFlag struct {
	ID        int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	PostID    int64 `gorm:"not null;uniqueIndex:uq_community_flag_post_flagger,priority:1;column:post_id" json:"post_id"`
	FlaggerID int64 `gorm:"not null;uniqueIndex:uq_community_flag_post_flagger,priority:2;column:flagger_id" json:"flagger_id"`
	// Reason uses the FlagReason* constants (NULL = unspecified); Note is free
	// text (nullable per DDL).
	Reason *int16  `gorm:"column:reason" json:"reason"`
	Note   *string `gorm:"column:note" json:"note"`
	// Weight is PG real (float32) — GORM maps a bare float to numeric, so the
	// type is pinned explicitly. Written explicitly by the service → no default.
	Weight float32 `gorm:"type:real;not null;column:weight" json:"weight"`
	// Status uses the FlagStatus* constants; 0=pending is a meaningful zero →
	// NO default tag.
	Status    int16     `gorm:"not null;column:status" json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

func (CommunityFlag) TableName() string { return "community_flag" }

// CommunityReviewItem is a centralized moderation-queue row (Coral multi-site
// single queue + per-site filter). site/post_id/source/decided_* are nullable
// per the DDL sketch — a queue item can predate its per-site routing and the
// decision fields fill on resolution.
type CommunityReviewItem struct {
	ID int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	// Site (nullable) is the routing tenant; PostID (nullable) the subject post.
	Site   *string `gorm:"column:site" json:"site"`
	PostID *int64  `gorm:"column:post_id" json:"post_id"`
	// Source uses the ReviewSource* constants (NULL = unspecified) — why it
	// entered the queue.
	Source *int16 `gorm:"column:source" json:"source"`
	// Status uses the ReviewStatus* constants; 0=pending is a meaningful zero →
	// NO default tag.
	Status    int16      `gorm:"not null;column:status" json:"status"`
	DecidedBy *int64     `gorm:"column:decided_by" json:"decided_by"`
	DecidedAt *time.Time `gorm:"column:decided_at" json:"decided_at"`
	CreatedAt time.Time  `json:"created_at"`

	// TrustReviewItemID is the id of the item this row was forwarded to in the
	// unified trust inbox (step 03 outbox). NULL = not yet forwarded — the sweep
	// (FOR UPDATE SKIP LOCKED) picks up NULL rows and back-fills this on success.
	TrustReviewItemID *int64 `gorm:"column:trust_review_item_id" json:"trust_review_item_id"`
	// ForwardAttempts counts sweep delivery attempts (bookkeeping; creation value
	// 0 is fixed → the DDL default stays). No dead-letter: a row stays retryable
	// forever, the count only feeds an escalating error log.
	ForwardAttempts int32 `gorm:"not null;default:0;column:forward_attempts" json:"forward_attempts"`
}

func (CommunityReviewItem) TableName() string { return "community_review_item" }
