package galgameapp

import (
	"context"
	"database/sql"
	stderrors "errors"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
	"time"

	"api/internal/app"
	"api/internal/middleware"
	"api/internal/platform/devapi"
	"api/internal/platform/editing"
	galgamePerm "api/internal/platform/galgame/perm"
	siteModel "api/internal/platform/site/model"
	siteRepo "api/internal/platform/site/repository"
	"api/pkg/oidctoken"
	"api/pkg/utils"

	"github.com/gofiber/fiber/v3"
	"github.com/stretchr/testify/require"
	"gorm.io/datatypes"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// Integration harness for the /internal/edit/* platform proposal face (06b).
// DB-backed against a real Postgres (TEST_DATABASE_DSN, or the local default);
// a missing database skips the whole package. Provisions the developer-platform
// tables (oauth_clients + dev columns + keys/usage), the editing engine tables,
// and a synthetic galgame-family entity table so the face can be exercised
// without the full galgame content DB.
//
// SUITE DISCIPLINE: this suite writes edit_* rows scoped to the synthetic entity
// type "galgame.testthing" and cleans only those; it never TRUNCATEs the shared
// edit_* tables. Its clients/keys use the "proposetest_" prefix. TestMain holds
// two advisory suite locks for the whole run, so parallel `go test ./...` is
// safe even when every suite targets one database (unified TEST_DATABASE_DSN,
// or the shared local default): "dvap" (the devapi suite TRUNCATEs the
// developer-key tables this suite mints into) and "edts" (the edit_* tables,
// shared with the editing and catalog/handler suites). Acquire order is
// dvap → edts everywhere, so the pair can never deadlock; both values are
// distinct from every other suite key and from the editing engine's business
// classid 0x65646974 (which besides uses the two-int4 lock form).

const testJWTSecret = "propose-face-test-secret"

const (
	devapiSuiteLockKey int64 = 0x64766170 // "dvap" — must match the devapi suite
	editSuiteLockKey   int64 = 0x65647473 // "edts" — shared by the edit-table suites
)

var testDB *gorm.DB

func acquireSuiteLocks(db *sql.DB, keys ...int64) func() {
	if db == nil {
		return func() {}
	}
	ctx := context.Background()
	conn, err := db.Conn(ctx)
	if err != nil {
		return func() {}
	}
	for _, key := range keys {
		if _, err := conn.ExecContext(ctx, "SELECT pg_advisory_lock($1)", key); err != nil {
			_ = conn.Close() // closing the session releases any lock already held
			return func() {}
		}
	}
	return func() {
		for i := len(keys) - 1; i >= 0; i-- {
			_, _ = conn.ExecContext(ctx, "SELECT pg_advisory_unlock($1)", keys[i])
		}
		_ = conn.Close()
	}
}

func TestMain(m *testing.M) {
	dsn := os.Getenv("TEST_DATABASE_DSN")
	if dsn == "" {
		dsn = "host=localhost port=5432 user=postgres password=postgres dbname=kun_galgame_infra_test sslmode=disable"
	}
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{Logger: logger.Default.LogMode(logger.Silent)})
	if err != nil {
		fmt.Fprintf(os.Stderr, "SKIP: cannot connect to test database: %v\n", err)
		os.Exit(0)
	}
	sqlDB, _ := db.DB()
	release := acquireSuiteLocks(sqlDB, devapiSuiteLockKey, editSuiteLockKey)
	if err := provisionProposeSchema(db); err != nil {
		release()
		fmt.Fprintf(os.Stderr, "SKIP: propose-face schema provisioning failed: %v\n", err)
		os.Exit(0)
	}
	testDB = db
	code := m.Run()
	release()
	os.Exit(code)
}

func provisionProposeSchema(db *gorm.DB) error {
	if err := db.AutoMigrate(&siteModel.Site{}, &siteModel.OAuthClient{}); err != nil {
		return err
	}
	if err := devapi.AddOAuthClientDevColumns(db); err != nil {
		return err
	}
	if err := db.AutoMigrate(devapi.Models()...); err != nil {
		return err
	}
	if err := editing.AutoMigrate(db); err != nil {
		return err
	}
	return db.Exec(`CREATE TABLE IF NOT EXISTS propose_test_entity (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		title TEXT NOT NULL DEFAULT ''
	)`).Error
}

// testEntityType is the synthetic galgame-family entity this suite drives. Its
// default policy mirrors galgame.game's editable fields for a PLAIN actor:
// propose=open (anyone may file) + automerge=review (a plain actor holds no
// review perm and no ownership, so it NEVER automerges → an open proposal).
const testEntityType = "galgame.testthing"

func registerTestSpec(t *testing.T, reg *editing.Registry) {
	t.Helper()
	spec := editing.EntityTypeSpec{
		Family: familyGalgame,
		Type:   testEntityType,
		LoadSnapshot: func(ctx context.Context, id int64) (map[string]any, error) {
			var row struct{ Title string }
			err := testDB.WithContext(ctx).Table("propose_test_entity").
				Select("title").Where("id = ?", id).Take(&row).Error
			if stderrors.Is(err, gorm.ErrRecordNotFound) {
				return nil, editing.ErrEntityNotFound
			}
			if err != nil {
				return nil, err
			}
			return map[string]any{testEntityType + ".title": row.Title}, nil
		},
		Txn: func(ctx context.Context, fn func(tx *gorm.DB) error) error {
			return testDB.WithContext(ctx).Transaction(fn)
		},
		Fields: []editing.FieldSpec{{
			Key:      testEntityType + ".title",
			Kind:     editing.KindText,
			DiffHint: editing.DiffHintLines,
			Validate: func(v any) error {
				if _, ok := v.(string); !ok {
					return fmt.Errorf("title must be a string")
				}
				return nil
			},
			Apply: func(ctx context.Context, tx *gorm.DB, id int64, v any) error {
				return tx.Exec("UPDATE propose_test_entity SET title = ? WHERE id = ?", v, id).Error
			},
		}},
		DefaultPolicy: editing.Policy{
			Propose:   editing.ProposeOpen,
			Review:    editing.ReviewPerm("galgame.review"),
			Automerge: editing.AutomergeReview,
		},
	}
	require.NoError(t, reg.Register(spec))
}

// seedTestEntity inserts a fresh synthetic entity row and returns its id.
func seedTestEntity(t *testing.T, title string) int64 {
	t.Helper()
	var id int64
	require.NoError(t, testDB.Raw(
		"INSERT INTO propose_test_entity (title) VALUES (?) RETURNING id", title,
	).Scan(&id).Error)
	return id
}

// cleanupProposeRows removes only THIS suite's edit_* rows (scoped by the
// synthetic entity type) — never the shared tables wholesale.
func cleanupProposeRows(t *testing.T) {
	t.Helper()
	require.NoError(t, testDB.Exec(
		`DELETE FROM edit_proposal_amendment WHERE proposal_id IN
		   (SELECT id FROM edit_proposal WHERE entity_type = ?)`, testEntityType).Error)
	require.NoError(t, testDB.Exec("DELETE FROM edit_proposal WHERE entity_type = ?", testEntityType).Error)
	require.NoError(t, testDB.Exec("DELETE FROM edit_revision WHERE entity_type = ?", testEntityType).Error)
	require.NoError(t, testDB.Exec("DELETE FROM oauth_clients WHERE id LIKE 'proposetest_%'").Error)
}

// proposeEnv bundles a built platform-face app + its engine for a test.
type proposeEnv struct {
	fiber  *fiber.App
	engine *editing.Engine
	reg    *editing.Registry
}

// newProposeEnv builds the platform proposal face over a fresh engine + registry
// (with the synthetic spec) and mounts a scope-isolation stub route.
func newProposeEnv(t *testing.T) *proposeEnv {
	t.Helper()
	reg := editing.NewRegistry()
	registerTestSpec(t, reg)
	engine := editing.NewEngine(testDB, reg)

	application := &app.App{Fiber: fiber.New()}
	repo := devapi.NewRepository(testDB)
	store := devapi.NewRedisStore(nil) // nil cache → rate-limit/quota fail open
	face := devapiFace{
		mw:       devapi.NewMiddleware(repo, store),
		usageRec: devapi.NewUsageRecorder(repo, store),
	}
	ph := newProposeHandler(engine, siteRepo.NewOAuthClientRepository(testDB))
	jwtAuth := middleware.JWTAuth(oidctoken.NewVerifierWithJWKS(testJWTSecret, ""))
	mountInternalPropose(application, face, ph, jwtAuth)

	// Scope-isolation probe: a stub /internal route gated on galgame:read. A
	// propose-only key must be rejected here (403) exactly as it would be on the
	// real read face.
	application.Fiber.Group("/internal").Add([]string{fiber.MethodGet}, "/stub-read",
		face.mw.ResolveCredential,
		devapi.RequireTier(devapi.TierInternal),
		devapi.RequireScope(devapi.ScopeGalgameRead),
		func(c fiber.Ctx) error { return c.SendStatus(fiber.StatusOK) },
	)

	return &proposeEnv{fiber: application.Fiber, engine: engine, reg: reg}
}

// mintKey creates a proposetest_ client (given tier/site) and mints one key with
// the given scopes, returning the plaintext key.
func mintKey(t *testing.T, clientID, site, tier string, scopes []string) string {
	t.Helper()
	client := &siteModel.OAuthClient{
		ID:            clientID,
		Name:          "propose test app",
		Secret:        "x",
		RedirectURIs:  datatypes.JSON([]byte("[]")),
		Grants:        datatypes.JSON([]byte("[]")),
		AllowedScopes: datatypes.JSON([]byte("[]")),
		DevEnabled:    true,
		DevTier:       tier,
		CatalogSite:   site,
	}
	require.NoError(t, testDB.Create(client).Error)
	svc := devapi.NewAdminService(devapi.NewRepository(testDB), devapi.NewRedisStore(nil))
	_, plaintext, err := svc.MintKey(context.Background(), clientID, devapi.MintKeyInput{Name: "k", Scopes: scopes}, 1)
	require.NoError(t, err)
	return plaintext
}

// signJWT mints an HS256 access token the propose face's verifier accepts,
// carrying the given user id in the `id` claim.
func signJWT(t *testing.T, uid uint) string {
	t.Helper()
	tok, err := utils.GenerateAccessToken(testJWTSecret, utils.TokenClaims{ID: uid}, time.Hour)
	require.NoError(t, err)
	return tok
}

// req drives one request through the face. apiKey rides X-API-Key (the client
// identity), bearer rides Authorization (the end-user JWT); either may be "".
func req(t *testing.T, f *fiber.App, method, path, apiKey, bearer, body string) (int, []byte) {
	t.Helper()
	var r *http.Request
	if body != "" {
		r = httptest.NewRequest(method, path, strings.NewReader(body))
		r.Header.Set("Content-Type", "application/json")
	} else {
		r = httptest.NewRequest(method, path, nil)
	}
	if apiKey != "" {
		r.Header.Set("X-API-Key", apiKey)
	}
	if bearer != "" {
		r.Header.Set("Authorization", "Bearer "+bearer)
	}
	resp, err := f.Test(r)
	require.NoError(t, err)
	raw, err := io.ReadAll(resp.Body)
	require.NoError(t, err)
	return resp.StatusCode, raw
}

// galgameResolver is the real galgame family perm resolver, used by the S2S
// comparison app so a plain (roles ∅) actor evaluates identically on both faces.
var galgameResolver = galgamePerm.Resolver
